### ISSUE TITLE
托盘隐藏功能请求

### ISSUE THREAD

**Issue by Tang-pure** [PBH-BTN/PeerBanHelper#110]
本人强迫症，对于黑窗运行和托盘图标极度不适。原先一直使用vbs脚本开机后台静默自启动。
鉴于目前已经有了webui可以查看状态，希望可以隐藏托盘，简洁界面

**Comment by Gaojianli** [comment]
隐藏托盘之后你还怎么退出呢

**Comment by Tang-pure** [comment]
正常使用是不用退出的啊，一直在后台运行就行了不用退。实在要退就任务管理器杀掉，或者可以在文件目录下写个脚本杀都行
