### ISSUE TITLE
 JAR 文件在哪下载？

### ISSUE THREAD

**Issue by hanqingchina** [PBH-BTN/PeerBanHelper#140]
访问 [PBH最新版版本发布页](https://github.com/PBH-BTN/PeerBanHelper/releases/latest)，向下滚动，下载 JAR 文件。

这个页面下载的文件里没有JAR文件啊

java -jar -Xmx256M - -XX:-ShrinkHeapInSteps -jar 替换这段文字为JAR文件的文件名

然后这段就不知道怎么执行了

**Comment by bai0012** [comment]
你可以下载windows的zip文件，把里面的jar文件拿出来使用
完善ubuntu 22.04就是这样用的
