### ISSUE TITLE
能否降低jar文件的jre版本要求，以在32位系统上使用

### ISSUE THREAD

**Issue by fsxitutu** [PBH-BTN/PeerBanHelper#154]
现有的PeerBanHelper jar文件需要java21以上版本才能运行。oracle和openjdk目前并不提供java21 x86架构的二进制文件，并准备放弃x86编译选项。导致在32位系统上使用PeerBanHelper是一件比较困难的事情，甚至将来(如果使用java22封装)在32位系统上使用PeerBanHelper将变得几乎不可能。目前adoptopenjdk(adoptium)已经不再提供x86的openjdk 21二进制文件，只能使用早期的每夜版并由此可能导致一些其他问题

**Comment by Gaojianli** [comment]
现在已经是2024年了，32位win就让他进入历史的垃圾堆吧，如果是Linux，相信你有能力将pbh移植到jdk17

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："fsxitutu ***@***.***&gt;;
发送时间：2024年6月12日(星期三) 晚上11:59
收件人："PBH-BTN/PeerBanHelper" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[PBH-BTN/PeerBanHelper] 能否降低jar文件的jre版本要求，以在32位系统上使用 (Issue #154)
-----------------------------------

 

 
现有的PeerBanHelper jar文件需要java21以上版本才能运行。oracle和openjdk目前并不提供java21 x86架构的二进制文件，并准备放弃x86编译选项。导致在32位系统上使用PeerBanHelper是一件比较困难的事情，甚至将来(如果使用java22封装)在32位系统上使用PeerBanHelper将变得几乎不可能。目前adoptopenjdk(adoptium)已经不再提供x86的openjdk 21二进制文件，只能使用早期的每夜版并由此可能导致一些其他问题

**Comment by Ghost-chu** [comment]
我已经有将近 10 年没见过只支持 32 位架构的设备了    
相信你能找到的设备 CPU 都是支持 x64 的，不如装个 64 位的系统

**Comment by Gaojianli** [comment]
> 我已经有将近 10 年没见过只支持 32 位架构的设备了 相信你能找到的设备 CPU 都是支持 x64 的，不如装个 64 位的系统

冷知识，第一款x64设备发布于2003年，已经20年了

**Comment by fsxitutu** [comment]
> 现在已经是2024年了，32位win就让他进入历史的垃圾堆吧，如果是Linux，相信你有能力将pbh移植到jdk17
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："fsxitutu ***@***.***&gt;; 发送时间：2024年6月12日(星期三) 晚上11:59 收件人："PBH-BTN/PeerBanHelper" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：[PBH-BTN/PeerBanHelper] 能否降低jar文件的jre版本要求，以在32位系统上使用 (Issue #154) ----------------------------------- 现有的PeerBanHelper jar文件需要java21以上版本才能运行。oracle和openjdk目前并不提供java21 x86架构的二进制文件，并准备放弃x86编译选项。导致在32位系统上使用PeerBanHelper是一件比较困难的事情，甚至将来(如果使用java22封装)在32位系统上使用PeerBanHelper将变得几乎不可能。目前adoptopenjdk(adoptium)已经不再提供x86的openjdk 21二进制文件，只能使用早期的每夜版并由此可能导致一些其他问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

64位系统和程序的开销要比32位要大很多。我当然知道纯x86 CPU这种东西早就被清理到历史的垃圾堆里了。在低性能设备上，64位CPU跑32位系统至少在目前还是很常见的情况。
