### ISSUE TITLE
[Enhancement] 默认配置优化 

### ISSUE THREAD

**Issue by SantaSati** [PBH-BTN/PeerBanHelper#157]
如
https://github.com/PBH-BTN/PeerBanHelper/blob/43bee85c2210a0c64fde287610b19ec88aa8f51d/src/main/resources/config.yml#L5-L36
所示，默认配置中开启了两个下载器，任何一个与现有下载器配置不同都会导致逻辑出问题
`[19:24:24] [main/WARN]: [错误] TrClient 请求下载器时出现错误 java.net.ConnectException - null`
建议默认全部注释掉以及使用更友好的方式提醒

**Comment by Ghost-chu** [comment]
错误的客户端不影响正常运行，PBH 会跳过它们（但留下日志）并标记为通信异常。除了垃圾日志有点多，不影响使用。

不采纳默认注释，这样不了解 YAML 的用户会直接懵圈。

**Comment by Ghost-chu** [comment]
ci 已完成相关更改，现在有更友好的提示，并引导 WebUI 添加下载器。
