### ISSUE TITLE
Dockerhub的v4.0.8，进去后webui和日志依然显示4.0.7

### ISSUE THREAD

**Issue by sakuyamaij** [PBH-BTN/PeerBanHelper#159]
docker logs
[main/INFO]: PeerBanHelper v4.0.7 - by PBH-BTN Community, Made with ❤

web
Backend Version 4.0.7 WebUI Version 1.6.1 

反复重新拉了好几次，还是这样。看到issue也没人反馈这个问题，难道我发生灵异事件了

补充：
tag已经latest和4.0.8都试了

**Comment by Ghost-chu** [comment]
维护者发版时忘记更改版本号了，实际上的确是4.0.8
