### ISSUE TITLE
[TODO] OOBE

### ISSUE THREAD

**Issue by Ghost-chu** [PBH-BTN/PeerBanHelper#161]
PBH 缺少 OOBE 体验，用户在首次使用 PBH 时应当能够通过 OOBE 完成基本功能设定，包括：

- 设置管理 Token
- 设置安全规则（本地监听或者监听所有网卡接口）
- 添加下载器
- 配置规则
- 选择是否加入 BTN 网络
- 添加可选规则订阅

**Comment by Gaojianli** [comment]
实现建议，另外搞一个init.html，当后端没初始化时默认定向到这个文件

**Comment by Ghost-chu** [comment]
已完成 OOBE 相关功能。虽仍有改进计划，但与此 Issue 已无关联，关闭。
