### ISSUE TITLE
v4.1.0之后的版本无法访问Web UI

### ISSUE THREAD

**Issue by 675658** [PBH-BTN/PeerBanHelper#172]
环境：Docker

复现版本：v4.1.0之后的所有版本

具体表现：在Docker宿主机以及其他位置访问Web UI，连接会在握手时被重置, 在容器内正常

```shell
wget http://127.0.0.1:9898
```
<img width="455" alt="image" src="https://github.com/PBH-BTN/PeerBanHelper/assets/73889171/1c894b39-c2b2-4403-8a3d-060baab89178">

```shell
nmap -p 9898 -T4 -A -v 127.0.0.1
```
<img width="269" alt="image" src="https://github.com/PBH-BTN/PeerBanHelper/assets/73889171/71462788-3e7b-4690-a636-7a90bfb7869a">

**Comment by Ghost-chu** [comment]
这是特性，不是 BUG。  
在过往版本 PeerBanHelper 中，PBH 不遵守 address 监听地址的设定，总是监听所有网络界面。  
从 4.1.0 开始，PBH 遵守 address 监听地址的设定了，默认监听 `127.0.0.1`，需要自行修改为 `0.0.0.0` 来开启外部访问。

![image](https://github.com/PBH-BTN/PeerBanHelper/assets/30802565/dcb9223f-96de-4ccb-b083-b966439f7d39)
