### ISSUE TITLE
[TODO] deb/aur/spk/install4j 打包

### ISSUE THREAD

**Issue by Ghost-chu** [PBH-BTN/PeerBanHelper#173]
为了降低用户安装配置 PBH 的难度，应当考虑打包为 deb/aur/spk。  
Windows 系统也许可以使用 install4j 打包安装器。

也许还可以看一眼 ipk？

**Comment by Gaojianli** [comment]
没有必要，只要开了个头你要解决无穷无尽的兼容性问题和权限问题，不是所有环境都有java21，很多环境连java11都没有。docker就可以了，linux用户有能力解决这些问题

**Comment by poplar-at-twilight** [comment]
有 jar 文件就可以了，剩下的部分用户可以自行搞定

**Comment by Ghost-chu** [comment]
暂时搁置
