### ISSUE TITLE
[TODO] 下载器适配

### ISSUE THREAD

**Issue by Ghost-chu** [PBH-BTN/PeerBanHelper#176]
* ~~BiglyBT/Vuze/Azureus 可通过 Transmission 适配器适配，但最好通过插件适配~~ 完成！
* ~~Deluge 可以通过WebUI适配，但通过插件显然是更好的选择~~ 完成！
* BitComet 它的 WebUI 简陋到家，几乎什么也无法提供，但由于用户数量众多，仍然值得一试。但最好的选择还是希望有社区大佬搞个 hook 出来

**Comment by SaharaMiyoko** [comment]
![image](https://github.com/PBH-BTN/PeerBanHelper/assets/104242390/e5c6c647-10c0-4468-be89-0bf96f063ac4)

听说新的webui要出了，坐等适配
并且隔壁qbittorrent-clientblocker在api如此少的情况下也实现了部分适配

**Comment by Ghost-chu** [comment]
> [SaharaMiyoko](/SaharaMiyoko)

感谢反馈，我们一直在努力适配更多的下载器。如果新版 BitComet WebUI 能够提供足够的 API，我们也会跟进支持。

**Comment by i990049** [comment]
> > [SaharaMiyoko](/SaharaMiyoko)
> 
> 感谢反馈，我们一直在努力适配更多的下载器。如果新版 BitComet WebUI 能够提供足够的 API，我们也会跟进支持。

utorrent呢？

**Comment by Ghost-chu** [comment]
> > > [SaharaMiyoko](/SaharaMiyoko)
> > 
> > 
> > 感谢反馈，我们一直在努力适配更多的下载器。如果新版 BitComet WebUI 能够提供足够的 API，我们也会跟进支持。
> 
> utorrent呢？

uTorrent 由于其 WebUI 没有 IP 封禁 API，且软件已不再更新，暂时无解。

**Comment by i990049** [comment]
> > > > [SaharaMiyoko](/SaharaMiyoko)
> > > 
> > > 
> > > 感谢反馈，我们一直在努力适配更多的下载器。如果新版 BitComet WebUI 能够提供足够的 API，我们也会跟进支持。
> > 
> > 
> > utorrent呢？
> 
> uTorrent 由于其 WebUI 没有 IP 封禁 API，且软件已不再更新，暂时无解。

这个有前端，很多盒子都用
https://github.com/Novik/ruTorrent

**Comment by SeaHOH** [comment]
> uTorrent 由于其 WebUI 没有 IP 封禁 API，且软件已不再更新，暂时无解。

确实没有这个 API，但重复设置`ipfilter.enable`参数会触发刷新 ipfilter.dat 文件，可以此曲折地达到封禁目标 IP 的目的。

其实还有在[更新](https://forum.utorrent.com/topic/105292-35x-beta/)，不过这个更新 (基本都是些无关 BT 的外围功能) 实在不好说是不是更新，bug 也越来越多 (转用 Tixati 已三年有余，不知当前是否仍旧如此)。

其实还是建议改用其它客户端，各种 bug 真的太烦人了。可惜这么好的软件最终砸在了孙宇晨手里。
