### ISSUE TITLE
PeerID與Client Name封禁

### ISSUE THREAD

**Issue by MononeV** [PBH-BTN/PeerBanHelper#177]
規則統計頁面不再顯示PeerID與Client Name規則，目前也沒有發現有触發PeerID與Client Name封禁。
![image](https://github.com/PBH-BTN/PeerBanHelper/assets/39477101/d4a30f4d-3cfa-46cf-a78c-254eb6384e95)
同時av腳本庫有一個peer-ids.av.example，是準備用腳本代替模塊麼？

**Comment by Ghost-chu** [comment]
Transmission 本就不支持 PeerID 显示，之前显示是错误的把Client Name复制到了PeerID上，新版本中已经修复了。

PeerID/Client Name没有触发可能是bug，会晚点检查一下

**Comment by MononeV** [comment]
> Transmission 本就不支持 PeerID 显示，之前显示是错误的把Client Name复制到了PeerID上，新版本中已经修复了。
> 
> PeerID/Client Name没有触发可能是bug，会晚点检查一下

我是配合qb使用的

我的意思是，這個規則統計頁面本來除了訂閱規則之外還會顯示PeerID規則和Client Name規則，現在只有訂閱規則了

**Comment by Ghost-chu** [comment]
嗯…可能是个BUG 晚点我会检查一下，感谢反馈

**Comment by Ghost-chu** [comment]
非常感谢反馈，该问题现已在 4.1.4 中得到修复
