### ISSUE TITLE
订阅规则偶发部分 IP 地址无法正确匹配规则

### ISSUE THREAD

**Issue by Ghost-chu** [PBH-BTN/PeerBanHelper#184]
群友 *神秘人* 报告，multi-dial 规则的 101 那条规则无法匹配到订阅规则。sub 目录内的规则文件内容正常，也有少部分 IP 能够匹配到，但 101 的不行。

测试 BTN 规则正常，说明获取的 Peers 数据正确，怀疑是订阅规则模块的某部分神秘代码出问题了 @PluieM

**Comment by PluieM** [comment]
经与 1092570726 确认已修复
