### ISSUE TITLE
无法显示webui

### ISSUE THREAD

**Issue by Fvpder** [PBH-BTN/PeerBanHelper#199]
4.2.4版本升级至4.3.0版本后不显示webui
![image](https://github.com/PBH-BTN/PeerBanHelper/assets/107116491/c68f5c5c-b4f6-46c3-bb7c-c3143262235d)

**Comment by Ghost-chu** [comment]
![image](https://github.com/PBH-BTN/PeerBanHelper/assets/30802565/2e29eedb-49aa-4609-8bbc-f2e9e9feef16)

测试 4.3.0 WebUI 正常，试试看 InPrivate 打开，排除一下缓存问题

**Comment by Fvpder** [comment]
确实是缓存问题，强制刷新后正常了
