### ISSUE TITLE
多拨侦测疑似检测到无效的ipv6地址

### ISSUE THREAD

**Issue by scrpr** [PBH-BTN/PeerBanHelper#201]
**PeerBanHelper版本**：`4.2.4`
**BT客户端版本**：qBittorrent Enhanced Edition `v4.6.4.10`

检查封禁日志时发现大量3::/64, 4::/64, 5::/64和64:ff9b::/64的被多拨侦测识别到的IP，但这些IP似乎不属于任何ISP，可能是qbee使用的某种私用地址？
![64:ff9b::/64](https://github.com/PBH-BTN/PeerBanHelper/assets/46473171/390cc452-f013-4220-be70-cb285517117e)
![\d::/64](https://github.com/PBH-BTN/PeerBanHelper/assets/46473171/09242556-54f1-412a-989a-a81514aa42c2)

**Comment by Ghost-chu** [comment]
感谢反馈，PBH正式版进行IP封禁时不会考虑是否真的连接成功，开始握手就封禁了。新快照已经解决了此问题，只有开始真正连接上才检查。

**Comment by Ghost-chu** [comment]
这种无效地址通常是tracker回报给客户端，客户端尝试连接就会被PBH检测到，触发相关操作。

**Comment by Ghost-chu** [comment]
新版本现在会检查握手
