### ISSUE TITLE
[Release] 建议使用latest作为docker最新release版本的tag

### ISSUE THREAD

**Issue by povsister** [PBH-BTN/PeerBanHelper#205]
依据文档说明，docker的latest可能会是开发版或者其他奇奇怪怪的版本。
这一点让我非常不理解。因为换tag更新镜像会很麻烦，需要remove掉现在的容器，然后依据新的tag重建一个配置一样的容器。

按照docker约定俗成的规矩，latest通常代表最新release的版本，理应在每个release的同时，一并发布对应semver的tagged image。
开发版可以直接用dev tag或者nightly+date的形式来发布，pre-release同样可以依据semver发布v4.1.3-pre1这样的镜像。

也许是我孤陋寡闻了，目前不清楚为什么不遵循这个常识？

**Comment by Ghost-chu** [comment]
我都不知道你想表达什么意思……

1. 我们不推荐使用 latest，因为镜像源有时会错误的缓存 latest 版本，导致拉取到的镜像并非是最新的发布版本。
2. 你应该使用我们推荐的 docker-compose 部署办法，它和 Docker 会一同安装，只需要修改 `docker-compose.yml` 中的镜像版本号，docker-compose 就会自动重建容器
3. 不推荐不代表没有，如果你愿意看看 Docker Hub，显然相关版本都在上面自动发布了
  3.1 ![image](https://github.com/PBH-BTN/PeerBanHelper/assets/30802565/b35af30a-8e04-46d7-b8fd-eaa8b4b4b211)
4. 开发版本目前使用 `ghostchu/peerbanhelper-snapshot` 不会干扰到正式版镜像

**Comment by povsister** [comment]
> 我们不推荐使用 latest，因为镜像源有时会错误的缓存 latest 版本，导致拉取到的镜像并非是最新的发布版本。

理解，不是所有人都有条件直连docker hub的。应该在文档中说明：部分Docker mirror会过久的缓存latest镜像，如果在使用mirror的时候，建议直接填写对应版本号。

> 你应该使用我们推荐的 docker-compose 部署办法

个人反感docker compose，没有其他原因，所以一般家用场景都是单docker，或者k3s。

> 不推荐不代表没有，如果你愿意看看 Docker Hub，显然相关版本都在上面自动发布了

我提出这个问题前，特意查看了一遍docker hub，确实发现最新的tag版本和latest的digest相同，但不清楚这个是“巧合”还是“特性”，毕竟文档里给出了一个奇怪的原因。

anyway，感谢解答。
Close #205 as resolved

**Comment by Ghost-chu** [comment]
> > 我们不推荐使用 latest，因为镜像源有时会错误的缓存 latest 版本，导致拉取到的镜像并非是最新的发布版本。
> 
> 理解，不是所有人都有条件直连docker hub的。应该在文档中说明：部分Docker mirror会过久的缓存latest镜像，如果在使用mirror的时候，建议直接填写对应版本号。
> 
> > 你应该使用我们推荐的 docker-compose 部署办法
> 
> 个人反感docker compose，没有其他原因，所以一般家用场景都是单docker，或者k3s。
> 
> > 不推荐不代表没有，如果你愿意看看 Docker Hub，显然相关版本都在上面自动发布了
> 
> 我提出这个问题前，特意查看了一遍docker hub，确实发现最新的tag版本和latest的digest相同，但不清楚这个是“巧合”还是“特性”，毕竟文档里给出了一个奇怪的原因。
> 
> anyway，感谢解答。 Close #205 as resolved

还是建议使用 docker-compose，在更新等方面来的更简单一些。
