### ISSUE TITLE
[BUG] Contains 无效

### ISSUE THREAD

**Issue by Gaojianli** [PBH-BTN/PeerBanHelper#207]
### 版本号

v4.3.0

### 操作系统平台和系统架构

Linux Docker x64

### 部署方式

Docker

### 关联的下载器类型

qBittorrent

### 问题描述

Contains 无效

### 复现步骤

<img width="601" alt="78d94ad070eedff0e952dfda4b1086dc" src="https://github.com/PBH-BTN/PeerBanHelper/assets/19235246/0b18d5cf-796e-44a5-9d58-3fbd11eb9db3">

发现一个离线下载，添加规则

<img width="709" alt="b73993c38d7199d3087816c2324fc970" src="https://github.com/PBH-BTN/PeerBanHelper/assets/19235246/33acecc6-ee88-42e7-9d4c-b7fe4a8a71ac">

重启PBH
复现

### 额外信息

预期：在握手获得Client Name之后应该直接执行封禁

### 检查清单

- [X] 我确定正在运行 Github Releases 中的最新的正式版本 PeerBanHelper
- [X] 我确定我所添加的下载器已满足 README 中的前置要求（如版本号和插件）
- [X] 我确定我所提到的问题，均未在 README 和 WIKI 中有所解答
- [ ] 我确定我没有检查这个检查清单，只是闭眼选中了所有的复选框
- [X] 我确定这不是一个与安全有关的安全漏洞，它可以被安全的公开报告
- [X] 我确定我已知悉，如果我没有正确地填写问题报告表单，则 Issue 可能会被关闭

**Comment by Ghost-chu** [comment]
PBH要等它有流量之后，才会动手。晚点调整下缓存机制，可以提前封一封。

**Comment by Ghost-chu** [comment]
现在 PeerId 和 ClientName 在交换到 PeerID/ClientName 后，可跳过流量检查。
