### ISSUE TITLE
[TODO] 手动黑名单

### ISSUE THREAD

**Issue by Gaojianli** [PBH-BTN/PeerBanHelper#208]
使用PBH之后，qbt的手动黑名单功能作废了，需要提供替代。

# 需要的接口

## 查询黑名单列表
参数： `page` `page_size`
返回：
黑名单id，ip地址，命中次数，`total`

## 增加黑名单
参数：`ip`
返回：`id`

## 移除黑名单
参数：`ip`

**Comment by Ghost-chu** [comment]
已添加到 IPBlackList 接口集
