### ISSUE TITLE
通過WebUI修改下載器，Endpoint不支持容器名

### ISSUE THREAD

**Issue by MononeV** [PBH-BTN/PeerBanHelper#237]
我的endpoint是https://qbittorrent:28080，這樣導致無法從webUI修改配置，會提示not a url type

**Comment by Gaojianli** [comment]
下次请去前端页面提issue

**Comment by Gaojianli** [comment]
fixed in https://github.com/PBH-BTN/pbh-fe/commit/887e2263172d9806c2a8de35b211f8c2d950bc9e
