### ISSUE TITLE
[TODO] IP 订阅规则需要适配 DAT/eMule 格式屏蔽列表

### ISSUE THREAD

**Issue by Ghost-chu** [PBH-BTN/PeerBanHelper#244]
IP 订阅规则目前仅支持 IPAddress 对象，应对其改造以引入 IPAddressSeqRange 的支持。

这样，就可以继续引入 [DAT/eMule](https://sourceforge.net/p/peerguardian/wiki/dev-blocklist-format-dat/) 的 IP 屏蔽列表的支持。

@PluieM

**Comment by PluieM** [comment]
马上安排
