### ISSUE TITLE
[BUG] 建议新增[等待时间]功能

### ISSUE THREAD

**Issue by aagaguai** [PBH-BTN/PeerBanHelper#251]
### 版本号 - Version

v5.0.0

### 操作系统平台和系统架构 - OS  and CPU Arch

Windows Server 2022 Datacenter 21H2 amd64

### 部署方式 - Deploy method

直接运行jar

### 关联的下载器类型 - Downloader Type

qBittorrent

### 问题描述 - Issue Description

运行此项目前cpu利用率1%，运行此项目后qb的cpu利用率就到了30%左右，建议给每个种子加上等待时间，例如每30毫秒1次，以此降低频繁查询而导致的cpu资源占用大

### 复现步骤 - Reproduce steps

项目部署在本地，并且所有配置都是默认生成的，qb内的种子有约600个左右

### 截图/日志文件 - Screenshot / Logs 

[图片截图](https://d1.aag.moe/public/2024/07/16/87459059ced8677cdd24cada7e27f189.png)

### 检查清单 - Check list

- [X] 我确定正在运行 Github Releases 中的最新的正式版本 PeerBanHelper (I'm running the latest version of PBH that can be found in Github Relases)
- [X] 我确定我所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [X] 我确定我所提到的问题，均未在 README 和 WIKI 中有所解答 (This not a question/or the question that not listed in README's FAQ or WIKI)
- [ ] 我确定我没有检查这个检查清单，只是闭眼选中了所有的复选框 (I have not read these checkboxes and therefore I just ticked them all)
- [ ] 我确定这不是一个与安全有关的安全漏洞，它可以被安全的公开报告 (This not a security related issue, can be safe report in public)
- [X] 我确定我已知悉，如果我没有正确地填写问题报告表单，则 Issue 可能会被关闭 (I know this issue may closed without any warnings if I didn't fill the form correctly)

**Comment by Ghost-chu** [comment]
试试看调大检查间隔呢 https://github.com/PBH-BTN/PeerBanHelper/blob/aeeacee8f15f4d217979adae06a392db85f30ff9/src/main/resources/profile.yml#L3

**Comment by aagaguai** [comment]
> 试试看检查间隔呢
> 
> https://github.com/PBH-BTN/PeerBanHelper/blob/aeeacee8f15f4d217979adae06a392db85f30ff9/src/main/resources/profile.yml#L3

检查频率设置到10000毫秒后稍微正常了，不过这个"等待时间"的功能我觉得还是加一下更好，连续请求查询时能减少一定程度的cpu利用率

**Comment by Ghost-chu** [comment]
看看升级到 5.0.3 后，启用增量封禁，对这个问题是否有所缓解？
