### ISSUE TITLE
[社区通报] 重新封禁 -XL0019- (Xunlei 0.0.1.9) 客户端

### ISSUE THREAD

**Issue by Ghost-chu** [PBH-BTN/PeerBanHelper#254]
在迅雷 0019 版本 PBH 加白后过去的三个月里，BTN 收集了所有 BTN 用户上报的 0019 的快照信息，并进行了数据统计，以下是统计结果：

### 流量统计数据 ###

BTN => -XL0019- 总量：1879412257850 字节（1.87 TB）
-XL0019- => BTN 总量：874750177 字节（874.75 MB）

### 带宽统计数据 ###

BTN => -XL0019- 全网总带宽累加：3024853812 字节/秒 [3024.85MB/s]
最大：11214908字节/秒 (11.21MB/s); 平均：163048字节/秒 (163.04KB/s)
-XL0019- => BTN 全网总带宽累加：1884943 字节/秒 [1.88MB/s]
最大：462737字节/秒 (462.73KB/s)；平均：101字节/秒 (101B/s)

总上决定，PBH 将从 5.0.1 版本开始，重新封禁 -XL0019- (XunLei 0.0.1.9) 客户端。

**Comment by Mishasama** [comment]
江山易改本性难移，有期徒刑是真的没有意义。永远也不要对穷凶极恶之人抱有任何改邪归正的幻想。
又不是头一天上网，明知迅雷的口碑还坚持用的人就算迅雷变好了也是会开启上传限速10KB/s的。

建议结合tracker对IP进行下载行为大数据分析，对于曾经被封禁的特征指纹用户进行无限期的见面就封。

**Comment by azicen** [comment]
-XL0101-

**Comment by 1391189216** [comment]
> 江山易改本性难移，有期徒刑是真的没有意义。永远也不要对穷凶极恶之人抱有任何改邪归正的幻想。 又不是头一天上网，明知迅雷的口碑还坚持用的人就算迅雷变好了也是会开启上传限速10KB/s的。
> 
> 建议结合tracker对IP进行下载行为大数据分析，对于曾经被封禁的特征指纹用户进行无限期的见面就封。

迅雷什么时候变好了？除了xunlei0100之外，其他的所有版本都不会做种。
