### ISSUE TITLE
[功能请求] 连锁封禁的封禁原因显示原始封禁IP的原因

### ISSUE THREAD

**Issue by azicen** [PBH-BTN/PeerBanHelper#260]
连锁封禁时，目前只显示原始封禁的 IP，难以确定真正的封禁原因。

![image](https://github.com/user-attachments/assets/6a140874-7443-4313-9561-f7d632b6800b)

希望在 `封禁名单-封禁原因` 和 `封禁日志-描述`  中显示原始 IP 的封禁原因。

**Comment by Ghost-chu** [comment]
技术问题，实现不了，搁置了
