### ISSUE TITLE
[Feature] 下载器不可用时的退避措施

### ISSUE THREAD

**Issue by Gaojianli** [PBH-BTN/PeerBanHelper#264]
昨天，我修改了下载器WebUI的密码，但是我忘记了修改PBH相应的配置，因此PBH不断进行了尝试，导致了IP被封禁。由于我的下载器使用了反向代理，结果导致了::1被封禁。由于PBH不停的进行重试，因此导致我今天晚上依旧无法登录（ip被封禁），想讨论一下，针对配置存在错误的场景，是否存在退避措施（指数级增加重试间隔）以避免DoS

**Comment by Ghost-chu** [comment]
![image](https://github.com/user-attachments/assets/e2017036-9d77-4a19-ad54-5c72075984e8)
![image](https://github.com/user-attachments/assets/13ee5003-8ed7-4e4c-9fc3-f8d3a4678b5f)
