### ISSUE TITLE
[功能请求]新增一个流量统计仪表盘

### ISSUE THREAD

**Issue by SteveYu000** [PBH-BTN/PeerBanHelper#269]
一个可以显示所有上传下载流量总量统计的仪表盘，类似封禁日志，不过显示的是过去一段时间内所有的流量监控情况
目的：有助于分析未被发现的吸血客户端

**Comment by Ghost-chu** [comment]
由于部分下载器不提供相关数据，且通过 WebUI 轮询获得数据既麻烦也不准确。  
PBH 也无法在合理磁盘使用、RAM消耗、CPU时间的条件下记录相关数据，暂时不考虑此功能。请使用下载器自带的数据统计功能代替。

**Comment by Ghost-chu** [comment]
Reopen，攻坚克难取得突破性进展

**Comment by Gaojianli** [comment]
提问，如何唯一标识一个客户端呢

**Comment by Ghost-chu** [comment]
> 提问，如何唯一标识一个客户端呢

PBH 唯一客户端由以下三个关键信息识别：

* IP 地址
* Torrent
* 下载器名称

上述三要素相同的，识别为同一个客户端。使用 IPV6 的用户，IPV6 按原样不做任何处理。

**Comment by Ghost-chu** [comment]
![image](https://github.com/user-attachments/assets/1073dfa0-5dcb-4cad-8c13-efe5ac2656f8)

**Comment by SteveYu000** [comment]
- 希望可以增加查看最近一段时间（如30天）内总共的流量情况。因为运营商通常会限制每个月的总上传量。可以通过调整时间精度（如每30天为一个柱状图）实现，或者直接在图表下方增加一栏总流量数。

- 增加针对每个客户端的流量统计
- 可供参考的UI：
![11 39 21@2x](https://github.com/user-attachments/assets/9f5c1ce7-a710-49bc-8c8b-0e6405d5fc2e)
[https://www.leishi.io/blog/posts/2021-09/Making-A-Downloader-Traffic-Panel-On-Synology-Using-Grafana-And-Promethus/](url)
