### ISSUE TITLE
[BUG] 同一台主机下docker用bridge创建的PBH不能添加macvlan网络的下载器

### ISSUE THREAD

**Issue by Kosakanao** [PBH-BTN/PeerBanHelper#273]
### 版本号 - Version

5.0.5

### 操作系统平台和系统架构 - OS  and CPU Arch

6.1.79-Unraid x86_64 GenuineIntel GNU/Linux

### 部署方式 - Deploy method

Docker 镜像

### 关联的下载器类型 - Downloader Type

qBittorrent

### 问题描述 - Issue Description

在用bridge网络创建的PBH添加下载器时会提示
无法连接到下载器，登录时出现网络错误：java.net.ConnectException: Host is unreachable
<img width="731" alt="Screenshot 2024-07-21 at 10 38 49 AM" src="https://github.com/user-attachments/assets/0b03a873-80d2-4178-8154-e3e682cb348a">

### 复现步骤 - Reproduce steps

1.同一台主机
2.pbh bridge模式，下载器macvlan获得局域网内独立ip
3.pbh web添加出现错误

### 截图/日志文件 - Screenshot / Logs 

<img width="1039" alt="Screenshot 2024-07-21 at 10 35 58 AM" src="https://github.com/user-attachments/assets/52d7f2dd-f421-481a-9116-462f6f92c45f">
<img width="1292" alt="Screenshot 2024-07-21 at 10 44 24 AM" src="https://github.com/user-attachments/assets/65faa337-ab1f-4abd-b378-d13e7fb4c59a">

### 额外信息 - Addition Information

目前用macvlan模式单独也给pbh局域网内ip 10.0.0.x后可以正常添加下载器10.0.0.x

### 检查清单 - Check list

- [X] 我确定正在运行 Github Releases 中的最新的正式版本 PeerBanHelper (I'm running the latest version of PBH that can be found in Github Relases)
- [X] 我确定我所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [X] 我确定我所提到的问题，均未在 README 和 WIKI 中有所解答 (This not a question/or the question that not listed in README's FAQ or WIKI)
- [ ] 我确定我没有检查这个检查清单，只是闭眼选中了所有的复选框 (I have not read these checkboxes and therefore I just ticked them all)
- [X] 我确定这不是一个与安全有关的安全漏洞，它可以被安全的公开报告 (This not a security related issue, can be safe report in public)
- [X] 我确定我已知悉，如果我没有正确地填写问题报告表单，则 Issue 可能会被关闭 (I know this issue may closed without any warnings if I didn't fill the form correctly)

**Comment by Ghost-chu** [comment]
本仓库Issues不处理非软件问题，对于有特殊网络环境的用户，请自行调整您的Docker Engine配置。报告的问题超出了我们提供支持的范围。
