### ISSUE TITLE
[BUG] v5.x 添加封禁会重新开启 Transmission 已停止的种子

### ISSUE THREAD

**Issue by jqtmviyu** [PBH-BTN/PeerBanHelper#285]
### 版本号 - Version

v5.0.6 或 v5.0.7

### 操作系统平台和系统架构 - OS  and CPU Arch

arm64

### 部署方式 - Deploy method

Docker

### 关联的下载器类型 - Downloader Type

Transmission 4.0.5

### 问题描述 - Issue Description

添加封禁会重新开启 Transmission 已停止的种子, 包括手动停止和达到分享率自动停止的.

### 复现步骤 - Reproduce steps

1. 从4.4.1升级到v5.0.?, 再升级到v5.0.7
2. 启动docker

### 截图/日志文件 - Screenshot / Logs 

启动前:
![0](https://github.com/user-attachments/assets/819b6a00-c98d-4e41-924b-572d8607ef43)
启动后:
![3](https://github.com/user-attachments/assets/a9a169b4-7d99-4001-968e-fa18ddea0004)

### 额外信息 - Addition Information

旧版本4.4.1未发现该问题, 已回退.

### 检查清单 - Check list

- [X] 我确定正在运行 Github Releases 中的最新的正式版本 PeerBanHelper (I'm running the latest version of PBH that can be found in Github Relases)
- [X] 我确定我所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [X] 我确定我所提到的问题，均未在 README 和 WIKI 中有所解答 (This not a question/or the question that not listed in README's FAQ or WIKI)
- [ ] 我确定我没有检查这个检查清单，只是闭眼选中了所有的复选框 (I have not read these checkboxes and therefore I just ticked them all)
- [X] 我确定这不是一个与安全有关的安全漏洞，它可以被安全的公开报告 (This not a security related issue, can be safe report in public)
- [X] 我确定我已知悉，如果我没有正确地填写问题报告表单，则 Issue 可能会被关闭 (I know this issue may closed without any warnings if I didn't fill the form correctly)

**Comment by Ghost-chu** [comment]
目前暂时没有改善 PBH 对 TR 支持的计划。  
Transmission 的提供的 API 相当差。PBH 已经单独给 TR 写了大量 Workaround 代码，包括但不限于同时调用 TR 会崩溃、封禁 IP 只能要求其更新屏蔽列表、断开恶意 IP 连接必须屏蔽后暂停-恢复种子等多种令人窒息的操作。

建议向 qBittorrent 迁移。

**Comment by Ghost-chu** [comment]
应该修好了
