### ISSUE TITLE
转换 Active Monitoring 规则模块到内嵌核心功能

### ISSUE THREAD

**Issue by Ghost-chu** [PBH-BTN/PeerBanHelper#287]
Active Monitoring 能够在 PBH 每次联系下载器时获取所有连接的 Peers 的数据，并将它们写入/更新到 SQLite 中，持久化存储。最初设计用途为给 PBH Plus 发电用户提供持久化数据保存，计算上下载总量等统计面板数据。  

但数日前用户开始报告出现慢刷流手段（通过频繁切换 IP 地址，一段时间内保持有限数量且来自不同段的 IP 连接到下载器），利用 PeerBanHelper 内存缓存容量有限的问题，等待自己从内存缓存中过期后再重新连接（此时不管是 PBH 还是下载器都会认为这是一个新 Peer），除非被 BTN 捕获，否则一直可以逍遥法外。

本 Issue 旨在将此功能转换为核心功能之一，当用户*认为且坚定的相信*自己的硬件能够处理大量查询和更新时，用户可开启 Active Monitoring 功能。开启后其它功能模块应当也可以从中检索查找数据。

**Comment by mzhboy** [comment]
频繁写入db这个问题能否解决一下，我的pi用的tf卡不耐写啊。否则只能想办法把db放到ram文件系统了

**Comment by Ghost-chu** [comment]
> 频繁写入db这个问题能否解决一下，我的pi用的tf卡不耐写啊。否则只能想办法把db放到ram文件系统了

TF 卡还是别开这个功能了，寿命太短了。

**Comment by paulzzh** [comment]
可以考虑支持mysql之类的数据库，解决存放问题且查询效率要比sqlite好

**Comment by Ghost-chu** [comment]
关闭：PCB 自己现在有自己的独立数据存储表，采用类似 Active Monitoring 的存储和缓存机制。
