### ISSUE TITLE
提供关闭 UI 的方法

### ISSUE THREAD

**Issue by Puqns67** [PBH-BTN/PeerBanHelper#291]
希望能提供配置项或运行参数以禁用 UI。

原因：
使用命令行启动应用还需要下载运行库，启动后的 UI 除了能显示日志没有其他作用。

另外这个 UI 的问题也有些多。
使用环境：Arch Linux, KDE Plasma 6, Wayland。
JavaFx 不无法显示中文字符，Swing UI 可以。
UI 有时会直接卡死，无法操作。
有时会使用 JavaFx UI 有时有会变回 Swing UI。
最小化功能与 Plasma 的任务栏不兼容，无法打开最小化后的右键菜单，右键单击后还会通过 Pipewire 请求获取鼠标输入？

个人感觉作为一个使用 WebUI 的软件，或者说服务端软件，完全不需要集成 UI 这么个功能。还会提高维护的复杂程度。能适当的实现最小化至任务栏就已经完全足够了。

**Comment by Ghost-chu** [comment]
请在启动命令行的最后添加 nogui 参数禁用 GUI。

```
java ........ -jar PeerBanHelper.jar nogui
```

Linux 系统建议使用 Docker 运行。
