### ISSUE TITLE
[BUG] 下载器URL末端如存在'/'会提示认证失败

### ISSUE THREAD

**Issue by licia-tia** [PBH-BTN/PeerBanHelper#295]
### 版本号 - Version

v5.1.0

### 操作系统平台和系统架构 - OS  and CPU Arch

Ubuntu x86

### 部署方式 - Deploy method

Docker 镜像

### 关联的下载器类型 - Downloader Type

qBittorrent

### 问题描述 - Issue Description

qbt下载器URL末端如存在'/'会提示认证失败

示例：
http://localhost:1234 成功
http://localhost:1234/ 失败

### 复现步骤 - Reproduce steps

1. 添加新的下载器
2. 在URL末端带上'/'
3. 添加失败

### 检查清单 - Check list

- [X] 我确定正在运行 Github Releases 中的最新的正式版本 PeerBanHelper (I'm running the latest version of PBH that can be found in Github Relases)
- [X] 我确定我所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [X] 我确定我所提到的问题，均未在 README 和 WIKI 中有所解答 (This not a question/or the question that not listed in README's FAQ or WIKI)
- [ ] 我确定我没有检查这个检查清单，只是闭眼选中了所有的复选框 (I have not read these checkboxes and therefore I just ticked them all)
- [x] 我确定这不是一个与安全有关的安全漏洞，它可以被安全的公开报告 (This not a security related issue, can be safe report in public)
- [X] 我确定我已知悉，如果我没有正确地填写问题报告表单，则 Issue 可能会被关闭 (I know this issue may closed without any warnings if I didn't fill the form correctly)

**Comment by Ghost-chu** [comment]
按预期工作，PBH会自动添加末尾斜线，请勿手动添加。

**Comment by Gaojianli** [comment]
> 按预期工作，PBH会自动添加末尾斜线，请勿手动添加。

用一个path join库吧，能自动处理这种问题
