### ISSUE TITLE
删除对本地地址的白名单

### ISSUE THREAD

**Issue by ztmzzz** [PBH-BTN/PeerBanHelper#301]
遇到一个神奇的客户端，可以隐藏自己的ip地址，使得qbittorrent只会显示本机地址，从而绕过封禁。
10.1.219.64是我k8s的vxlan.calico地址，直接运行qbittorrent也会得到192.168.xx.xx的本机地址。
![image](https://github.com/user-attachments/assets/5db9104c-6c1c-45bc-ba31-786bc3c9c7db)

**Comment by Ghost-chu** [comment]
你 NAT 自己配错了，检查网关 IP NAT 配置

**Comment by ztmzzz** [comment]
其他用户的ip都是正确的，就这个不行。而且对方的ip已经在黑名单中了，大概率是恶意客户端。

**Comment by Ghost-chu** [comment]
没有恶意客户端可以伪装自己为内网 IP，只要对方连接到互联网，ISP 首先就需要检查对方给定 IP 地址是否正确。如果不正确，ISP 的路由器和交换设备是无法把它的数据正确传输到你这里，效果就是断网。

任何能够连接到你的 Peer 一定拥有一个正确的 IP 地址，如果它丢失了正确的 IP 地址，则一定是你的路由上的某个设备的配置出现了问题（路由器（特别是 OpenWRT）、Docker 网络配置皆有可能）。

只要你有一点点的网络知识，你就清楚这一点。

这并非 PBH 的问题，自然也不应该由 PBH 修复，我们也无法修复它。如果你没有搞定复杂网络配置的能力，那么最好就不要整什么 vlan 这种花哨东西。
