### ISSUE TITLE
[BUG] 最多封禁页面显示的数据为空

### ISSUE THREAD

**Issue by CaoMeiYouRen** [PBH-BTN/PeerBanHelper#303]
### 版本号 - Version

Backend Version	
5.1.0
 (9eb338a7) 
WebUI Version	
2.1.0 
 (1aa881be) 

### 操作系统平台和系统架构 - OS  and CPU Arch

centos7.9

### 部署方式 - Deploy method

docker 

### 关联的下载器类型 - Downloader Type

qBittorrent

### 问题描述 - Issue Description

已经有了封禁ip，但最多封禁页面显示的数据为空。

`/api/bans/ranks?limit=50`接口返回的数据为空数组`[]`

封禁名单、封禁日志等都正常统计了。

### 复现步骤 - Reproduce steps

切换到 `最多封禁` 页面

### 截图/日志文件 - Screenshot / Logs 

![image](https://github.com/user-attachments/assets/b0e69b73-c33c-4c01-9641-67ffbffb300c)
![image](https://github.com/user-attachments/assets/081a0c8a-5ae7-4c29-91d4-d319acc14b68)
![image](https://github.com/user-attachments/assets/094f5936-97ea-4525-aad4-dfd1c861648a)

### 检查清单 - Check list

- [X] 我确定正在运行 Github Releases 中的最新的正式版本 PeerBanHelper (I'm running the latest version of PBH that can be found in Github Relases)
- [X] 我确定我所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [X] 我确定我所提到的问题，均未在 README 和 WIKI 中有所解答 (This not a question/or the question that not listed in README's FAQ or WIKI)
- [ ] 我确定我没有检查这个检查清单，只是闭眼选中了所有的复选框 (I have not read these checkboxes and therefore I just ticked them all)
- [X] 我确定这不是一个与安全有关的安全漏洞，它可以被安全的公开报告 (This not a security related issue, can be safe report in public)
- [X] 我确定我已知悉，如果我没有正确地填写问题报告表单，则 Issue 可能会被关闭 (I know this issue may closed without any warnings if I didn't fill the form correctly)

**Comment by Ghost-chu** [comment]
实际上这不是一个 BUG，只有被封禁超过 2 次的 IP 地址才会显示在上面（以避免显示太多无用数据）。  
不过，在现阶段的日志清除时间的限制下，似乎很难看到满足条件的记录条目（默认的封禁时间较长）。这确实有待改进。

**Comment by Ghost-chu** [comment]
在快照中得到修复
