### ISSUE TITLE
[社区通报] 新的全随机 PeerID 恶意客户端样本

### ISSUE THREAD

**Issue by Ghost-chu** [PBH-BTN/PeerBanHelper#309]
BTN 近期发现新的恶意客户端样本，特征如下：

**PeerID:** 全随机
**ClientName:** `Gopeed dev`
**端口:** 全随机

**注意：官方版本 Gopeed 没有随机 PeerID 的行为，且固定为 -GPxxxx-。此样本为恶意修改版本**

**2024/08/08 更新：BTN 发现样本已更新为全随机 PeerID+全随机 ClientName，~~用户脚本已失效~~已更新 v2 版本。**

这意味着传统过滤器在未来将会彻底失去作用。

![image](https://github.com/user-attachments/assets/307ac4bf-2901-48cd-9412-2eb41723bbcb)

---

PeerBanHelper 可以加载用户脚本来检测此恶意客户端，请[下载检测脚本(v2)](https://gist.github.com/Ghost-chu/9bd06cc5f39ccc66e563a2a9672bb3d6)并将其重命名为 `gopeed-random-peerid-v2.av` 并放入 `data/scripts` 文件夹。重启 PBH 即可加载。

与此同时，BTN-Collected-Rules 已创建了一个新的 IP 规则集，收集相关 IP 地址：

https://github.com/PBH-BTN/BTN-Collected-Rules/blob/main/random-peerid.txt

**Comment by Zzzwannasleep** [comment]
支持

**Comment by Ghost-chu** [comment]
2024/08/08 更新：此样本发生变种，新的变种 PeerID 和 ClientName 都已随机。

**Comment by ShenHongFei** [comment]
![image](https://github.com/user-attachments/assets/927cc0e0-6166-4d57-8355-636a6621efeb)
遇到了同样的 gopeed dev 吸血客户端，很恶劣，总共 8 GB 的种子上传了 32 GB
