### ISSUE TITLE
[功能请求]适用于Tracker服务器的PeerBanHelper

### ISSUE THREAD

**Issue by pmman289** [PBH-BTN/PeerBanHelper#313]
我的tracker服务器经常遭到hp-torrent此类恶意peer的频繁请求，严重占用带宽，希望能够将PeerBanHelper接入tracker来屏蔽这类恶意peer，同时还能接入BTN网络以便它们在连接到其它peer前提前封禁

**Comment by Ghost-chu** [comment]
建议您在 Tracker 的 WAF 新增规则，定时拉取 https://github.com/PBH-BTN/BTN-Collected-Rules 的 IP 地址清单，将 hp_torrent 等此类恶意 Peer 的 IP 地址放入屏蔽列表中，缓解 Tracker 压力。同时也可以考虑在 Tracker 程序中检测 HTTP 请求的 User-Agent 以及宣告的 PeerID。

从 Tracker 屏蔽 Peer 并不能阻止它们连接到其它 Peer，因为下载器还会通过 PEX 和 DHT 交换 Peer。

**Comment by pmman289** [comment]
> 建议您在 Tracker 的 WAF 新增规则，定时拉取 https://github.com/PBH-BTN/BTN-Collected-Rules 的 IP 地址清单，将 hp_torrent 等此类恶意 Peer 的 IP 地址放入屏蔽列表中，缓解 Tracker 压力。同时也可以考虑在 Tracker 程序中检测 HTTP 请求的 User-Agent 以及宣告的 PeerID。
> 
> 从 Tracker 屏蔽 Peer 并不能阻止它们连接到其它 Peer，因为下载器还会通过 PEX 和 DHT 交换 Peer。

非常感谢您的建议，前者确实可以通过WAF屏蔽解决，但是如果能直接将tracker提供的信息接入BTN网络，是否能够更快地封禁恶意peer；而且这些由企业批量运行的恶意peer可能主要从tracker获取peer信息，据我观察它们主要向[https://github.com/XIU2/TrackersListCollection](url)的best tracker名单中的tracker进行查询，且频率极高，怀疑它们能做到高效吸血的其中一个原因可能就是这一点。

**Comment by Anonyame** [comment]
除此以外Thunder似乎也存在往复扫描Tracker的情况，有Tracker维护者曾通过返回空信息来避免其反复请求。

**Comment by Ghost-chu** [comment]
> > 建议您在 Tracker 的 WAF 新增规则，定时拉取 https://github.com/PBH-BTN/BTN-Collected-Rules 的 IP 地址清单，将 hp_torrent 等此类恶意 Peer 的 IP 地址放入屏蔽列表中，缓解 Tracker 压力。同时也可以考虑在 Tracker 程序中检测 HTTP 请求的 User-Agent 以及宣告的 PeerID。
> > 从 Tracker 屏蔽 Peer 并不能阻止它们连接到其它 Peer，因为下载器还会通过 PEX 和 DHT 交换 Peer。
> 
> 非常感谢您的建议，前者确实可以通过WAF屏蔽解决，但是如果能直接将tracker提供的信息接入BTN网络，是否能够更快地封禁恶意peer；而且这些由企业批量运行的恶意peer可能主要从tracker获取peer信息，据我观察它们主要向[https://github.com/XIU2/TrackersListCollection](url)的best tracker名单中的tracker进行查询，且频率极高，怀疑它们能做到高效吸血的其中一个原因可能就是这一点。

PBH 的工作原理决定了无法支持 Tracker，特别是不同的 Tracker 软件其实现也截然不同。  
对于 Tracker 来说，这些工作应由 Tracker 软件完成。接入 BTN 网络需要提交可信 Peers 数据，而 Tracker 的数据并无法满足相关要求。对于 Tracker 来说，这些数据可被轻松伪造。
