### ISSUE TITLE
[BUG] BTN-Collected-Rules误报IP导致PBH把自己IPban了

### ISSUE THREAD

**Issue by yuricon** [PBH-BTN/PeerBanHelper#316]
### 版本号 - Version

v5.1.0

### 操作系统平台和系统架构 - OS  and CPU Arch

win11 x64

### 部署方式 - Deploy method

windows .zip

### 关联的下载器类型 - Downloader Type

qBittorrent Enhanced Edition v4.6.5.10

### 问题描述 - Issue Description

今天更新BTN-Collected-Rules-all的IP订阅后发现PBH突然根据IP把自己IP Ban了，说明自己的IP进了订阅的黑名单，这可能是BTN的误报
主要问题有2个：
1.QBEE连接列表里面可能会出现自己IP，并且会被PBH检测判定BAN自己
2.BTN的progress-rewind误报反馈，IP：183.93.114.XX（整段就这一个），我并没有过重下载操作
web ui问题：
禁封名单和禁封日志里有些种子显示会对不上（包括种子名称和大小），比如A B C3个不同的种子名称在GUI和webui的禁封名单显示A B C，但禁封日志里都显示D，从QBEE连接列表来看禁封日志的应该是错误记录，我不确认这是否和早期版本一路更新覆盖安装过来有关

### 复现步骤 - Reproduce steps

根据筛查后发现是进progress-rewind里面了，确认了PBH触发的IP和端口确实是我使用的QBEE，我并没有重下的操作
触发ban的种子是我自己100%进度做种中的，也就是说在连接列表里出现了我自己的IP（这点以前观察QBEE连接列表里面确实有过，而且进度显示0.00%），并且在没显示客户端ID PeerID和进度0的情况下直接被IPban规则ban了
从过程上来说是根据IPban，PBH这个操作运行没问题，但可能会因为这种特殊情况导致其他可能发生的未知问题

再就是为什么会进progress-rewind的排查
因为我是宽带用户，我并不能100%确定我是否一直用的这个IP，只能确定最近几个月没重启过光猫
我的PBH显示并未加入BTN网络，也没有自己IP触发进度重置的BAN报道，那么这个IP应该是由其他PBH用户反馈的
我使用的BT客户端是qBittorrent Enhanced Edition v4.6.5.10，并没有手动重下的操作
如果IP之前是我一直在使用，那可能是QBEE的BUG或者其他用户的误报，如果不是那可能是之前此IP用户导致的，目前我在使用的情况下可以更新剔除

### 截图/日志文件 - Screenshot / Logs 

![2024-08-10 183240](https://github.com/user-attachments/assets/b40b7083-6581-4531-b3fe-2d8461e3aee4)
![屏幕截图 2024-08-10 185725](https://github.com/user-attachments/assets/4d324ae7-b5cb-48e2-b02d-408b641209ec)
因此同时发现的Web UI禁封日志种子名称记录错误
![屏幕截图 2024-08-10 185917](https://github.com/user-attachments/assets/d3aa9b4e-0db2-4b36-adab-f2080968e8c3)

### 额外信息 - Addition Information

QBEE ban 了自己公网IP好像也感觉不出来什么影响

### 检查清单 - Check list

- [X] 我确定正在运行 Github Releases 中的最新的正式版本 PeerBanHelper (I'm running the latest version of PBH that can be found in Github Relases)
- [X] 我确定我所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [ ] 我确定我所提到的问题，均未在 README 和 WIKI 中有所解答 (This not a question/or the question that not listed in README's FAQ or WIKI)
- [ ] 我确定我没有检查这个检查清单，只是闭眼选中了所有的复选框 (I have not read these checkboxes and therefore I just ticked them all)
- [ ] 我确定这不是一个与安全有关的安全漏洞，它可以被安全的公开报告 (This not a security related issue, can be safe report in public)
- [ ] 我确定我已知悉，如果我没有正确地填写问题报告表单，则 Issue 可能会被关闭 (I know this issue may closed without any warnings if I didn't fill the form correctly)

**Comment by Ghost-chu** [comment]
已修正
