### ISSUE TITLE
[BUG] Unsupported locale: en_hk

### ISSUE THREAD

**Issue by Blake57H** [PBH-BTN/PeerBanHelper#324]
### 版本号 - Version

v5.1.0

### 操作系统平台和系统架构 - OS  and CPU Arch

Windows 11 x64 (10.0.22631.4037)

### 部署方式 - Deploy method

Windows .ZIP Portable

### 关联的下载器类型 - Downloader Type

qBittorrent 4.6.5

### 问题描述 - Issue Description

Program throwing "unsupported locale" error upon launch. 

### 复现步骤 - Reproduce steps

1. Set system regional format to "English (Hong Kong SAR)".
2. Launch the program. 
3. Console showing "unsupported locale" error message.
4. You can make it worse by removing data directory then start the program in console.

### 截图/日志文件 - Screenshot / Logs 

<img width="741" alt="Screenshot 2024-08-16 161002" src="https://github.com/user-attachments/assets/cff1b06d-6143-46ec-b8e0-3365b8f94ad9">
<img width="750" alt="Screenshot 2024-08-16 160939" src="https://github.com/user-attachments/assets/834cdc84-ef6c-4d6c-a13d-9271d76d46ef">
[latest.log](https://github.com/user-attachments/files/16634846/latest.log)

### 额外信息 - Addition Information

I upgraded the program from v3.3.7 today. Previous version doesn't have this issue.

The bug doesn't affect peer banning function. Bad peers still get banned (verified by looking at the .db file in `data/persist`), but ban messages won't show up in console or `latest.log`.

### 检查清单 - Check list

- [X] 我确定正在运行 Github Releases 中的最新的正式版本 PeerBanHelper (I'm running the latest version of PBH that can be found in Github Relases)
- [X] 我确定我所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [X] 我确定我所提到的问题，均未在 README 和 WIKI 中有所解答 (This not a question/or the question that not listed in README's FAQ or WIKI)
- [ ] 我确定我没有检查这个检查清单，只是闭眼选中了所有的复选框 (I have not read these checkboxes and therefore I just ticked them all)
- [X] 我确定这不是一个与安全有关的安全漏洞，它可以被安全的公开报告 (This not a security related issue, can be safe report in public)
- [X] 我确定我已知悉，如果我没有正确地填写问题报告表单，则 Issue 可能会被关闭 (I know this issue may closed without any warnings if I didn't fill the form correctly)

**Comment by Ghost-chu** [comment]
Hi, you can change the language setting in `config.yml` by changing `language: default` to `language: en_us` to force PBH use English(US) language.

**Comment by Blake57H** [comment]
Thanks, that helped.
