### ISSUE TITLE
[BUG] progress-rewind检测可靠性可能存在问题

### ISSUE THREAD

**Issue by yuricon** [PBH-BTN/PeerBanHelper#325]
### 版本号 - Version

v.5.1.0

### 操作系统平台和系统架构 - OS  and CPU Arch

win11 x64

### 部署方式 - Deploy method

.zip

### 关联的下载器类型 - Downloader Type

qBittorrent Enhanced Edition v4.6.5.10

### 问题描述 - Issue Description

https://github.com/PBH-BTN/PeerBanHelper/issues/316
问题再现，又进banlist了

这次可以确定此IP（183.93.114.xx）一直是我在使用，请排查qb（qbee）客户端是否存在bug，以及pbh进度回退检测机制是否可靠

### 复现步骤 - Reproduce steps

最近progress-rewind里ip大量增加是否也和这个问题有关
可以先统计下里面qb（qbee）占比来定位是否和qb本身有关
我自己观察的进度回滚记录里（因为有订阅IP和banlist1个月不到20个样本），qb占比80%，个别qbee和其他，人工分析后大部分应该是正确封禁，有着明显的特征，比如同网段，同ip多次触发，peerid和客户端名称对不上等，排除这些剩下的样本中都只出现过一次
然后我发现一个有趣的现象，剩下的这些样本在封禁日志里有一部分指向同一个种子，这个种子正是之前提到过webui 封禁日志bug中提到的种子D（种子A B C在封禁日志里都显示D，D具体为airota&vcb的asobi asobase BDRIP reseedv2，然后同时是我封禁日志里最早的记录，7月16日14：46，种子是7月9日添加完成覆盖v1的种子）
根据这个情况我有一个猜想，如果封禁日志是读取之前更新的长久保存的数据库，并且里面的对应种子记录错误，然后一个正常客户端下载进度被错误匹配数据库记录里的种子，那么就可能会被误判
通过封禁日志的图表统计查看种子D的占比最高298（26.99%），但很明显里面95%应该都是错误记录的统计，如果猜想正确，那么这个误报率会非常高

同时我发现有一些被IP订阅ban的记录快照是100%进度做种中，并且有给我上传数据的，这些很可能也是跟我一样被误判进了banlist，而且很巧的是这里面99%也都在封禁日志中错误的指向D，不过已经是IP订阅 ban了，并不能当作回滚汇报和D的强相关，只能侧面证明目前存在很多误报的情况

### 检查清单 - Check list

- [X] 我确定正在运行 Github Releases 中的最新的正式版本 PeerBanHelper (I'm running the latest version of PBH that can be found in Github Relases)
- [X] 我确定我所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [ ] 我确定我所提到的问题，均未在 README 和 WIKI 中有所解答 (This not a question/or the question that not listed in README's FAQ or WIKI)
- [ ] 我确定我没有检查这个检查清单，只是闭眼选中了所有的复选框 (I have not read these checkboxes and therefore I just ticked them all)
- [ ] 我确定这不是一个与安全有关的安全漏洞，它可以被安全的公开报告 (This not a security related issue, can be safe report in public)
- [ ] 我确定我已知悉，如果我没有正确地填写问题报告表单，则 Issue 可能会被关闭 (I know this issue may closed without any warnings if I didn't fill the form correctly)

**Comment by Ghost-chu** [comment]
谢谢，这是一个已知问题，目前我们在着手解决它。

https://github.com/PBH-BTN/PeerBanHelper/pull/323
