### ISSUE TITLE
程序 GUI 字体乱码

### ISSUE THREAD

**Issue by serapolis** [PBH-BTN/PeerBanHelper#334]
### 版本号 - Version

6.0

### 操作系统平台和系统架构 - OS  and CPU Arch

Windows 11, x64

### 部署方式 - Deploy method

Windows 安装程序（通过 .exe 安装） (Windows .EXE Installer)

### 关联的下载器类型 - Downloader Type

仅 qBittorrent（Only qBittorrent）

### 问题描述 - Issue Description

（如题）

### 复现步骤 - Reproduce steps

在x86架构上运行的Win11系统上以安装程序自动部署的桌面快捷方式启动服务端时即可复现。

### 截图/日志文件 - Screenshot / Logs 

![屏幕截图 2024-08-18 224940](https://github.com/user-attachments/assets/9c7e1a43-ec24-4fb1-86b0-b8a909e6741f)

### 额外信息 - Addition Information

该问题是在安装后自第一次运行起即存在的。
经本人尝试，即便Win11对服务端程序进行了兼容模式评估且按照评估后设置的兼容模式运行，此问题仍旧存在。
此外，经本人检查，程序安装的文件夹的路径均为ASCII字符，不存在汉字、假名等字符。
该问题在本人的设备上还没被发现有阻碍Web UI运行的迹象。

### 检查清单 - Check list

- [X] 我确定正在运行 Github Releases 中的最新的正式版本 PeerBanHelper (I'm running the latest version of PBH that can be found in Github Relases)
- [X] 我确定我所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [X] 我确定我所提到的问题，均未在 README 和 WIKI 中有所解答 (This not a question/or the question that not listed in README's FAQ or WIKI)
- [ ] 我确定我没有检查这个检查清单，只是闭眼选中了所有的复选框 (I have not read these checkboxes and therefore I just ticked them all)
- [X] 我确定这不是一个与安全有关的安全漏洞，它可以被安全的公开报告 (This not a security related issue, can be safe report in public)
- [X] 我确定我已知悉，如果我没有正确地填写问题报告表单，则 Issue 可能会被关闭 (I know this issue may closed without any warnings if I didn't fill the form correctly)

**Comment by Ghost-chu** [comment]
您可能是安装了番剧字体包的受害者，请从其它正常设备的系统文件夹中复制微软雅黑字体到您的设备上安装恢复系统原装字体。

**Comment by Ghost-chu** [comment]
https://github.com/PBH-BTN/MSYH-Font

字体已上传到这里，下载三个 ttc 文件右键安装即可。

**Comment by zhongfly** [comment]
题外话：
说起字幕的字体包，从来都不推荐直接安装到系统里，会污染系统字体，容易出现各种问题。
建议使用临时挂载字体的工具，例如FontLoaderSub（ https://bbs.acgrip.com/thread-3848-1-1.html ），或者 SubtitleFontHelper（ https://github.com/Apache553/SubtitleFontHelper ）。我个人推荐后者，可以在播放器使用字幕时自动加载需要的字体，播放完毕后自动卸载，完全无感。

**Comment by serapolis** [comment]
十分感谢您抽时间解释了这个问题出现的原因及解决方法。该问题也已解决，解决途径如下：
1.安装、覆盖上述链接提供的字体；
2.Taskkill掉程序并重启。

> https://github.com/PBH-BTN/MSYH-Font
> 
> 字体已上传到这里，下载三个 ttc 文件右键安装即可。

**Comment by serapolis** [comment]
> 题外话： 说起字幕的字体包，从来都不推荐直接安装到系统里，会污染系统字体，容易出现各种问题。 建议使用临时挂载字体的工具，例如FontLoaderSub（ https://bbs.acgrip.com/thread-3848-1-1.html ），或者 SubtitleFontHelper（ https://github.com/Apache553/SubtitleFontHelper ）。我个人推荐后者，可以在播放器使用字幕时自动加载需要的字体，播放完毕后自动卸载，完全无感。

实际上本来额外安装字体就是多余的。MKV封装似乎是支持直接将TTF之类的字体文件直接封入的。不过感谢您的解答。

**Comment by zhongfly** [comment]
> 实际上本来额外安装字体就是多余的。MKV封装似乎是支持直接将TTF之类的字体文件直接封入的。不过感谢您的解答。

你说的是内封字体，一般也还会做字体子集化，减小体积，目前字幕组这么做的不算多（至少我常看的组里没找到），另外也有mks这种外挂字幕格式也支持内封字体的，但是也更稀少了，甚至有的播放器都不支持。
不过目前实际情况，内封/外挂的字幕一般都还是ass，搭配字体包的……

**Comment by bangFX** [comment]
我遇到了同样的问题
但是我第一次启动GUI正常，修改配置启用 BTN 后再次启动时才出现这个问题

**Comment by Ghost-chu** [comment]
> 我遇到了同样的问题 但是我第一次启动GUI正常，修改配置启用 BTN 后再次启动时才出现这个问题

PBH 有两套 GUI，一套是 Swing，另一套是 JavaFx。你可能是首次启动时因为下载 JavaFx 失败，所以进入了没有问题的 Swing。

下一次重启后如果下载成功，就会切换到 JavaFx，问题就会暴露出来。

**Comment by bangFX** [comment]
> > 我遇到了同样的问题 但是我第一次启动GUI正常，修改配置启用 BTN 后再次启动时才出现这个问题
> 
> PBH 有两套 GUI，一套是 Swing，另一套是 JavaFx。你可能是首次启动时因为下载 JavaFx 失败，所以进入了没有问题的 Swing。
> 
> 下一次重启后如果下载成功，就会切换到 JavaFx，问题就会暴露出来。


确实，第二次启动时印象瞥了下有下载行为
我改用PeerBanHelper-Swing.exe 启动正常
///
已重装字体解决。
