### ISSUE TITLE
[BUG] 打开WebUI按钮不读取配置文件地址

### ISSUE THREAD

**Issue by molehzy** [PBH-BTN/PeerBanHelper#346]
### 版本号 - Version

v6.0.1

### 操作系统平台和系统架构 - OS  and CPU Arch

Windows
x64

### 部署方式 - Deploy method

Windows 绿色懒人包

### 关联的下载器类型 - Downloader Type

qBittorrent-Enhanced-Edition

### 问题描述 - Issue Description

GUI内点击``WebUI-打开WebUI``不读取配置文件设置的地址

### 复现步骤 - Reproduce steps

1.修改``config.yml.server.address``
2.在GUI内点击``WebUI-打开WebUI``

### 截图/日志文件 - Screenshot / Logs 

![image](https://github.com/user-attachments/assets/17b9fd17-c8ff-4bbf-82f7-b1dbab0652ac)

### 检查清单 - Check list

- [X] 我确定正在运行 Github Releases 中的最新的正式版本 PeerBanHelper (I'm running the latest version of PBH that can be found in Github Relases)
- [X] 我确定我所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [X] 我确定我所提到的问题，均未在 README 和 WIKI 中有所解答 (This not a question/or the question that not listed in README's FAQ or WIKI)
- [ ] 我确定我没有检查这个检查清单，只是闭眼选中了所有的复选框 (I have not read these checkboxes and therefore I just ticked them all)
- [ ] 我确定这不是一个与安全有关的安全漏洞，它可以被安全的公开报告 (This not a security related issue, can be safe report in public)
- [X] 我确定我已知悉，如果我没有正确地填写问题报告表单，则 Issue 可能会被关闭 (I know this issue may closed without any warnings if I didn't fill the form correctly)

**Comment by wdw1007** [comment]
你是在这台机器上搭建并且就在这台机器上访问吗
localhost -> 127.0.0.1(ipv4)
如果是这样应该保持`address` 中的 `127.0.0.1` 与 `prefix` 中的 `http://127.0.0.18900`

**Comment by Ghost-chu** [comment]
address指的是网络界面监听地址，除非你知道这是做什么的，否则请勿修改。

**Comment by molehzy** [comment]
> address指的是网络界面监听地址，除非你知道这是做什么的，否则请勿修改。

虽然这个问题对我没有实际上的影响，但为什么监听端口会读取而监听地址不会读取呢？按钮写死localhost的意义是啥？

**Comment by Ghost-chu** [comment]
你都用GUI了肯定是在本机上启动了程序，那按钮自然直接开localhost的就行了。
