### ISSUE TITLE
[BUG] 添加下载器名称时不能包含特殊字符

### ISSUE THREAD

**Issue by kukusyaoran** [PBH-BTN/PeerBanHelper#349]
### 版本号 - Version

v6.0.1

### 操作系统平台和系统架构 - OS  and CPU Arch

debian-x86

### 部署方式 - Deploy method

Docker

### 关联的下载器类型 - Downloader Type

qBittorrent

### 问题描述 - Issue Description

初始化时，添加下载器名称中如果包含"."，点击测试下载器提示“null”

### 复现步骤 - Reproduce steps

1.拉取并并运行 Docker 镜像
2.登录 PBH 初始化界面
3.填写下载器名称，例如“qBittorrent-1.19"，点击测试下载器触发错误提示

### 截图/日志文件 - Screenshot / Logs 

![截屏2024-08-20 21 30 58](https://github.com/user-attachments/assets/22eadf10-7ba4-44b7-b184-e19ad7501fd3)

### 检查清单 - Check list

- [X] 我确定正在运行 Github Releases 中的最新的正式版本 PeerBanHelper (I'm running the latest version of PBH that can be found in Github Relases)
- [X] 我确定我所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [X] 我确定我所提到的问题，均未在 README 和 WIKI 中有所解答 (This not a question/or the question that not listed in README's FAQ or WIKI)
- [X] 我确定我没有检查这个检查清单，只是闭眼选中了所有的复选框 (I have not read these checkboxes and therefore I just ticked them all)
- [X] 我确定这不是一个与安全有关的安全漏洞，它可以被安全的公开报告 (This not a security related issue, can be safe report in public)
- [X] 我确定我已知悉，如果我没有正确地填写问题报告表单，则 Issue 可能会被关闭 (I know this issue may closed without any warnings if I didn't fill the form correctly)

**Comment by Ghost-chu** [comment]
请避免使用 `.`，它是配置文件章节分隔符。

**Comment by kukusyaoran** [comment]
> 请避免使用 `.`，它是配置文件章节分隔符。

发现后面再尝试添加新的下载器，比如直接输入 `1.19` 会触发语法检查错误提示，只是在初始化步骤的时候没有提供这个名称检查提示
