### ISSUE TITLE
[BUG] 统计→图表→位置与运营商 不显示数据

### ISSUE THREAD

**Issue by Rbqwow** [PBH-BTN/PeerBanHelper#356]
### 版本号 - Version

Backend Version 6.0.1 (755770ec)
WebUI Version 2.2.0 (ac4d438e)

### 操作系统平台和系统架构 - OS  and CPU Arch

Windows 11 23H2 x64

### 部署方式 - Deploy method

Windows 绿色懒人包

### 关联的下载器类型 - Downloader Type

qBittorrent Enhanced Edition v4.6.5.10

### 问题描述 - Issue Description

已配置 GeoIP 库，但图表不显示数据
尝试过在更多选项里面切换项目

### 复现步骤 - Reproduce steps

输完 Plus 密钥就一直这样(

### 截图/日志文件 - Screenshot / Logs 

![image](https://github.com/user-attachments/assets/748ce647-2098-4f3d-b1c2-03ed9da67c43)
![image](https://github.com/user-attachments/assets/44e07885-1c56-4049-a092-2344bdc760b5)

### 额外信息 - Addition Information

Release 里面说的 [配置 GeoIP 库](https://github.com/PBH-BTN/PeerBanHelper/wiki/%E7%94%B3%E8%AF%B7-Maxmind-GeoLite2-%E8%AE%B8%E5%8F%AF%E8%AF%81) 的 Wiki 链接失效
是漏写了什么吗...?

### 检查清单 - Check list

- [X] 我确定正在运行 Github Releases 中的最新的正式版本 PeerBanHelper (I'm running the latest version of PBH that can be found in Github Relases)
- [X] 我确定我所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [X] 我确定我所提到的问题，均未在 README 和 WIKI 中有所解答 (This not a question/or the question that not listed in README's FAQ or WIKI)
- [ ] 我确定我没有检查这个检查清单，只是闭眼选中了所有的复选框 (I have not read these checkboxes and therefore I just ticked them all)
- [X] 我确定这不是一个与安全有关的安全漏洞，它可以被安全的公开报告 (This not a security related issue, can be safe report in public)
- [X] 我确定我已知悉，如果我没有正确地填写问题报告表单，则 Issue 可能会被关闭 (I know this issue may closed without any warnings if I didn't fill the form correctly)

**Comment by Ghost-chu** [comment]
请关闭浏览器上安装的广告拦截扩展
