### ISSUE TITLE
可以增加一个显示BTN状态部分吗

### ISSUE THREAD

**Issue by Kaffu-Chino** [PBH-BTN/PeerBanHelper#359]
RT，比如（禁用/连接失败/正常...)

**Comment by Ghost-chu** [comment]
BTN 实际上并非长连接，偶尔的连接失败也不会影响 BTN 的数据提交。实际上这个状态显示意义并不大。

> BTN-Spec 设计时考虑到中心化服务器容易遭到攻击或者数据泄露等情况，因此它被设计为可以在极低服务质量保证的情况下为大量用户提供服务。

> 不使用任何长连接
> 提交/获取数据时，不影响缓存数据
> 抛去需要动态环境的功能，其其余的规则分发等功能，应当可以在完全静态环境中部署（如：Github Pages），提高抗故障能力
> 最后，本规范设计时着重考虑了带宽消耗，避免服务器在任何非必要的情况下向客户端传输额外数据

**Comment by poplar-at-twilight** [comment]
其实可以从 `latest.log` 文件中读取最后一条动态，按关键字过滤，把 BTN 网络最新一次链接的结果显示到 webui 中。

例如，读取到

```
[17:37:57] [pool-8-thread-2/INFO]: [BTN 网络] 计划任务正在向 BTN 网络提交自上次汇报以来新增的封禁条目，请稍等……
[17:37:59] [/INFO]: [BTN 网络] 已向 BTN 网络提交 2 个封禁记录，感谢您对 BTN 网络的支持！
[17:38:02] [Ban Wave/INFO]: 已检查 1 个下载器的 2 个活跃 Torrent 与 6 个 Peers。共封禁 0 个 Peers，并解除 0 个过期的封禁 (7ms)
[17:38:05] [pool-8-thread-1/INFO]: [BTN 网络] 计划任务正在向 BTN 网络提交目前下载的 Peers 列表，请稍等……
[17:38:05] [/INFO]: [BTN 网络] 已向 BTN 网络提交 6 个 Peers，感谢您对 BTN 网络的支持！
[17:38:06] [/INFO]: [BTN 网络] 规则数据更新成功，当前数据版本：db26b3f4
```

则在 WebUI 的当前页面中，显示为

|项目|状态|时间|
|:---:|:---:|:---:|
|连通性|OK|17:37:59|
|汇报封禁记录量|2|17:37:59|
|汇报 Peer 封禁量|6|17:38:05|
|在线 Peer 列表|OK|17:38:05|
|当前数据版本|db26b3f4|17:38:06|

----

鉴于 BTN 网络的特点，在同步和汇报事务完成后，可以简单地向 webui 传递一个状态值

|状态|时间|
|:---:|:---:|
|工作正常|17:38:06|

**Comment by Gaojianli** [comment]
> 其实可以从 `latest.log` 文件中读取最后一条动态，按关键字过滤，把 BTN 网络最新一次链接的结果显示到 webui 中。
> 
> 例如，当读取到
> 
> ```
> [17:37:57] [pool-8-thread-2/INFO]: [BTN 网络] 计划任务正在向 BTN 网络提交自上次汇报以来新增的封禁条目，请稍等……
> [17:37:59] [/INFO]: [BTN 网络] 已向 BTN 网络提交 2 个封禁记录，感谢您对 BTN 网络的支持！
> [17:38:02] [Ban Wave/INFO]: 已检查 1 个下载器的 2 个活跃 Torrent 与 6 个 Peers。共封禁 0 个 Peers，并解除 0 个过期的封禁 (7ms)
> [17:38:05] [pool-8-thread-1/INFO]: [BTN 网络] 计划任务正在向 BTN 网络提交目前下载的 Peers 列表，请稍等……
> [17:38:05] [/INFO]: [BTN 网络] 已向 BTN 网络提交 6 个 Peers，感谢您对 BTN 网络的支持！
> [17:38:06] [/INFO]: [BTN 网络] 规则数据更新成功，当前数据版本：db26b3f4
> ```
> 
> 则在 WebUI 的当前页面中，显示为
> 
> 项目	状态	时间
> 汇报封禁记录量	2	17:37:59
> 汇报 Peer 封禁量	6	17:38:05
> 当前数据版本	db26b3f4	17:38:06
> 连通性	OK	17:38:06
> 或者，在同步和汇报事务完成后，可以简单地向 webui 传递一个状态值
> 
> BTN 状态	时间
> 工作正常	17:38:06
> 不正常的话，让用户查看具体的日志文件就行了
> 
> BTN 状态	时间
> 工作异常，请检查日志	17:38:06

不能从日志里面去读，太奇怪

**Comment by poplar-at-twilight** [comment]
> 不能从日志里面去读，太奇怪

重点并不是从何处读取，而是将最后一次传输的结果反馈到 webUI 中。BTN 本身并不是实时链接的，所以在 webUI 中显示的状态应当是它最后一次活跃时的状态。

**Comment by paulzzh** [comment]
a8dea0f
是不是可以做了？

**Comment by Ghost-chu** [comment]
![image](https://github.com/user-attachments/assets/a72095ea-96c9-4748-8dba-09b20abcc339)

我也觉得可以做了

**Comment by Ghost-chu** [comment]
已在 v7 版本中添加
