### ISSUE TITLE
进度作弊请求添加更多控制项

### ISSUE THREAD

**Issue by HebronG** [PBH-BTN/PeerBanHelper#378]
希望能添加根据文件大小采用不同的阈值的控制，不到1G的小文件回报进度同步会有误差，但放宽阈值那么超过50G的大文件很容易再封禁前就产生了巨量上传
同时也希望能添加根据当前进度采用不同阈值的控制，尤其是针对进度0%的希望能缩紧阈值

**Comment by c31io** [comment]
当前规则基于百分比封禁客户端，预期的封禁前吸血量为，`kx`，`x`为文件总体积，`k`为比例系数

观察到大文件吸血占用带宽较大，封禁不及时，故建议降低大文件容忍度，使预期吸血量存在上限`0.01x+C`，其中`C`为常量

例如，令`k=min(k0, 0.01+C/x)`，其中`k0`为小文件比例系数

同理，针对进度后退也可使用类似规则

***观察到的吸血来源：61.160.241.****

**Comment by paulzzh** [comment]
在引入 #414 和 #459 后有没有改善？

**Comment by HebronG** [comment]
> 在引入 #414 和 #459 后有没有改善？

目前使用下来感觉新版有改善
