### ISSUE TITLE
废弃对 Transmission 下载器的支持

### ISSUE THREAD

**Issue by Ghost-chu** [PBH-BTN/PeerBanHelper#382]
在较新版本的 PeerBanHelper 中，我们废弃了对 Transmission 下载器的支持，受影响的用户的 WebUI 的下载器状态将显示 “需要采取行动”，主要原因如下：

* 由于 API 的限制，PeerBanHelper 在 Transmission 上工作不佳，缺失重要数据（Peer 流量统计、PeerID），导致启发式识别/PeerId 规则封禁的效果很差
* 同样是出于 API 的限制，在 Transmission 上封禁 IP 地址时必须对种子进行 *暂停-重启* 的操作，并导致了如下诸多问题：
  * 在封禁事件频繁的 Torrent 上，PBH 会频繁的重启种子以掐断 Peer 的连接。但每一次重启都伴随着 Transmission 对所有 Tracker 服务器的更新请求。**这间接的导致了对 Tracker 服务器的 CC 攻击，且此类更新无视了 Tracker 服务器要求的最小宣告间隔**，加大了 Tracker 服务器的压力，并可能导致 IP 地址被 Tracker 服务器封禁。我们认为这不利于 BT 环境的发展，并可能导致 Tracker 服务器需要承受额外的压力、流量和带宽。
  如果我们放任不管，未来 PeerBanHelper 用户量达到一定规模时，将对 Tracker 产生显著的负面影响，并最终需要 Tracker 服务器的运营和维护者付出额外的时间、精力和金钱
  * 在快速启停时，Transmission 有概率直接崩溃，只能通过延迟执行 RPC 来规避，但这影响的 PeerBanHelper 的运行性能，并引入大量复杂的延迟逻辑，并时常出现奇怪的问题（种子一旦被暂停，就可能再也不会被重启等）
  * Transmission 的客户端字段会时常随机显示下面三种的任意一种：
    * (1) 客户端名称
    * (2) PeerID
    * (3) 通过 PeerID 猜测的客户端名称
  * 由于 PBH 根本无法判断 TR 会显示哪一种，这导致适配一直以来都很困难繁琐

我们即将采取的行动：

* PeerBanHelper 将在 WebUI 中置灰禁用/隐藏 Transmission 下载器的添加向导，避免新的用户继续添加 Transmission 下载器
  * 为了避免造成破坏性影响，已经存在的 Transmission 下载器设置将保持现状，在近期的版本中不会被强制删除。
* 在已经存在的 Transmission 下载器状态卡片上，常驻显示 “需要采取行动” 提示信息，提醒用户择期进行下载器迁移。未来在 Transmission 做出更多改变之前，PBH 不再对 TR 适配器做出改进。并可能在未来的版本中将其移除。

---

尽管很多用户都钟爱 Transmission（特别是较低的资源占用，可以轻松为大量种子做种；干净的 GUI 界面；稳定易用等），但由于上述几点（特别是对 Tracker 造成的额外压力），我们仍然需要开始推动 Transmission 的废弃进程。

以下是一些我们推荐的下载器：

* BiglyBT - BiglyBT 是一个使用 Java 编写的 BT 客户端，是 Vuze(Azureus) 的分支。其官方的 WebUI 插件（`BiglyBT-plugin-xmwebui`）提供了完美兼容 Transmission 的 WebUI 和 WebAPI。而且它的插件可以提供诸多高级功能（时段限制、分享率控制、Javascript 脚本、Tor/I2P 支持、自动分类、根据分享率删除文件等等）。GUI 上数据显示非常齐全。
得益于其插件机制，PBH 为其编写的扩展插件可以脱离极其受限的 Transmission WebAPI 的环境，获取最直接最完整的数据。而且如果你在用其它一些使用 Transmission WebAPI 的辅助工具的话，这可以节约大量的时间。
* qBittorrent - 老生常谈的 BT 软件，也是 PBH 最先支持的 BT 下载器；尽管有些大大小小的各种奇怪小毛病，但只要不遇到内存泄漏问题（只有少部分人会出现此问题），都无伤大雅，稳定可靠。
* Deluge - 一个使用 Python 编写的 BT 软件，通常被 PT 和 Seedbox 使用。优点是给所有用户的上传都十分平衡，可以同时给尽可能多的人上传数据。缺点是有点慢、IPV6 支持较差，以及 WebUI 上无法正常安装 PBH 的扩展插件。

---

要从 Transmission 迁移，不管目的下载器是什么，过程都大同小异：

* 从 Transmission 的 `Torrents` 文件夹导出所有 `.torrent` 文件
* 换到你的新的下载器，批量导入所有 torrent，设置好原来文件的存储位置
* 校验一下

---

对此决定所可能造成的不便表示抱歉，还请您理解。

**Comment by CXwudi** [comment]
关于qb内存泄漏问题，使用采用了1.2版的libtorrent的qb就可以了，不要使用2.0版的libtorrent

**Comment by mzhboy** [comment]
1.2 libtorrent 的可以下载静态链接版 [qbittorrent-nox-static](https://github.com/userdocs/qbittorrent-nox-static)
webui 一样好用

**Comment by i990049** [comment]
既然废掉一个，就拿别的补充，我建议增加对跨平台软件frostwire的支持

**Comment by pooneyy** [comment]
> 关于qb内存泄漏问题，使用采用了1.2版的libtorrent的qb就可以了，不要使用2.0版的libtorrent
> 
> 使用docker的话建议使用[linuxserver版的镜像](https://hub.docker.com/r/linuxserver/qbittorrent), 可以使用`libtorrentv1`的tag

带`libtorrentv1`的tag有好多。

- linuxserver/qbittorrent:5.0.4-libtorrentv1
- inuxserver/qbittorrent:libtorrentv1-version-release-5.0.4_v1.2.20
- linuxserver/qbittorrent:libtorrentv1-release-5.0.4_v1.2.20-ls70
- linuxserver/qbittorrent:libtorrentv1
以上都分别有什么区别呀？您推荐用哪个比较好呀？
