### ISSUE TITLE
[Feature] 增加整体分享率控制

### ISSUE THREAD

**Issue by Gaojianli** [PBH-BTN/PeerBanHelper#386]
由于 PBH 规则更新具有滞后性，在规则更新前出现的0day恶意客户端可能直接吸到运营商上门(5000G/月），因此希望增加全局分享率控制功能，当分享率/上传量触发告警后，暂停/限速所有种子，发送警告等待用户人工确认

**Comment by Fvpder** [comment]
移动被吸的彻底破防开始无视满意率了，800g就直接关停ipv6+nat4，投诉只会装死说设备更新，只能投诉到工信部以后无条件拆机了。建议移动用户限制一下上传速度，别被直接恰网线了

**Comment by SteveYu000** [comment]
> 由于 PBH 规则更新具有滞后性，在规则更新前出现的0day恶意客户端可能直接吸到运营商上门(5000G/月），因此希望增加全局分享率控制功能，当分享率/上传量触发告警后，暂停/限速所有种子，发送警告等待用户人工确认

分享率的话可以直接在bt客户端里设置吧。整体分享率意义不大，更直接的应该是上传流量限制，比如30天内最多上传多少数据。另外如果要增加分享率控制的话可以是针对每个种子单独设置，这是客户端没有的功能

**Comment by mzhboy** [comment]
QB可以直接设置一个默认的分享倍率，到达后停止做种。

**Comment by Ghost-chu** [comment]
> > 由于 PBH 规则更新具有滞后性，在规则更新前出现的0day恶意客户端可能直接吸到运营商上门(5000G/月），因此希望增加全局分享率控制功能，当分享率/上传量触发告警后，暂停/限速所有种子，发送警告等待用户人工确认
> 
> 分享率的话可以直接在bt客户端里设置吧。整体分享率意义不大，更直接的应该是上传流量限制，比如30天内最多上传多少数据。另外如果要增加分享率控制的话可以是针对每个种子单独设置，这是客户端没有的功能

单个种子也有单独的限速和分享率设置的，可以仔细看看菜单

**Comment by Ghost-chu** [comment]
发送警告做好了
