### ISSUE TITLE
建立独立的 peer-agent / peer-id / 恶意 IP 库

### ISSUE THREAD

**Issue by Rirmach** [PBH-BTN/PeerBanHelper#39]
主要使用 aria2 作为 BT 客户端，但本项目仅适配了 qB 所以无法使用。因此是否可以建立一个类似于 [v2fly/domain-list-community](https://github.com/v2fly/domain-list-community) 独立的黑名单库，由所有用户共建并完善？

**Comment by Ghost-chu** [comment]
我们目前没有 IP 黑名单库，使用的是基于特征检测的动态屏蔽。后续如果有 BTN 做出来的话，会开放接口拉取 IP 黑名单。

Aria2 有接入计划，但我没用过 Aria2，也不熟悉 Aria2 的 RPC，等待贡献者发个 PR。

**Comment by Rirmach** [comment]
其实我自己做了套适配 aria2 的反吸血程序，但因为开发语言不同（Golang）、很多功能需要同其它自己开发的微服务网络协同工作，所以也没法提PR

因为本人对 BT 圈了解不多，很难有精力去捕捉类似 trafficConsume 这样散落在各处的恶性事件（也是因为闹得大才看到的），所以还是希望能共建类似于 trackerlist 这样的东西，方便我们这些其它客户端的用户自己动手丰衣足食

**Comment by Ghost-chu** [comment]
只有 IP 库有意义，现在已经出现伪装BitComet和Transmission的恶意客户端了。

**Comment by laocuiGitHub** [comment]
做用户之间共享IP库是一个可行的办法，现在网络害虫越来越狡猾了，不过需要IP库封禁优先级要低于动态规则库，只用作于特征特别明显的IP进行封禁，避免大面积误封。

**Comment by Ghost-chu** [comment]
https://github.com/PBH-BTN/BTN-Collected-Rules
