### ISSUE TITLE
[Feature] 跳过私有种子

### ISSUE THREAD

**Issue by ixff** [PBH-BTN/PeerBanHelper#399]
跟 Issues #22 一样的需求。

出于省事的目的，我是BT/PT混用一个下载器的（目前还没发现有什么不合适的情况）。
但在使用PBH后，不时出现PT种子的PEER被PBH干掉/误伤的情形，比如下载进度、IP黑名单。
希望能提供这样一个开关，跳过私有种子，“PT的反吸血由Tracker控制，无需PBH干涉”。

qbittorrent 5.0 版本新增了一个webapi https://github.com/qbittorrent/qBittorrent/pull/20686 ，获取私有种子应该不会有 #22 中提及的负载性能问题了。

**Comment by Gaojianli** [comment]
需要根据下载器版本做功能开关了，这部分要考虑下 @Ghost-chu
