### ISSUE TITLE
关于近期大量出现的吸血 IP 警示 (2024/09/08)

### ISSUE THREAD

**Issue by Ghost-chu** [PBH-BTN/PeerBanHelper#438]
BTN 网络近期观测到部分地域出现爆发式恶意 IP 新增的情况（部分地域甚至超过 160,000 次封禁），PBH-BTN 建议您充分使用 PBH 提供的地域封禁功能，封禁以下高危地域：

```
海南省 海口市 （注：除了计数器高达 82,627 次外，只算 IP 地址也高达 10,192 个，位居第一。大部分为海口电信。）
浙江省 台州市 玉环市
浙江省 绍兴市
福建省 泉州市
福建省 福州市
福建省 宁德市
福建省 莆田市
安徽省 马鞍山市
广东省 广州市 番禺区
云南省 昭通市
陕西省 西安市
四川省 广安市 邻水县
江苏省 常州市
江苏省 南通市
江苏省 常州市
江苏省 泰州市 兴化市
云南省 昭通市
```

对于其它最近 14 天累计封禁量小于 15,000 条的地域，我们暂时不在此进行推荐封禁。  
本列表中仅列出 IP 滥用严重的城市，对于任何非必要的城市，本列表暂不列出。

## 在 PBH 中将地域添加到封禁列表

<img width="918" alt="Snipaste_2024-09-08_02-08-21" src="https://github.com/user-attachments/assets/4a6f9e4e-e899-4532-9c57-8d49c0a03847">

（请先确保 IPDB 正常工作，即在封禁列表页面，有正常显示国内的中文城市名称信息）

![image](https://github.com/user-attachments/assets/60b713e0-e159-49df-b39a-6b1d4dc88d2f)

## 封禁 Rank（仅截取排名较靠前的地区）

|cityname                       |bancount|
|-------------------------------|--------|
|"陕西省 西安市"                      |163605  |
|"海南省 海口市"                      |80897   |
|"Tultitlán de Mariano Escobedo"|67507   |
|"四川省 广安市 邻水县"                  |50179   |
|"安徽省 马鞍山市"                     |45253   |
|"福建省 泉州市"                      |26813   |
|"江苏省 常州市"                      |25274   |
|"江苏省 南通市"                      |23792   |
|"浙江省 绍兴市"                      |22780   |
|"浙江省 台州市 玉环市"                  |15087   |
|"云南省 昭通市 彝良县"                  |14681   |
|"海南省 海口市 琼山区"                  |14548   |
|"江苏省 泰州市 兴化市"                  |13253   |
|"云南省 昭通市"                      |12782   |
|"安徽省 马鞍山市 含山县"                 |12671   |
|"海南省 海口市 美兰区"                  |12360   |
|"福建省 福州市"                      |11856   |
|"福建省 宁德市 古田县"                  |11766   |
|"黑龙江省 哈尔滨市"                    |11401   |
|"河北省 保定市"                      |10192   |

**Comment by SeaHOH** [comment]
功能挺好，但是不应向推荐大家配置，毕竟现在用户应该挺多了吧。为了区区几万十几万 ( 注意，这不是节点数量 ) ban 连坐上百万潜在节点，个人这么做无可厚非，但大家都根据推荐成规模地这样干就很有问题了。

**Comment by Ghost-chu** [comment]
> 功能挺好，但是不应向推荐大家配置，毕竟现在用户应该挺多了吧。为了区区几万十几万 ( 注意，这不是节点数量 ) ban 连坐上百万潜在节点，个人这么做无可厚非，但大家都根据推荐成规模地这样干就很有问题了。

三个/16封过去和封省网没区别了。之所以没有塞进规则里已经在出于减小影响的目的了。  
如果不是地域性滥用严重，每天都能变出一大把新段，谁愿意开地图炮？

**Comment by Ghost-chu** [comment]
目前列表已经在很保守的范围下了，对于仅仅是特定区县在刷的已经精确到了区县。且这仅仅是最近 20 天的数据。  
这些地区都有大量连续 IP 段，且每隔 1-3 天就会出现一大段新的 IP。在除了和运营商内鬼直接沟通的情况外，没有任何情况（哪怕是机房和数据中心），也不会频繁出现大量 IP 地址变动。  

跨省结算的时代，已经不是使用刷下行来拉平上行。上传要给下载的结算方式已经注定了 “刷下载” 也是一种赚钱的手段。Gopeed dev 证明了这种行为的可行性，最近数天也有越来越多其它地市入场。就连 PCDN 也提供了可刷下行的宣传口号。

如果相对应地区的 ISP 放任不管，更有甚者直接参与到利益链条的瓜分之中，那么被封禁属实活该。

**Comment by Ghost-chu** [comment]
说真的，这些地市的普通 BT 用户根本没你想得多（“数百万潜在节点”）。通过快照数据和封禁数据对比，这些地域的吸血 IP 和正常 IP 比例几乎都在 5000:1 (该数字显然被严重低估) 的级别上（对于海南省海口市，这一比例已经超过 70000:1）。  

对于未被滥用的其它地市，数据显然正常的多。

就算你封禁了这些潜在节点，也不会影响这些区域的用户下载热门资源。（他们可以从未使用 PBH/未手动添加区域封禁/海外用户/分流组那里获取资源），他们也能用 socks5 等代理工具更改到不受影响的区域，或者使用 I2P 下载。

**Comment by SeaHOH** [comment]
我的意思是，大家都这么封对相应区域的正常用户造成负面影响更大，肉眼可见的就是完成下载需要更长时间，分发更慢。

至于“百万潜在节点”之言，是指这些被连坐的 IP 可能会有正常节点使用到它们，而不是指实际有上百万的活动节点。普通客户端正常使用时，连接的节点只是整个网络的一小部分 (小众、冷门的资源除外)，不同圈子的用户可能一个月也相互连不上一次，整个 BT 网络远比你想象的要大得多，这种大规模封禁对相应地域造成的影响绝对不可忽视。

这个功能可以用，但不要大家都照着某个配置来，真的。我们反吸血的目的是把 BT 撑住，不让它死掉，如果越做越小的话，死得会更快。

**Comment by Ghost-chu** [comment]
> 我的意思是，大家都这么封对相应区域的正常用户造成负面影响更大，肉眼可见的就是完成下载需要更长时间，分发更慢。
> 
> 至于“百万潜在节点”之言，是指这些被连坐的 IP 可能会有正常节点使用到它们，而不是指实际有上百万的活动节点。普通客户端正常使用时，连接的节点只是整个网络的一小部分 (小众、冷门的资源除外)，不同圈子的用户可能一个月也相互连不上一次，整个 BT 网络远比你想象的要大得多，这种大规模封禁对相应地域造成的影响绝对不可忽视。
> 
> 这个功能可以用，但不要大家都照着某个配置来，真的。我们反吸血的目的是把 BT 撑住，不让它死掉，如果越做越小的话，死得会更快。

错误的，阻止严重滥用地区还能让愿意做种的人继续做种下去，你所说的放任不管才是加速 BT 死亡。  
对于更多人来说，如果自己的宽带被疯狂拉爆，那不如直接关软件。至于你说的越做越小，从有人提出封禁中国大陆IP开始，就已经死了一半了。  

对重点地区的屏蔽也是维护做种人的信心的重要手段。如果你愿意给这些地区流量，那完全可以不添加这些规则。

**Comment by poplar-at-twilight** [comment]
> BTN 网络近期观测到部分地域出现爆发式恶意 IP 新增的情况（部分地域甚至超过 160,000 次封禁），PBH-BTN 建议您充分使用 PBH 提供的地域封禁功能，封禁以下高危地域：

个人建议，如果有计划定期公布大规模滥用/攻击 BT 网络的地区黑名单，可以在 [https://github.com/PBH-BTN/BTN-Collected-Rules PBH-BTN/BTN-Collected-Rules] 新增一个订阅链接，定期滚动更新建议批量加入黑名单的地区，并给予更长的解禁时间。

**Comment by SeaHOH** [comment]
> PBH 所造成的影响远没你想象的大

要有信心啊！用发展的眼光来思考和看待问题，也许你会有更好的想法。
个人看法：PBH-PTN 相关计划前途远大，对维护 BT 网络发展会起到越来越多的积极作用，将来用户普及率肯定会非常高，到时很多老外都会订阅 BTN-Collected-Rules 也说不定。

**Comment by DrJason33564** [comment]
今天在下载来自next.itelllyou.cn的系统镜像时遭遇了大量Rain客户端的连接，这些客户端大多或多或少报告了些进度，且会有上传，但是没有一个做种端，而且量实在是太大，所以我还是决定让PBH全部封了（之前把Rain的规则注释掉了）
不清楚这次说的时间是否有异常Rain客户端？

**Comment by SteveYu000** [comment]
提个建议，能不能批量添加地区？一行行的输太慢了。自动识别换行，每行为一条新规则，这样方便得多。另外，可以加个输入联想，先匹配省，然后根据省匹配市，以此类推，就类似于通常见到的地区选择栏一样

**Comment by starobots** [comment]
一直用的外国pt和bt站，是不是可以直接加一个ban国内所有ip的ipfilter就没这么多问题了。

**Comment by sommio** [comment]
Tultitlan de Mariano Escobedo 的 IP 范围是哪些？所属于哪些 ASN？
这个墨西哥城市看着诡异

**Comment by starobots** [comment]
请问，使用这个模块之后，是配合普通版的qbt就可以还是需要qbt ee版？
qbt有libtorrent 1.2，qbt ee版好像都是2.0的，有爆内存的问题。

**Comment by zhongfly** [comment]
> 请问，使用这个模块之后，是配合普通版的qbt就可以，还是需要qbt ee版？ qbt有libtorrent 1.2，qbt ee版好像都是2.0的，有爆内存的问题。

和下载器不相关…只要是软件支持的下载器都行

**Comment by FrzMtrsprt** [comment]
> 请问，使用这个模块之后，是配合普通版的qbt就可以，还是需要qbt ee版？ qbt有libtorrent 1.2，qbt ee版好像都是2.0的，有爆内存的问题。

不知道你指的是哪个平台，但qbt ee windows端的libtorrent应该是1.2的。PBH 6.1加入了对qbt ee的shadowban api的支持，而原版qbt是没有这个功能的。

**Comment by starobots** [comment]
现在这些吸血IP，直接把老外放出来不管新的旧的磁力链接都拿来吸。几年前的最新的电影动画都有。
之前rarbg放出来全站数据库磁力链接，那几个黑洞吸血基本全都有。

**Comment by i990049** [comment]
> 功能挺好，但是不应向推荐大家配置，毕竟现在用户应该挺多了吧。为了区区几万十几万 ( 注意，这不是节点数量 ) ban 连坐上百万潜在节点，个人这么做无可厚非，但大家都根据推荐成规模地这样干就很有问题了。

被连坐了就换别的分享方式，比如网盘和fopnu

**Comment by 6qs2w9oxhina** [comment]
今天看了一下黑名单多了240e:314::/32段，之前加了112.66.0.0/15段
(我的三个服务器都是112.66.176.0/20段和240e:314:axxx::/48段的，
连接到我这的大多都是124.225.*.*的IPv4，在我的封禁列表里跟112.66.0.0/15段有关的，
只能看到我的服务器上开的qb客户端互相封禁。)。
我认为IPv4刷流行为确实有点猖狂吧，但我还有IPv6还可以连接。
但加这个/32是真的把海口市龙华区的大部分正常用户全部拉黑了(公网/NAT的IPv6基本用的都是240e:314::/32段)。
个人认为十分不妥。

**Comment by Ghost-chu** [comment]
> 今天看了一下黑名单多了240e:314::/32段，之前加了112.66.0.0/15段 (我的三个服务器都是112.66.176.0/20段和240e:314:axxx::/48段的， 连接到我这的大多都是124.225.*.*的IPv4，在我的封禁列表里跟112.66.0.0/15段有关的， 只能看到我的服务器上开的qb客户端互相封禁。)。 我认为IPv4刷流行为确实有点猖狂吧，但我还有IPv6还可以连接。 但加这个/32是真的把海口市龙华区的大部分正常用户全部拉黑了(公网/NAT的IPv6基本用的都是240e:314::/32段)。 个人认为十分不妥。

https://github.com/PBH-BTN/BTN-Collected-Rules/issues/24

**Comment by SeaHOH** [comment]
```
multi-dial
random-peerid
overdownload-ips
```
我用了这几个列表，昨天看公告居然海南全封，于是自己再过了一道`multi-dial`。
把`xxx.xxx.0.0/1[5678]`和`*::/32`移除，`xxx.xxx.xxx.0/1[5678]`换成`xxx.xxx.xxx.0/22`。
到目前为止，因为还没开始下新种，暂时没见到公告中的吸血 peer，再观察几天看情况。

**Comment by chengnan049** [comment]
> 几年前的最新的电影动画都有

还真是，前几天下了一个十几年前的演唱会都有人吸

<img width="1606" height="111" alt="Image" src="https://github.com/user-attachments/assets/f06b7d1c-f9cf-4d5c-ac27-0149875cc9d3" />
