### ISSUE TITLE
添加qbittorrent-enhanced-nox_x86_64-linux-musl_static，无法添加

### ISSUE THREAD

**Issue by soulmatelh** [PBH-BTN/PeerBanHelper#444]
添加qbittorrent-enhanced-nox_x86_64-linux-musl_static（v4.6.6），无法添加，
![屏幕截图 2024-09-08 225752](https://github.com/user-attachments/assets/e7d1db61-fc1b-4bab-a6b8-1ace25147f6f)
PeerBanHelper版本v6.1.2
![屏幕截图 2024-09-08 225936](https://github.com/user-attachments/assets/0def9860-cc47-44a8-b9bf-125b19947404)

**Comment by Ghost-chu** [comment]
未使用问题模板且未提供足够信息，关闭
