### ISSUE TITLE
无法下载GeoIP数据库

### ISSUE THREAD

**Issue by SteveYu000** [PBH-BTN/PeerBanHelper#446]
下载数据库 GeoLite2-City 时出现错误：java.net.ConnectException
应该是网络问题，有办法自己手动下载吗？

**Comment by Ghost-chu** [comment]
自己下载后也是过一段时间就会过期，要求你更新。

建议挂个代理。https://pbh-btn.github.io/pbh-docs/docs/network/proxy-server

**Comment by CreeperAWA** [comment]
可以考虑增加一个镜像站吗？CF-Worker都能强上不少，或者允许自己配置镜像站地址

**Comment by SteveYu000** [comment]
代理地址是什么？我是用的clash，用本机地址吗？

**Comment by SteveYu000** [comment]
解决了
