### ISSUE TITLE
关于增加多平台支持

### ISSUE THREAD

**Issue by stan0577** [PBH-BTN/PeerBanHelper#466]
是否有适配macOS和Linux的意愿？

**Comment by Gaojianli** [comment]
[why don't you use docker?](https://docs.docker.com/desktop/install/mac-install/)

**Comment by Ghost-chu** [comment]
6.2.4 中已添加：
* Linux 桌面发行版通用安装程序 (.sh) (x64)
* Debian 程序包 (.deb) (x64)
* RedHat 程序包 (.rpm) (x64)
* macOS 程序包 (.dmg) (Intel/ARM)
* 群晖 DSM 套件（基于 Docker）(.spk) (x64/ARM)
