### ISSUE TITLE
[WebUI] 

### ISSUE THREAD

**Issue by CloudyEagle** [PBH-BTN/PeerBanHelper#470]
### WebUI 版本号 - Version

2.2.2

### 问题描述 - Issue Description

WebUI无法登录

### 复现步骤 - Reproduce steps

我原先安装的较旧版本6.0.4，使用6.2.1安装文件升级后无法登录，直接使用C:\Users\XXX\AppData\Local\PeerBanHelper\config路径下的config.yml文件里的token值也无法登录，我清空token重启也还是无法进入引导界面，也没有进入引导界面；我用BCUninstaller卸载重装后才进入引导，尽管没有用程序自带的卸载程序，请问我这个是什么情况。

### 截图 - Screenshot  

![image](https://github.com/user-attachments/assets/3ded84f0-e55c-4efc-8d4a-9c62c0caaff6)

### 检查清单 - Check list

- [X] PeerBanHelper 已更新到最新版本 (I'm running the latest version of PBH that can be found in Github Relases)
- [X] 我已检查过 [PBH 文档](https://pbh-btn.github.io/pbh-docs/)（特别是常见问题），且即使使用了搜索也没有找到与此有关的内容 (This not a question/or the question that not listed in README's FAQ or [PBH WIKI](https://pbh-btn.github.io/pbh-docs/))
- [ ] 我没有检查这个检查清单，只是闭眼选中了所有的复选框，请关闭这个 Issue (I have not read these checkboxes and therefore I just ticked them all, Please close this issue)

**Comment by CloudyEagle** [comment]
在开始菜单里登录的安装你的方法是可以的，但是服务模式中用新生成的token还是无法登录，请问是什么情况？

**Comment by Ghost-chu** [comment]
**除非你知道你在做什么，否则不要安装为系统服务**

系统服务的数据存储目录在系统文件夹，不在 AppData。
