### ISSUE TITLE
[WebUI]在线规则 [错误] 未找到IP黑名单订阅规则: jsdelivr

### ISSUE THREAD

**Issue by Unihis** [PBH-BTN/PeerBanHelper#506]
### WebUI 版本号 - Version

	 2.2.3 

### 问题描述 - Issue Description

订阅了在线规则jsdelivr，更新后无法编辑，无法删除，无法关闭

### 复现步骤 - Reproduce steps

更新6.2.7版本后

### 截图 - Screenshot  

![1](https://github.com/user-attachments/assets/85ec04d8-5761-4dcb-9eb0-2ee19e2d08a1)

https://github.com/user-attachments/assets/e5fda727-6a9d-42be-b152-ba1ac8da54b2

### 额外信息 - Addition Information

开机启动后会暴增封禁peer，但并未实际封禁。连续两天都会发生此现象

### 检查清单 - Check list

- [X] PeerBanHelper 已更新到最新版本 (I'm running the latest version of PBH that can be found in Github Relases)
- [ ] 我已检查过 [PBH 文档](https://pbh-btn.github.io/pbh-docs/)（特别是常见问题），且即使使用了搜索也没有找到与此有关的内容 (This not a question/or the question that not listed in README's FAQ or [PBH WIKI](https://pbh-btn.github.io/pbh-docs/))
- [ ] 我没有检查这个检查清单，只是闭眼选中了所有的复选框，请关闭这个 Issue (I have not read these checkboxes and therefore I just ticked them all, Please close this issue)

**Comment by Ghost-chu** [comment]
> 开机启动后会暴增封禁peer，但并未实际封禁。连续两天都会发生此现象

试试打开增量封禁呢

**Comment by Ghost-chu** [comment]
> 订阅了在线规则jsdelivr，更新后无法编辑，无法删除，无法关闭

群里联系我一下，私聊发送下 config.yml 文件。不要公开上传。

**Comment by Ghost-chu** [comment]
> 开机启动后会暴增封禁peer，但并未实际封禁。连续两天都会发生此现象

此问题已修复
