### ISSUE TITLE
[Feature] 在Peer列表中显示地理信息

### ISSUE THREAD

**Issue by FrzMtrsprt** [PBH-BTN/PeerBanHelper#519]
希望能在活跃种子的Peer列表中显示每个Peer的地理信息，就像在下载器中那样。可以考虑默认显示国旗，鼠标悬浮时显示具体信息。

**Comment by Gaojianli** [comment]
数据提供了吗 @Ghost-chu

**Comment by Gaojianli** [comment]
![image](https://github.com/user-attachments/assets/77068d9f-95cd-4ad6-96cd-d4eef6bf20f8)
