### ISSUE TITLE
[WebUI] UI优化：分页页码

### ISSUE THREAD

**Issue by rihalvnium76** [PBH-BTN/PeerBanHelper#52]
版本：v2.8 win x64 Native Image

![image](https://github.com/Ghost-chu/PeerBanHelper/assets/57667144/747636b1-3ed8-4972-969c-c7102dd42d4f)

分页页码建议从 1 开始

**Comment by Ghost-chu** [comment]
说实话，我搞不太定它😂。项目需要一位前端老哥帮帮忙，我这都是对着搜索引擎写的，它能工作已经是奇迹了。

**Comment by rihalvnium76** [comment]
而且分页也没做边界检测，点下一页可以跳转到完全没数据的一页

**Comment by Ghost-chu** [comment]
> 而且分页也没做边界检测，点下一页可以跳转到完全没数据的一页

问题不大，这个WebUI最起码能用👍  
这个很早就注意到了，但是考虑到后面 WebUI 需要重构，也就没动这一块儿了。

**Comment by rihalvnium76** [comment]
```js
let page = urlSearchParams.get("pageIndex");
if (page === undefined || page === null) {
    page = "0"; // 此处应该为 "1"
}
```

**Comment by rihalvnium76** [comment]
`previousPage()` 和 `nextPage()` 应该加上边界判断

不过感觉你压根没做分页功能

**Comment by Gaojianli** [comment]
等我抽个时间来搞一下这个吧
