### ISSUE TITLE
[Question] 进度倒退检测的差值是什么？

### ISSUE THREAD

**Issue by CreeperAWA** [PBH-BTN/PeerBanHelper#558]
如题
举个例子
![image](https://github.com/user-attachments/assets/fca2eaca-7f9b-439d-bca4-93845cf52042)
这里的 封禁原因 显示 客户端进度：0.40%，实际进度：2.20%，上次记录进度：99.90%，本次回退进度：99.50%，差值：7.00%
前面的都好理解，可是这个差值是什么？怎么计算的？而且我发现触发进度倒退检测的差值都显示的是 7.00%

**Comment by DrJason33564** [comment]
指的应该是触发检测的阈值吧

**Comment by CreeperAWA** [comment]
> 指的应该是触发检测的阈值吧

我猜测可能是，但我认为这样表达不严谨且容易引起误会

**Comment by Ghost-chu** [comment]
这个插值会出现两种形式：
* 一种是固定的百分比，代表阈值
* 另一种是动态的百分比，代表相差值

至于为什么这么写，这是一个历史故事。后面有空改改。

**Comment by CreeperAWA** [comment]
> 这个插值会出现两种形式：
> * 一种是固定的百分比，代表阈值
> * 另一种是动态的百分比，代表相差值
> 
> 至于为什么这么写，这是一个历史故事。后面有空改改。

感谢回复

**Comment by ngkaichak** [comment]
这功能误封我云主机五次了

**Comment by Ghost-chu** [comment]
> 这功能误封我云主机五次了

配置文件里云主机加白就行了
