### ISSUE TITLE
添加bitcomet下载器时报错Cannot find any provider supporting AES/CBC/PKCS7Padding

### ISSUE THREAD

**Issue by Changcta** [PBH-BTN/PeerBanHelper#562]
### WebUI 版本号 - Version

v2.3.0-(abf36697) 

### 问题描述 - Issue Description

按照操作手册添加bitcomet下载器，测试下载器提示Cannot find any provider supporting AES/CBC/PKCS7Padding
bitcomet的webui可以正常打开

### 复现步骤 - Reproduce steps

1. 配置下载器
2. 点击测试下载器

### 截图 - Screenshot  

![20241006204847](https://github.com/user-attachments/assets/9b50c2e1-e993-4ac9-b9ff-e84dd599a06d)

### 额外信息 - Addition Information

安装包使用  PeerBanHelper_windows-x64_6.4.1_nojava  

### 检查清单 - Check list

- [X] PeerBanHelper 已更新到最新版本 (I'm running the latest version of PBH that can be found in Github Relases)
- [X] 我已检查过 [PBH 文档](https://pbh-btn.github.io/pbh-docs/)（特别是常见问题），且即使使用了搜索也没有找到与此有关的内容 (This not a question/or the question that not listed in README's FAQ or [PBH WIKI](https://pbh-btn.github.io/pbh-docs/))
- [ ] 我没有检查这个检查清单，只是闭眼选中了所有的复选框，请关闭这个 Issue (I have not read these checkboxes and therefore I just ticked them all, Please close this issue)

**Comment by Ghost-chu** [comment]
感谢您的支持，尽管这看起来很像一个错误，但由于您选择了错误的问题模板**且** Issue 中没有提供我们所需要的关键线索，因此我不得不将这个问题关闭。

烦请您使用正确的后端问题反馈模板再次报告此问题。
