### ISSUE TITLE
[功能请求] 可以在规则管理中增加封禁指定客户端的规则

### ISSUE THREAD

**Issue by CreeperAWA** [PBH-BTN/PeerBanHelper#568]
如题，虽然我知道这并不好，尤其是有的客户端的用户非常多，简单而又粗暴的屏蔽会产生很多不良影响，不过我认为可以与 #569 的功能结合使用

**Comment by Ghost-chu** [comment]
https://pbh-btn.github.io/pbh-docs/docs/module/client-name  
https://pbh-btn.github.io/pbh-docs/docs/module/peer-id

暂时无法组合使用

**Comment by CreeperAWA** [comment]
> https://pbh-btn.github.io/pbh-docs/docs/module/client-name https://pbh-btn.github.io/pbh-docs/docs/module/peer-id
我看到了这两篇文档，不过我并没有在规则管理模块找到这个功能，所以我提出的是**在规则管理中增加**

> 暂时无法组合使用
感谢回复，期待该功能

**Comment by Ghost-chu** [comment]
![image](https://github.com/user-attachments/assets/0f03957b-746b-42d6-a21e-235c6deeab7f)

相关工作 @Gaojianli 老师已经在推进了

**Comment by Ghost-chu** [comment]
新版 WebUI 已完成对规则修改的支持
