### ISSUE TITLE
[WebUI] MacOS无法正确启动

### ISSUE THREAD

**Issue by BasaltCompass** [PBH-BTN/PeerBanHelper#577]
### WebUI 版本号 - Version

v2.3.1(adf1c2c2)

### 问题描述 - Issue Description

- 在M2芯片的Macmini上安装[PeerBanHelper_macos_universal_6.4.1.dmg](https://github.com/PBH-BTN/PeerBanHelper/releases/download/v6.4.1/PeerBanHelper_macos_universal_6.4.1.dmg)（6.4.2相同）
- 安装后得到三个客户端：GUI、Swing、GUI-silent
- 三个客户端启动后都无法正常运行，运行后在程序坞跳动一段时间（~180s）后卡住，跳动同时进程显示“未响应”
- 三个客户端中，Swing虽然显示未响应，但运行后可以通过端口进入webUI，并且PBH似乎能够正常工作
![image](https://github.com/user-attachments/assets/4ad37253-68f0-4035-9c28-452c7faa9e14)

### 复现步骤 - Reproduce steps

1. 在M2芯片的，MacOS15.0.1的Macmini上安装PeerBanHelper_macos_universal_6.4.1.dmg
2. 运行GUI、Swing、GUI-silent三个中任意一个程序（无论先后），都会未响应
3. 运行Swing虽然也会显示未响应，但可以在浏览器中通过端口进入webUI，并连接bt客户端

### 截图 - Screenshot  

![image](https://github.com/user-attachments/assets/6a8acfba-fdb2-45d3-b109-c17392c0147c)

### 检查清单 - Check list

- [X] PeerBanHelper 已更新到最新版本 (I'm running the latest version of PBH that can be found in Github Relases)
- [X] 我已检查过 [PBH 文档](https://pbh-btn.github.io/pbh-docs/)（特别是常见问题），且即使使用了搜索也没有找到与此有关的内容 (This not a question/or the question that not listed in README's FAQ or [PBH WIKI](https://pbh-btn.github.io/pbh-docs/))
- [ ] 我没有检查这个检查清单，只是闭眼选中了所有的复选框，请关闭这个 Issue (I have not read these checkboxes and therefore I just ticked them all, Please close this issue)

**Comment by Ghost-chu** [comment]
感谢您的反馈，这是一个已知问题。
建议暂时使用 docker 运行。开发者没有 Apple 家的设备，无法做更进一步的调试。

**Comment by BasaltCompass** [comment]
> 感谢您的反馈，这是一个已知问题。 建议暂时使用 docker 运行。开发者没有 Apple 家的设备，无法做更进一步的调试。

了解，感谢开发者！
