### ISSUE TITLE
[功能请求]在检测到PeerBanHelper出现异常时自动对种子进行限速

### ISSUE THREAD

**Issue by SteveYu000** [PBH-BTN/PeerBanHelper#581]
为了应对之前PeerBanHelper崩溃的类似情况，建议可以增加一个心跳检测程序，PeerBanHelper正常运行时则定时发出消息，如果异常（包括程序崩溃、下载器连接异常等），则停止发出消息或发出异常消息，**检测程序发现异常状态则对对应的BT客户端进行上传限速**，这样可以有效防止被大量吸血

**Comment by Ghost-chu** [comment]
Java程序显然要运行在 JVM虚拟机里，包括心跳。崩溃的时候显然是整个虚拟机都挂掉了，自然也无法再操作下载器了

**Comment by SteveYu000** [comment]
用其他语言写一个检测器怎么样呢？只写检测器

**Comment by azicen** [comment]
可以考虑使用docker等容器环境，使用容器去保活。即使出现崩溃也能通过快速恢复的方式防止被放血
