### ISSUE TITLE
[功能请求]增加速率统计图表

### ISSUE THREAD

**Issue by desktop4025** [PBH-BTN/PeerBanHelper#589]
我看统计有流量上传图表，我觉得可以加一个速率图表，类似qbit里面的速率
![图片](https://github.com/user-attachments/assets/4243108e-d3d2-41b4-a1f7-2789391c6e14)

**Comment by Ghost-chu** [comment]
你都说了 qb 有速率图表了，这我们就不加了。对于反吸血来说，意义不大，徒增压力。  
图表信息在 WebAPI 中也不可用，并且其它下载器并不都有此图表。
