### ISSUE TITLE
[功能建议] 自动范围封禁时考虑封禁原因

### ISSUE THREAD

**Issue by tongxiangzheng** [PBH-BTN/PeerBanHelper#599]
### 问题描述 - Issue Description

情况说明：
当我检查封禁名单时，我发现PeerBanHelper封禁了较多的教育网用户，分析原因发现最早由于一个校园网用户使用了迅雷，使得此用户的ipv6 ip被封禁（这一点完全没问题）。接下来当同一个学校的其他用户与我的设备连接时，自动范围封禁功能检测到这些用户与已封禁ip处于同一前缀下，因此执行连续封禁。但是我倾向于认为这些用户大部分是真实的流量，因此不希望因为一个用户使用了迅雷而执行连坐制度。不过，自动范围封禁对我而言同样非常有用，因此我不打算直接关闭此功能。
请求的功能：
请问自动范围封禁功能能否增加配置选项，可以在检查是否需要范围封禁时筛选封禁原因，排除一些情节轻微的封禁IP？

### 检查清单 - Check list

- [X] 这不是一个错误 （BUG） (This is not an bug/error)
- [X] PeerBanHelper 已更新到最新版本，非最新版本不接受任何错误反馈，任何非最新版本的 Issue 将被 立 刻 关 闭，不会有人给您提供任何支持 (I'm running the latest version of PBH that can be found in Github Relases, non-latest release won't receive any support)
- [X] 我已检查过 [PBH 文档](https://pbh-btn.github.io/pbh-docs/)（特别是常见问题），且即使使用了搜索也没有找到与此有关的内容 (This not a question/or the question that not listed in README's FAQ or [PBH WIKI](https://pbh-btn.github.io/pbh-docs/))
- [X] 我同意遵守 PBH-BTN 包容性条约，不发布 “嘲讽、骂战、引战、开盒（有时也称为人肉搜索）、人身攻击、仇恨、暴力、侮辱性言辞、违法违规、黑灰产、危害国家安全、实施或帮助他人实施电信犯罪” 等内容。并已知晓如果仍旧发布了这些内容，我的账号将立刻从包括但不限于 PBH-BTN 组织、社交软件中封禁。所有主题、内容都将被立刻删除或折叠，撤销、删除和收回您所做出的一切贡献，并封禁 BTN 网络的中账号权限、排除您所提交的所有数据。在您违反相关规则时，PBH-BTN 将会将您的注册、登录、和最近访问的 IP 地址、电子邮件地址、以及其它可能追踪您或将您去匿名化的信息从定期删除转为永不删除，并在任何国家或地区的政府、公安机关或有关部门需要时无通知的提供这些数据。 (I agree to abide by the PBH-BTN Inclusivity Pact by not posting content such as “taunting, name-calling, war-mongering, open-boxing (sometimes referred to as mansplaining), personal attacks, hatred, violence, insulting language, illegal activities, black and grey business, endangering national security, and committing or assisting others in committing telecommunication crimes”. I am aware that if I continue to post such content, my account will be immediately banned from organizations including but not limited to PBH-BTN, social software. All topics and content will be immediately deleted or collapsed, all contributions will be revoked, deleted and retracted, and you will be banned from the BTN network and all data you have submitted will be excluded. In the event of a violation of these rules, PBH-BTN will delete your registration, login, and most recent IP address, email address, and any other information that may be used to track you or de-anonymize you from regular to permanent deletion, and will make this data available to the government, public security, or other relevant authorities without notice if they request it, no matter what country or region.)

**Comment by Ghost-chu** [comment]
你可以直接把学校 IP 段放进 profile.yml 的例外列表里，不参与检查。

**Comment by Duck1998** [comment]
如果只是想单独拒绝迅雷的话，也许可以在PBH的profile文件里允许迅雷的ClientID和PeerID，只由BT下载器负责阻断，例如QB的peer_blacklist.txt，或者QBEE内置默认开启的阻断功能。这样就是阻断连接而不是拉黑IP了。

**Comment by Gaojianli** [comment]
> 你可以直接把学校 IP 段放进 profile.yml 的例外列表里，不参与检查。

他的意思应该是想要peer封禁不触发连锁封禁吧，这个问题我之前也提过，感觉误伤较大

**Comment by Ghost-chu** [comment]
> > 你可以直接把学校 IP 段放进 profile.yml 的例外列表里，不参与检查。
> 
> 他的意思应该是想要peer封禁不触发连锁封禁吧，这个问题我之前也提过，感觉误伤较大

那就直接关了连锁封禁就好了嘛

**Comment by tongxiangzheng** [comment]
> 你可以直接把学校 IP 段放进 profile.yml 的例外列表里，不参与检查。

好的，我直接放例外列表，解决问题了

**Comment by WordlessEcho** [comment]
今天看到一个IP用迅雷封3天，连锁封禁直接封7天，我觉得还是把连锁封禁的时间改小一些或者关掉吧（
