### ISSUE TITLE
[功能建议] 配置文件导出或导入（WebUI）

### ISSUE THREAD

**Issue by happilying** [PBH-BTN/PeerBanHelper#613]
### 问题描述 - Issue Description

是否能加入使用webui导出或导入配置文件以使迁移或更新更方便

### 检查清单 - Check list

- [X] 这不是一个错误 （BUG） (This is not an bug/error)
- [X] PeerBanHelper 已更新到最新版本，非最新版本不接受任何错误反馈，任何非最新版本的 Issue 将被 立 刻 关 闭，不会有人给您提供任何支持 (I'm running the latest version of PBH that can be found in Github Relases, non-latest release won't receive any support)
- [X] 我已检查过 [PBH 文档](https://pbh-btn.github.io/pbh-docs/)（特别是常见问题），且即使使用了搜索也没有找到与此有关的内容 (This not a question/or the question that not listed in README's FAQ or [PBH WIKI](https://pbh-btn.github.io/pbh-docs/))
- [X] 我同意遵守 PBH-BTN 包容性条约，不发布 “嘲讽、骂战、引战、开盒（有时也称为人肉搜索）、人身攻击、仇恨、暴力、侮辱性言辞、违法违规、黑灰产、危害国家安全、实施或帮助他人实施电信犯罪” 等内容。并已知晓如果仍旧发布了这些内容，我的账号将立刻从包括但不限于 PBH-BTN 组织、社交软件中封禁。所有主题、内容都将被立刻删除或折叠，撤销、删除和收回您所做出的一切贡献，并封禁 BTN 网络的中账号权限、排除您所提交的所有数据。在您违反相关规则时，PBH-BTN 将会将您的注册、登录、和最近访问的 IP 地址、电子邮件地址、以及其它可能追踪您或将您去匿名化的信息从定期删除转为永不删除，并在任何国家或地区的政府、公安机关或有关部门需要时无通知的提供这些数据。 (I agree to abide by the PBH-BTN Inclusivity Pact by not posting content such as “taunting, name-calling, war-mongering, open-boxing (sometimes referred to as mansplaining), personal attacks, hatred, violence, insulting language, illegal activities, black and grey business, endangering national security, and committing or assisting others in committing telecommunication crimes”. I am aware that if I continue to post such content, my account will be immediately banned from organizations including but not limited to PBH-BTN, social software. All topics and content will be immediately deleted or collapsed, all contributions will be revoked, deleted and retracted, and you will be banned from the BTN network and all data you have submitted will be excluded. In the event of a violation of these rules, PBH-BTN will delete your registration, login, and most recent IP address, email address, and any other information that may be used to track you or de-anonymize you from regular to permanent deletion, and will make this data available to the government, public security, or other relevant authorities without notice if they request it, no matter what country or region.)

**Comment by Gaojianli** [comment]
@Ghost-chu 这个可以有，需要两个接口，一个下载tar.gz（包含所有配置文件，和脚本以及他们的映射关系），一个上传文件（整个tar）

**Comment by Ghost-chu** [comment]
你直接把 data 打个 zip 带走不就行了吗，整的花里胡哨

**Comment by jonm58** [comment]
这个功能没什么用,建议不加
加了浪费硬盘空间

**Comment by happilying** [comment]
主要是针对远程或docker（docker更新还得换镜像新建容器，更别说上传文件的困难了，远程你只能访问webui的情况下也没法对目录进行文件更改），可以在OOBE就弄个已有配置文件，是否导入的功能，这样也可继承之前的Token（随机生成的话加上保存密码谁去记这些）和配置，对于多下载器也很有用（虽然应该不会有人下挂很多个下载器就是了）

**Comment by Ghost-chu** [comment]
本质上还是一个压缩包打包数据，自己给 data 打个包就行了。这部分由 PeerBanHelper 实现不是一个很好的主意。  
至于你说的镜像新建容器，使用推荐的 docker-compose 部署没有上述问题，直接更换镜像标签就好了。更新也完全可以使用 watchtowner 等方式。如果使用非推荐部署方式，我们默认你有足够的能力处理这些棘手的问题。

**Comment by happilying** [comment]
QS，我个人主要是想减少更新时的门槛和耗费时间，毕竟对于24H做种的话，每多停机一秒，被吸血的可能性和量就越多（我是一点都不想让那些PCDN的找到一点机会吸流量），但对于这个问题最好的解决方案是弄个不停机更新系统出来（或更新时自动停止，更新完恢复做种），WebUI导出导入配置算一个降低门槛的作用吧。

**Comment by Ghost-chu** [comment]
理解您的心情，但我们的人手就这么多，只能先挑重要的改。不停机更新太困难了，收益和付出不成正比。可能花一个月做出来之后，效果和没有差不多。
