### ISSUE TITLE
[WebUI] WebUI数据透视页显示封禁记录有误

### ISSUE THREAD

**Issue by DrJason33564** [PBH-BTN/PeerBanHelper#640]
### WebUI 版本号 - Version

2.3.1

### 问题描述 - Issue Description

在我的PBH的数据透视页对封禁排行前二的IP进行数据透视时，显示的封禁日志为来自同一种子的两个不同迅雷客户端，且所有记录显示的封禁日期均为同一天。同时，两IP的封禁记录除各自的最后一两条有端口和进度记录外，其他记录这两项都为空。具体可见附的截图
经过检查发现，自我的封禁排行中第五项IP（124.225.94.99）开始后的所有IP应该不存在此问题

### 复现步骤 - Reproduce steps

1. 登录WebUI
2. 对封禁IP进行数据透视

### 截图 - Screenshot  

数据透视页问题↓
![Screenshot 2024-10-27 at 19-24-04 PeerBanHelper](https://github.com/user-attachments/assets/653e541c-05bd-4bcc-a817-9bf24d91986c)
![Screenshot 2024-10-27 at 19-26-04 PeerBanHelper](https://github.com/user-attachments/assets/f2032626-e3ad-43a8-9cd1-100e67432d38)
![Screenshot 2024-10-27 at 19-25-25 PeerBanHelper](https://github.com/user-attachments/assets/9a821a94-bb4a-40bf-88c4-0388469eb264)
![Screenshot 2024-10-27 at 19-54-25 PeerBanHelper](https://github.com/user-attachments/assets/4b723296-ce74-4d6e-acf3-d314d5e61528)
我的封禁排行第一页↓
![图片](https://github.com/user-attachments/assets/89180f84-945a-4d32-a972-f0ecedbe5701)

### 额外信息 - Addition Information

我曾经开启过主动监测（active-monitoring），但由于担心对emmc芯片造成影响在9月中旬后将其关闭
上述提到存在问题的IP都发现于我关闭主动监测前，但它们在数据透视页显示的IP访问次数均为0
![图片](https://github.com/user-attachments/assets/e35b5183-f011-45d0-b97f-4334be9b3b08)
![图片](https://github.com/user-attachments/assets/1343f8c3-15f3-41e3-b159-6af04464b7dc)
而发现于关闭主动监测前但不存在问题的IP在数据透视页有IP访问次数统计
![图片](https://github.com/user-attachments/assets/1c84a365-7eaf-474d-8b35-bc2ab3f98a03)
![图片](https://github.com/user-attachments/assets/d1cf4974-a818-47aa-8afe-ec6fa1fdcd02)
发现于关闭主动监测功能后的IP不存在这一问题。数据库（persist文件夹中文件）在关闭主动监测后没有更换或清空

### 检查清单 - Check list

- [X] PeerBanHelper 已更新到最新版本，非最新版本不接受任何错误反馈，任何非最新版本的 Issue 将被 立 刻 关 闭，不会有人给您提供任何支持 (I'm running the latest version of PBH that can be found in Github Relases, non-latest release won't receive any support)
- [X] 我已检查过 [PBH 文档](https://pbh-btn.github.io/pbh-docs/)（特别是常见问题），且即使使用了搜索也没有找到与此有关的内容 (This not a question/or the question that not listed in README's FAQ or [PBH WIKI](https://pbh-btn.github.io/pbh-docs/))
- [ ] 我没有检查这个检查清单，只是闭眼选中了所有的复选框，请关闭这个 Issue (I have not read these checkboxes and therefore I just ticked them all, Please close this issue)
- [X] 所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [X] 我同意遵守 PBH-BTN 包容性条约，不发布 “嘲讽、骂战、引战、开盒（有时也称为人肉搜索）、人身攻击、仇恨、暴力、侮辱性言辞、违法违规、黑灰产、危害国家安全、实施或帮助他人实施电信犯罪” 等内容。并已知晓如果仍旧发布了这些内容，我的账号将立刻从包括但不限于 PBH-BTN 组织、社交软件中封禁。所有主题、内容都将被立刻删除或折叠，撤销、删除和收回您所做出的一切贡献，并封禁 BTN 网络的中账号权限、排除您所提交的所有数据。在您违反相关规则时，PBH-BTN 将会将您的注册、登录、和最近访问的 IP 地址、电子邮件地址、以及其它可能追踪您或将您去匿名化的信息从定期删除转为永不删除，并在任何国家或地区的政府、公安机关或有关部门需要时无通知的提供这些数据。 (I agree to abide by the PBH-BTN Inclusivity Pact by not posting content such as “taunting, name-calling, war-mongering, open-boxing (sometimes referred to as mansplaining), personal attacks, hatred, violence, insulting language, illegal activities, black and grey business, endangering national security, and committing or assisting others in committing telecommunication crimes”. I am aware that if I continue to post such content, my account will be immediately banned from organizations including but not limited to PBH-BTN, social software. All topics and content will be immediately deleted or collapsed, all contributions will be revoked, deleted and retracted, and you will be banned from the BTN network and all data you have submitted will be excluded. In the event of a violation of these rules, PBH-BTN will delete your registration, login, and most recent IP address, email address, and any other information that may be used to track you or de-anonymize you from regular to permanent deletion, and will make this data available to the government, public security, or other relevant authorities without notice if they request it, no matter what country or region.)

**Comment by Ghost-chu** [comment]
关闭后不会删除旧数据，只是暂停记录新数据。毕竟删除数据也是一顿擦写。

**Comment by DrJason33564** [comment]
> 关闭后不会删除旧数据，只是暂停记录新数据。毕竟删除数据也是一顿擦写。

问题在于上图中的223.98.183.169和36.148.144.222这两个ip下记录的封禁数据有明显错误

**Comment by Ghost-chu** [comment]
没有看出来问题。如果你的下载器就不支持流量统计（如部分版本的 BitComet），那么它确实会显示 N/A。  
如果 PBH 提交封禁请求后，下载器没有及时封禁，那么 PBH 可能会尝试再次进行封禁。此时确有可能创建重复记录。常见于 BitComet 下载器。

你现在所说的问题已经不属于 WebUI 范畴了，我将关闭这个 Issue。如果仍需要继续反馈，请填写核心问题反馈模板，并附上模板上所要求的其它信息。

**Comment by DrJason33564** [comment]
感谢答复，看了下这几个ip应该是来自对比特彗星的封禁操作
