### ISSUE TITLE
[WebUI] 关于近期改用aria2/1.37.0进行规避检测的问题

### ISSUE THREAD

**Issue by autumnsentiment** [PBH-BTN/PeerBanHelper#641]
### WebUI 版本号 - Version

6.4.8

### 问题描述 - Issue Description

鉴于近期检测到的pcdn脚本全为aria2/1.37.0客户端，新增对该客户端的行为监测，IP段仍为pcdn三大省

### 复现步骤 - Reproduce steps

未开启时监测到使用7月热门番剧做种遭遇放血，特征网段222.185.229.0;61.147.218.0网段，且带有防封禁检测脚本，一旦中断离开规避本机IP

### 截图 - Screenshot  

![屏幕截图 2024-10-27 200927](https://github.com/user-attachments/assets/e366672e-8763-45ed-af69-aafc7dee8e99)

### 检查清单 - Check list

- [ ] PeerBanHelper 已更新到最新版本，非最新版本不接受任何错误反馈，任何非最新版本的 Issue 将被 立 刻 关 闭，不会有人给您提供任何支持 (I'm running the latest version of PBH that can be found in Github Relases, non-latest release won't receive any support)
- [ ] 我已检查过 [PBH 文档](https://pbh-btn.github.io/pbh-docs/)（特别是常见问题），且即使使用了搜索也没有找到与此有关的内容 (This not a question/or the question that not listed in README's FAQ or [PBH WIKI](https://pbh-btn.github.io/pbh-docs/))
- [ ] 我没有检查这个检查清单，只是闭眼选中了所有的复选框，请关闭这个 Issue (I have not read these checkboxes and therefore I just ticked them all, Please close this issue)
- [ ] 所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [X] 我同意遵守 PBH-BTN 包容性条约，不发布 “嘲讽、骂战、引战、开盒（有时也称为人肉搜索）、人身攻击、仇恨、暴力、侮辱性言辞、违法违规、黑灰产、危害国家安全、实施或帮助他人实施电信犯罪” 等内容。并已知晓如果仍旧发布了这些内容，我的账号将立刻从包括但不限于 PBH-BTN 组织、社交软件中封禁。所有主题、内容都将被立刻删除或折叠，撤销、删除和收回您所做出的一切贡献，并封禁 BTN 网络的中账号权限、排除您所提交的所有数据。在您违反相关规则时，PBH-BTN 将会将您的注册、登录、和最近访问的 IP 地址、电子邮件地址、以及其它可能追踪您或将您去匿名化的信息从定期删除转为永不删除，并在任何国家或地区的政府、公安机关或有关部门需要时无通知的提供这些数据。 (I agree to abide by the PBH-BTN Inclusivity Pact by not posting content such as “taunting, name-calling, war-mongering, open-boxing (sometimes referred to as mansplaining), personal attacks, hatred, violence, insulting language, illegal activities, black and grey business, endangering national security, and committing or assisting others in committing telecommunication crimes”. I am aware that if I continue to post such content, my account will be immediately banned from organizations including but not limited to PBH-BTN, social software. All topics and content will be immediately deleted or collapsed, all contributions will be revoked, deleted and retracted, and you will be banned from the BTN network and all data you have submitted will be excluded. In the event of a violation of these rules, PBH-BTN will delete your registration, login, and most recent IP address, email address, and any other information that may be used to track you or de-anonymize you from regular to permanent deletion, and will make this data available to the government, public security, or other relevant authorities without notice if they request it, no matter what country or region.)

**Comment by Ghost-chu** [comment]
谢谢，希望可以详细说明下 "新增对该客户端的行为监测" 和 “带有防封禁检测脚本” 具体是什么？  
“一旦中断离开规避本机IP” 具体是怎样的？

**Comment by autumnsentiment** [comment]
> 谢谢，希望可以详细说明下 "新增对该客户端的行为监测" 和 “带有防封禁检测脚本” 具体是什么？ “一旦中断离开规避本机IP” 具体是怎样的？

该问题是出现新的刷量脚本，客户端为aria/1.37.0，本lssues仅做对新刷量脚本特征进行报备。该脚本自带识别当前连接且正在活动的IP，一旦出现中断则ban掉该IP，以规避被PBH等项目发现

**Comment by Ghost-chu** [comment]
没关系的，我们在 10 月 7 日就已经发现这个样本并开始针对性拦截了~

只要您开启并连接到 BTN，他们就很难规避发现。PBH 会定期拍摄下载器上的所有 Peers 快照传输到 BTN 服务器，我们会定期检查快照情况，来确认是不是有人绕过了检查。

在即将到来的 v7 版本，BTN 还进行了增强，即使是吸血游击战，也无法躲过检查了。现在 PBH v7 配合新 BTN 协议能直接合并计算 BTN 全网的流量数据。

**Comment by autumnsentiment** [comment]
> 没关系的，我们在 10 月 7 日就已经发现这个样本并开始针对性拦截了~
> 
> 只要您开启并连接到 BTN，他们就很难规避发现。PBH 会定期拍摄下载器上的所有 Peers 快照传输到 BTN 服务器，我们会定期检查快照情况，来确认是不是有人绕过了检查。
> 
> 在即将到来的 v7 版本，BTN 还进行了增强，即使是吸血游击战，也无法躲过检查了。现在 PBH v7 配合新 BTN 协议能直接合并计算 BTN 全网的流量数据。

感谢回复。
针对该脚本可能存在的防检测问题，还需依仗各位大佬进行监测
