### ISSUE TITLE
[Other] 通过WebUI直接修改配置文件

### ISSUE THREAD

**Issue by happilying** [PBH-BTN/PeerBanHelper#680]
### 问题描述 - Issue Description

RT，是否可以在WebUI中设置一个高级（开发者）选项用于直接在web中编辑config.yml与profile.yml文件

### 额外信息 - Addition Information

Q：为什么不直接下载xml？
A：第一，为了只修改几行而直接去docker提取文件修改完再上传有点小题大做。
第二，如果远程（走公网）状态的话登陆nas或路由器后台修改文件存在管理密码泄露的风险（容易泄露docker管理密码或整个nas的密码）。
第三：如果手头刚好没有电脑，用手机的一言难尽的文档编辑体验（虽然手机Web编辑也是很糟糕就是了）。PS：应该不会有人买了nas但只会用手机app配置吧......😂

### 检查清单 - Check list

- [X] 这不是一个错误 （BUG） (This is not an bug/error)
- [X] PeerBanHelper 已更新到最新版本，非最新版本不接受任何错误反馈，任何非最新版本的 Issue 将被 立 刻 关 闭，不会有人给您提供任何支持 (I'm running the latest version of PBH that can be found in Github Relases, non-latest release won't receive any support)
- [X] 我已检查过 [PBH 文档](https://docs.pbh-btn.com/)（特别是常见问题），且即使使用了搜索也没有找到与此有关的内容 (This not a question/or the question that not listed in README's FAQ or [PBH WIKI](https://docs.pbh-btn.com/))
- [X] 我同意遵守 PBH-BTN 包容性条约，不发布 “嘲讽、骂战、引战、开盒（有时也称为人肉搜索）、人身攻击、仇恨、暴力、侮辱性言辞、违法违规、黑灰产、危害国家安全、实施或帮助他人实施电信犯罪” 等内容。并已知晓如果仍旧发布了这些内容，我的账号将立刻从包括但不限于 PBH-BTN 组织、社交软件中封禁。所有主题、内容都将被立刻删除或折叠，撤销、删除和收回您所做出的一切贡献，并封禁 BTN 网络的中账号权限、排除您所提交的所有数据。在您违反相关规则时，PBH-BTN 将会将您的注册、登录、和最近访问的 IP 地址、电子邮件地址、以及其它可能追踪您或将您去匿名化的信息从定期删除转为永不删除，并在任何国家或地区的政府、公安机关或有关部门需要时无通知的提供这些数据。 (I agree to abide by the PBH-BTN Inclusivity Pact by not posting content such as “taunting, name-calling, war-mongering, open-boxing (sometimes referred to as mansplaining), personal attacks, hatred, violence, insulting language, illegal activities, black and grey business, endangering national security, and committing or assisting others in committing telecommunication crimes”. I am aware that if I continue to post such content, my account will be immediately banned from organizations including but not limited to PBH-BTN, social software. All topics and content will be immediately deleted or collapsed, all contributions will be revoked, deleted and retracted, and you will be banned from the BTN network and all data you have submitted will be excluded. In the event of a violation of these rules, PBH-BTN will delete your registration, login, and most recent IP address, email address, and any other information that may be used to track you or de-anonymize you from regular to permanent deletion, and will make this data available to the government, public security, or other relevant authorities without notice if they request it, no matter what country or region.)

**Comment by Ghost-chu** [comment]
现有的 WebUI 的设置选项卡无法满足要求么？是修改哪些内容还需要手动编辑文件呢。

**Comment by happilying** [comment]
似乎并没有找到邮件推送（如果是我眼睛瞎了我道歉）🧐

**Comment by Ghost-chu** [comment]
> 似乎并没有找到邮件推送（如果是我眼睛瞎了我道歉）🧐

邮件推送没赶上版本，相关 API 还没到位，所以暂时确实需要通过配置文件修改。

@Gaojianli 能不能来个无菜单仅路由的直接编辑功能

**Comment by happilying** [comment]
我看似乎有自定义脚本，但因为安全原因禁用，可能是还没ssl适配所以暂时禁用？🧐

**Comment by Ghost-chu** [comment]
> 我看似乎有自定义脚本，但因为安全原因禁用，可能是还没ssl适配所以暂时禁用？🧐

还请等待下一个 minor 版本，下个 minor 版本包含对自定义脚本的 WebUI 适配，以及 BTN 下发脚本规则的支持。

![image](https://github.com/user-attachments/assets/039d8f87-1811-44e5-844a-4e49ca1f79bc)

**Comment by happilying** [comment]
> > 我看似乎有自定义脚本，但因为安全原因禁用，可能是还没ssl适配所以暂时禁用？🧐
> 
> 还请等待下一个 minor 版本，下个 minor 版本包含对自定义脚本的 WebUI 适配，以及 BTN 下发脚本规则的支持。
> 
> ![image](https://private-user-images.githubusercontent.com/30802565/382583425-039d8f87-1811-44e5-844a-4e49ca1f79bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NDgzNDgsIm5iZiI6MTczMDY0ODA0OCwicGF0aCI6Ii8zMDgwMjU2NS8zODI1ODM0MjUtMDM5ZDhmODctMTgxMS00NGU1LTg0NGEtNGU0OWNhMWY3OWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDE1MzQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNzY4MjViNWFjMjY2ZmY2MWQwZGU0ZTlmYTFjYmU0Y2E3ODcyNmE5ZTY5ZWUxN2U4YWJkNDgxOGUzZmUzYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PJ-EMtg7iWw3AIUk6fKz6gygRHBOTLU9m0J-H5ma20Q)

好！我TM直接打💰！（doge

**Comment by Gaojianli** [comment]
> > 似乎并没有找到邮件推送（如果是我眼睛瞎了我道歉）🧐
> 
> 邮件推送没赶上版本，相关 API 还没到位，所以暂时确实需要通过配置文件修改。
> 
> @Gaojianli 能不能来个无菜单仅路由的直接编辑功能

不给，改出问题了咋办

**Comment by Gaojianli** [comment]
以后我们尽量做到api和webui同步上线

**Comment by happilying** [comment]
> > > 似乎并没有找到邮件推送（如果是我眼睛瞎了我道歉）🧐
> > 
> > 
> > 邮件推送没赶上版本，相关 API 还没到位，所以暂时确实需要通过配置文件修改。
> > @Gaojianli 能不能来个无菜单仅路由的直接编辑功能
> 
> 不给，改出问题了咋办

出问题自负呗，就像手机开发者选项似的，可以隐藏的很深并且大屏警告但不能没有，但搞崩手机厂商不负责（😂

**Comment by Ghost-chu** [comment]
> > > > 似乎并没有找到邮件推送（如果是我眼睛瞎了我道歉）🧐
> > > 
> > > 
> > > 邮件推送没赶上版本，相关 API 还没到位，所以暂时确实需要通过配置文件修改。
> > > @Gaojianli 能不能来个无菜单仅路由的直接编辑功能
> > 
> > 
> > 不给，改出问题了咋办
> 
> 出问题自负呗，就像手机开发者选项似的，可以隐藏的很深并且大屏警告但不能没有，但搞崩手机厂商不负责（😂

想法很美好，现实通常是：

* [x] 安装为系统服务 （如果你不清楚这是什么，请不要勾选！）

“群主为什么 PBH 起不来，提示端口占用？”

**Comment by happilying** [comment]
> > > > > 似乎并没有找到邮件推送（如果是我眼睛瞎了我道歉）🧐
> > > > 
> > > > 
> > > > 邮件推送没赶上版本，相关 API 还没到位，所以暂时确实需要通过配置文件修改。
> > > > @Gaojianli 能不能来个无菜单仅路由的直接编辑功能
> > > 
> > > 
> > > 不给，改出问题了咋办
> > 
> > 
> > 出问题自负呗，就像手机开发者选项似的，可以隐藏的很深并且大屏警告但不能没有，但搞崩手机厂商不负责（😂
> 
> 想法很美好，现实通常是：
> 
> * [x]  安装为系统服务 （如果你不清楚这是什么，请不要勾选！）
> 
> “群主为什么 PBH 起不来，提示端口占用？”

这个放的太明显确实没法（天朝是这样的，我也经常前脚刚发完后脚立刻看到注释，但无法撤回......😂），可以作为远期规划或内部调试使用

**Comment by Ghost-chu** [comment]
> > > > > > 似乎并没有找到邮件推送（如果是我眼睛瞎了我道歉）🧐
> > > > > 
> > > > > 
> > > > > 邮件推送没赶上版本，相关 API 还没到位，所以暂时确实需要通过配置文件修改。
> > > > > @Gaojianli 能不能来个无菜单仅路由的直接编辑功能
> > > > 
> > > > 
> > > > 不给，改出问题了咋办
> > > 
> > > 
> > > 出问题自负呗，就像手机开发者选项似的，可以隐藏的很深并且大屏警告但不能没有，但搞崩手机厂商不负责（😂
> > 
> > 
> > 想法很美好，现实通常是：
> > 
> > * [x]   安装为系统服务 （如果你不清楚这是什么，请不要勾选！）
> > 
> > “群主为什么 PBH 起不来，提示端口占用？”
> 
> 这个放的太明显确实没法（天朝是这样的，我也经常前脚刚发完后脚立刻看到注释，但无法撤回......😂），可以作为远期规划或内部调试使用

我很希望开放大量内部或者高级操作，但现实证明只要你敢放，就一定有人头铁闭眼冲——哪怕会造成不可挽回的后果。  
编辑文件似乎也不是那么繁琐，对于邮件配置来说，你只需要配置一次，而且未来显然也迟早会加入 WebUI，只是时间问题，API 还需要更多的时间去调整。

**Comment by happilying** [comment]
诶，突发奇想，作者大大是否可以提供去除webui或其他模块的各种包以供小内存的路由器等设备使用以获得更广的兼容性？（虽然目前确实很简洁了）🧐

**Comment by Ghost-chu** [comment]
> 诶，突发奇想，作者大大是否可以提供去除webui或其他模块的各种包以供小内存的路由器等设备使用以获得更广的兼容性？（虽然目前确实很简洁了）🧐

WebUI 只有 2.16MB，GUI 也是 Java 自带的。  
占空间最大的是 SQLite 数据库驱动，但它显然算是 PBH 的核心。  
其次是 BouncyCastle，它也很大，但是连接 BitComet 是必须要它的。在过去的版本中我们尝试仅在需要的时候联网下载，但中国大陆的网络环境最终还是让我们放弃了这样做。  
剩下的则都是核心库，没有说哪个可以轻易删除的。  

当然，还有巨大无比的 Java 自己，这个是语言缺陷。  
我们平常也在努力压缩 PBH 的体积了，但受限于虚拟机本身它自己就巨大无比，实在是没什么办法。

native image 当玩具看看就行了，早期 PBH 的时候用过，效果非常差。

**Comment by happilying** [comment]
> > 诶，突发奇想，作者大大是否可以提供去除webui或其他模块的各种包以供小内存的路由器等设备使用以获得更广的兼容性？（虽然目前确实很简洁了）🧐
> 
> WebUI 只有 2.16MB，GUI 也是 Java 自带的。 占空间最大的是 SQLite 数据库驱动，但它显然算是 PBH 的核心。 其次是 BouncyCastle，它也很大，但是连接 BitComet 是必须要它的。在过去的版本中我们尝试仅在需要的时候联网下载，但中国大陆的网络环境最终还是让我们放弃了这样做。 剩下的则都是核心库，没有说哪个可以轻易删除的。
> 
> 当然，还有巨大无比的 Java 自己，这个是语言缺陷。 我们平常也在努力压缩 PBH 的体积了，但受限于虚拟机本身它自己就巨大无比，实在是没什么办法。
> 
> native image 当玩具看看就行了，早期 PBH 的时候用过，效果非常差。

好吧，希望之后这个项目能够获得大量人和物的帮助，这样之后就有充足的时间和精力针对不同平台定向优化体积了（底层改写）

**Comment by Ghost-chu** [comment]
> > > 诶，突发奇想，作者大大是否可以提供去除webui或其他模块的各种包以供小内存的路由器等设备使用以获得更广的兼容性？（虽然目前确实很简洁了）🧐
> > 
> > 
> > WebUI 只有 2.16MB，GUI 也是 Java 自带的。 占空间最大的是 SQLite 数据库驱动，但它显然算是 PBH 的核心。 其次是 BouncyCastle，它也很大，但是连接 BitComet 是必须要它的。在过去的版本中我们尝试仅在需要的时候联网下载，但中国大陆的网络环境最终还是让我们放弃了这样做。 剩下的则都是核心库，没有说哪个可以轻易删除的。
> > 当然，还有巨大无比的 Java 自己，这个是语言缺陷。 我们平常也在努力压缩 PBH 的体积了，但受限于虚拟机本身它自己就巨大无比，实在是没什么办法。
> > native image 当玩具看看就行了，早期 PBH 的时候用过，效果非常差。
> 
> 好吧，希望之后这个项目能够获得大量人和物的帮助，这样之后就有充足的时间和精力针对不同平台定向优化体积了（底层改写）

你可以换个思路，毕竟 PBH 是支持远程连接的。  
你可以把它放在比如台式、NAS、树莓派、或者废旧手机上。

**Comment by happilying** [comment]
> > > > 诶，突发奇想，作者大大是否可以提供去除webui或其他模块的各种包以供小内存的路由器等设备使用以获得更广的兼容性？（虽然目前确实很简洁了）🧐
> > > 
> > > 
> > > WebUI 只有 2.16MB，GUI 也是 Java 自带的。 占空间最大的是 SQLite 数据库驱动，但它显然算是 PBH 的核心。 其次是 BouncyCastle，它也很大，但是连接 BitComet 是必须要它的。在过去的版本中我们尝试仅在需要的时候联网下载，但中国大陆的网络环境最终还是让我们放弃了这样做。 剩下的则都是核心库，没有说哪个可以轻易删除的。
> > > 当然，还有巨大无比的 Java 自己，这个是语言缺陷。 我们平常也在努力压缩 PBH 的体积了，但受限于虚拟机本身它自己就巨大无比，实在是没什么办法。
> > > native image 当玩具看看就行了，早期 PBH 的时候用过，效果非常差。
> > 
> > 
> > 好吧，希望之后这个项目能够获得大量人和物的帮助，这样之后就有充足的时间和精力针对不同平台定向优化体积了（底层改写）
> 
> 你可以换个思路，毕竟 PBH 是支持远程连接的。 你可以把它放在比如台式、NAS、树莓派、或者废旧手机上。

QS，但个人感觉BTH作为监控软件，放在同为（流量）监控角色的路由器中更好（实际上只是纯粹路由性能过剩，需要利用罢了😂）

**Comment by happilying** [comment]
> > > > > > > 似乎并没有找到邮件推送（如果是我眼睛瞎了我道歉）🧐
> > > > > > 
> > > > > > 
> > > > > > 邮件推送没赶上版本，相关 API 还没到位，所以暂时确实需要通过配置文件修改。
> > > > > > @Gaojianli 能不能来个无菜单仅路由的直接编辑功能
> > > > > 
> > > > > 
> > > > > 不给，改出问题了咋办
> > > > 
> > > > 
> > > > 出问题自负呗，就像手机开发者选项似的，可以隐藏的很深并且大屏警告但不能没有，但搞崩手机厂商不负责（😂
> > > 
> > > 
> > > 想法很美好，现实通常是：
> > > 
> > > * [x]    安装为系统服务 （如果你不清楚这是什么，请不要勾选！）
> > > 
> > > “群主为什么 PBH 起不来，提示端口占用？”
> > 
> > 
> > 这个放的太明显确实没法（天朝是这样的，我也经常前脚刚发完后脚立刻看到注释，但无法撤回......😂），可以作为远期规划或内部调试使用
> 
> 我很希望开放大量内部或者高级操作，但现实证明只要你敢放，就一定有人头铁闭眼冲——哪怕会造成不可挽回的后果。 编辑文件似乎也不是那么繁琐，对于邮件配置来说，你只需要配置一次，而且未来显然也迟早会加入 WebUI，只是时间问题，API 还需要更多的时间去调整。

感觉可以开放给plus用，顺便允许plus内测些功能（应该不会有人氪这种金还小白操作吧，虽然不知道会不会有人拿这个大做文章就是了🧐

**Comment by Gaojianli** [comment]
> > > > > > > > 似乎并没有找到邮件推送（如果是我眼睛瞎了我道歉）🧐
> > > > > > > 
> > > > > > > 
> > > > > > > 邮件推送没赶上版本，相关 API 还没到位，所以暂时确实需要通过配置文件修改。
> > > > > > > @Gaojianli 能不能来个无菜单仅路由的直接编辑功能
> > > > > > 
> > > > > > 
> > > > > > 不给，改出问题了咋办
> > > > > 
> > > > > 
> > > > > 出问题自负呗，就像手机开发者选项似的，可以隐藏的很深并且大屏警告但不能没有，但搞崩手机厂商不负责（😂
> > > > 
> > > > 
> > > > 想法很美好，现实通常是：
> > > > 
> > > > * [x]     安装为系统服务 （如果你不清楚这是什么，请不要勾选！）
> > > > 
> > > > “群主为什么 PBH 起不来，提示端口占用？”
> > > 
> > > 
> > > 这个放的太明显确实没法（天朝是这样的，我也经常前脚刚发完后脚立刻看到注释，但无法撤回......😂），可以作为远期规划或内部调试使用
> > 
> > 
> > 我很希望开放大量内部或者高级操作，但现实证明只要你敢放，就一定有人头铁闭眼冲——哪怕会造成不可挽回的后果。 编辑文件似乎也不是那么繁琐，对于邮件配置来说，你只需要配置一次，而且未来显然也迟早会加入 WebUI，只是时间问题，API 还需要更多的时间去调整。
> 
> 感觉可以开放给plus用，顺便允许plus内测些功能（应该不会有人氪这种金还小白操作吧，虽然不知道会不会有人拿这个大做文章就是了🧐

主要问题是配置文件是yaml，编辑太容易出问题，还没有校验功能

**Comment by happilying** [comment]
QS，可以日后想办法逐渐迁移为更安全的配置文件格式（一旦配置项多起来就不好办喽🧐）

**Comment by Gaojianli** [comment]
> QS，可以日后想办法逐渐迁移为更安全的配置文件格式（一旦配置项多起来就不好办喽🧐）

我说了一万遍迁移到json，但是有人觉得yaml可读写更好更不容易写坏

**Comment by happilying** [comment]
> > QS，可以日后想办法逐渐迁移为更安全的配置文件格式（一旦配置项多起来就不好办喽🧐）
> 
> 我说了一万遍迁移到json，但是有人觉得yaml可读写更好更不容易写坏

从Web来说json更好，从程序角度来说yaml更好，也不能说谁好谁坏，只是针对不同需求罢了，如果PBH核心是Web实现（electron是吧）的话那改json也不会有人说什么了😂

**Comment by Ghost-chu** [comment]
暂不考虑此 FR
