### ISSUE TITLE
写了个多拨检测模块，但是持久化不太会写，请问能否接手？

### ISSUE THREAD

**Issue by CharlesChou73** [PBH-BTN/PeerBanHelper#69]
有一组青岛ip是同时下载一个种子，但是每个都正常报告进度，估计是有比较复杂的检测对抗逻辑。

针对这种情况开发了一个基于多拨检测的封禁模块（同一网段集中下载同一个种子视为多拨，因为多拨和PCDN强相关所以可以直接封禁），主要逻辑和配置都写好了，但是不熟悉SQLite所以持久化的部分只写了一半，怕写出bug，能否请老兄接手检查补充，做成完整的模块？

**Comment by Ghost-chu** [comment]
没必要进行持久化，内存缓存就够了

**Comment by CharlesChou73** [comment]
好的那我删一下持久化逻辑提pr
