### ISSUE TITLE
[Other] 新的放血策略？

### ISSUE THREAD

**Issue by 1391189216** [PBH-BTN/PeerBanHelper#697]
### 问题描述 - Issue Description

![image](https://github.com/user-attachments/assets/037ec79c-8d3c-4761-81f7-6555c1e8745c)
全都是下载到99.5%就不动了，然后我亲眼盯着240e**6cd5这个从85%下载到99.5%就停了，并且pbh也没有封禁，我怀疑这是一种新型的放血方式，这进度就很可疑，明显是机器设定好的脚本，不然不可能这么齐刷刷的到99.5%就停了。

咱也不懂，感觉有问题，反馈给大佬看看。

**Comment by Ghost-chu** [comment]
感谢您的报告，由于今天时间已较晚，相关调查工作会从明天开始。

**Comment by 1391189216** [comment]
> 果然，过了一会又使用了新的ip继续下载，同样下载到99.5%就停止了，如此循环往复。

![image](https://github.com/user-attachments/assets/29297ca8-cd51-441e-9da8-0161cc37b5f8)
我亲眼看到这个 ip 99%的时候，我这里都没有下载速度了，进度却一直再跑，当跑到99.8%的时候又突然跳回99.5%，然后又不动了。

**Comment by Ghost-chu** [comment]
> 果然，过了一会又使用了新的ip继续下载，同样下载到99.5%就停止了，如此循环往复。

在我们开始调查之前，请问您是否可以尝试检验一下种子文件完整性，看看有没有可能是本地文件出现了问题？不管如何我们明天都会检查服务器上的数据看看是否有异常情况。

**Comment by 1391189216** [comment]
> > 果然，过了一会又使用了新的ip继续下载，同样下载到99.5%就停止了，如此循环往复。
> 
> 在我们开始调查之前，请问您是否可以尝试检验一下种子文件完整性，看看有没有可能是本地文件出现了问题？不管如何我们明天都会检查服务器上的数据看看是否有异常情况。

重新校验了一次，文件完整。

**Comment by 1391189216** [comment]
> > 果然，过了一会又使用了新的ip继续下载，同样下载到99.5%就停止了，如此循环往复。
> 
> 在我们开始调查之前，请问您是否可以尝试检验一下种子文件完整性，看看有没有可能是本地文件出现了问题？不管如何我们明天都会检查服务器上的数据看看是否有异常情况。

magnet:?xt=urn:btih:CTQ22E534N7RD5EP6JUYQK4ELNX7TVP3&dn=MIDV-850-UC&tr=http%3A%2F%2F1337.abcvg.info%2Fannounce&tr=http%3A%2F%2Ffxtt.ru%2Fannounce&tr=http%3A%2F%2Fi-p-v-6.tk%3A6969%2Fannounce&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=http%3A%2F%2Fopen-v6.demonoid.ch%3A6969%2Fannounce&tr=http%3A%2F%2Fopen.acgnxtracker.com%2Fannounce&tr=http%3A%2F%2Fopen.tracker.ink%3A6969%2Fannounce&tr=http%3A%2F%2Ft.acg.rip%3A6699%2Fannounce&tr=http%3A%2F%2Ft.overflow.biz%3A6969%2Fannounce&tr=http%3A%2F%2Ftorrentsmd.com%3A8080%2Fannounce&tr=http%3A%2F%2Ftracker.bt4g.com%3A2095%2Fannounce&tr=http%3A%2F%2Ftracker.electro-torrent.pl%2Fannounce&tr=http%3A%2F%2Ftracker.files.fm%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.gbitt.info%2Fannounce&tr=http%3A%2F%2Ftracker.ipv6tracker.ru%2Fannounce&tr=http%3A%2F%2Ftrackme.theom.nz%2Fannounce&tr=http%3A%2F%2Fvps02.net.orel.ru%2Fannounce&tr=http%3A%2F%2Fwww.all4nothin.net%2Fannounce.php&tr=http%3A%2F%2Fwww.wareztorrent.com%2Fannounce&tr=https%3A%2F%2F1337.abcvg.info%2Fannounce&tr=https%3A%2F%2Fopentracker.i2p.rocks%2Fannounce&tr=https%3A%2F%2Ft1.hloli.org%2Fannounce&tr=https%3A%2F%2Ftr.abiir.top%2Fannounce&tr=https%3A%2F%2Ftr.abir.ga%2Fannounce&tr=https%3A%2F%2Ftr.burnabyhighstar.com%2Fannounce&tr=https%3A%2F%2Ftr.fuckbitcoin.xyz%2Fannounce&tr=https%3A%2F%2Ftracker.cyber-hub.net%2Fannounce&tr=https%3A%2F%2Ftracker.foreverpirates.co%2Fannounce&tr=https%3A%2F%2Ftracker.gbitt.info%2Fannounce&tr=https%3A%2F%2Ftracker.kuroy.me%2Fannounce&tr=https%3A%2F%2Ftracker.lilithraws.cf%2Fannounce&tr=https%3A%2F%2Ftracker.lilithraws.org%2Fannounce&tr=https%3A%2F%2Ftracker.loligirl.cn%2Fannounce&tr=https%3A%2F%2Ftracker.m-team.cc%2Fannounce.php&tr=https%3A%2F%2Ftracker.nanoha.org%2Fannounce&tr=https%3A%2F%2Ftracker.tamersunion.org%2Fannounce&tr=https%3A%2F%2Ftracker1.520.jp%2Fannounce&tr=https%3A%2F%2Ftrackme.theom.nz%2Fannounce&tr=http%3A%2F%2Fsukebei.tracker.wf%3A8888%2Fannounce&tr=https%3A%2F%2Fsparkle.ghostchu-services.top%2Ftracker%2Fannounce&tr=http%3A%2F%2F%5B2a04%3Aac00%3A1%3A3dd8%3A%3A1%3A2710%5D%3A2710%2Fannounce&tr=http%3A%2F%2Fbittorrent-tracker.e-n-c-r-y-p-t.net%3A1337%2Fannounce&tr=http%3A%2F%2Fbt.okmp3.ru%3A2710%2Fannounce&tr=http%3A%2F%2Fbvarf.tracker.sh%3A2086%2Fannounce&tr=http%3A%2F%2Fcanardscitrons.nohost.me%3A6969%2Fannounce&tr=http%3A%2F%2Fipv4announce.sktorrent.eu%3A6969%2Fannounce&tr=http%3A%2F%2Fipv6.rer.lol%3A6969%2Fannounce&tr=http%3A%2F%2Fpublic.tracker.vraphim.com%3A6969%2Fannounce&tr=http%3A%2F%2Fretracker.hotplug.ru%3A2710%2Fannounce&tr=http%3A%2F%2Fsaltwood.top%3A6969%2Fannounce&tr=http%3A%2F%2Ftaciturn-shadow.spb.ru%3A6969%2Fannounce&tr=http%3A%2F%2Ftk.greedland.net%2Fannounce&tr=http%3A%2F%2Ftr.kxmp.cf%2Fannounce&tr=http%3A%2F%2Ftr1.aag.moe%3A2095%2Fannounce&tr=http%3A%2F%2Ftracker-zhuqiy.dgj055.icu%2Fannounce&tr=http%3A%2F%2Ftracker.dler.com%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.edkj.club%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.ipv6tracker.org%2Fannounce&tr=http%3A%2F%2Ftracker.mywaifu.best%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.peckservers.com%3A9000%2Fannounce&tr=http%3A%2F%2Ftracker.qu.ax%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.renfei.net%3A8080%2Fannounce&tr=http%3A%2F%2Ftracker.vraphim.com%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.waaa.moe%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker1.bt.moack.co.kr%2Fannounce&tr=http%3A%2F%2Ftracker2.itzmx.com%3A6961%2Fannounce&tr=http%3A%2F%2Ftracker3.itzmx.com%3A6961%2Fannounce&tr=http%3A%2F%2Ftracker4.itzmx.com%3A2710%2Fannounce&tr=http%3A%2F%2Fwww.peckservers.com%3A9000%2Fannounce&tr=https%3A%2F%2Fp2p.azu.red%2Fannounce&tr=https%3A%2F%2Fsparkle.ghostchu-services.top%2Fannounce&tr=https%3A%2F%2Ftracker-zhuqiy.dgj055.icu%2Fannounce&tr=https%3A%2F%2Ftracker.cloudit.top%2Fannounce&tr=https%3A%2F%2Ftracker.gcrenwp.top%2Fannounce&tr=https%3A%2F%2Ftracker.ipfsscan.io%2Fannounce&tr=https%3A%2F%2Ftracker.itscraftsoftware.my.id%2Fannounce&tr=https%3A%2F%2Ftracker.pmman.tech%2Fannounce&tr=https%3A%2F%2Ftracker.yemekyedim.com%2Fannounce&tr=https%3A%2F%2Ftrackers.mlsub.net%2Fannounce&tr=https%3A%2F%2Fwww.peckservers.com%3A9443%2Fannounce&tr=udp%3A%2F%2F1c.premierzal.ru%3A6969%2Fannounce&tr=udp%3A%2F%2F207.241.226.111%3A6969%2Fannounce&tr=udp%3A%2F%2F207.241.231.226%3A6969%2Fannounce&tr=udp%3A%2F%2F52.58.128.163%3A6969%2Fannounce&tr=udp%3A%2F%2F%5B2a03%3A7220%3A8083%3Acd00%3A%3A1%5D%3A451%2Fannounce&tr=udp%3A%2F%2F%5B2a04%3Aac00%3A1%3A3dd8%3A%3A1%3A2710%5D%3A2710%2Fannounce&tr=udp%3A%2F%2F%5B2a0f%3Ae586%3Af%3Af%3A%3A81%5D%3A6969%2Fannounce&tr=udp%3A%2F%2Faegir.sexy%3A6969%2Fannounce&tr=udp%3A%2F%2Famigacity.xyz%3A6969%2Fannounce&tr=udp%3A%2F%2Fapi.clasificadosrapidos.com%3A53%2Fannounce&tr=udp%3A%2F%2Fbandito.byterunner.io%3A6969%2Fannounce&tr=udp%3A%2F%2Fbittorrent-tracker.e-n-c-r-y-p-t.net%3A1337%2Fannounce&tr=udp%3A%2F%2Fbt.ktrackers.com%3A6666%2Fannounce&tr=udp%3A%2F%2Fconcen.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fd40969.acod.regrucolo.ru%3A6969%2Fannounce&tr=udp%3A%2F%2Fec2-18-191-163-220.us-east-2.compute.amazonaws.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fevan.im%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fipv4.rer.lol%3A2710%2Fannounce&tr=udp%3A%2F%2Fisk.richardsw.club%3A6969%2Fannounce&tr=udp%3A%2F%2Fismaarino.com%3A1234%2Fannounce&tr=udp%3A%2F%2Fjutone.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fleet-tracker.moe%3A1337%2Fannounce&tr=udp%3A%2F%2Fmartin-gebhardt.eu%3A25%2Fannounce&tr=udp%3A%2F%2Fmoonburrow.club%3A6969%2Fannounce&tr=udp%3A%2F%2Fns1.monolithindustries.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fodd-hd.fr%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.dstud.io%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.free-tracker.ga%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.tracker.cl%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.tracker.ink%3A6969%2Fannounce&tr=udp%3A%2F%2Fopentor.org%3A2710%2Fannounce&tr=udp%3A%2F%2Fopentracker.io%3A6969%2Fannounce&tr=udp%3A%2F%2Fp2p.publictracker.xyz%3A6969%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Fpublic.tracker.vraphim.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fretracker.hotplug.ru%3A2710%2Fannounce&tr=udp%3A%2F%2Fretracker.lanta.me%3A2710%2Fannounce&tr=udp%3A%2F%2Fretracker01-msk-virt.corbina.net%3A80%2Fannounce&tr=udp%3A%2F%2Frun.publictracker.xyz%3A6969%2Fannounce&tr=udp%3A%2F%2Fryjer.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fseedpeer.net%3A6969%2Fannounce&tr=udp%3A%2F%2Fserpb.vpsburti.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftk2v6.trackerservers.com%3A8080%2Fannounce&tr=udp%3A%2F%2Ftorrents.artixlinux.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftr4ck3r.duckdns.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftrackarr.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.0x7c0.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.auctor.tv%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.birkenwald.de%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.bittor.pw%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.breizh.pm%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.ccp.ovh%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.darkness.services%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.ddunlimited.net%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.deadorbit.nl%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.dler.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.dump.cl%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.edkj.club%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.filemail.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.fnix.net%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.gigantino.net%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.gmi.gd%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.jamesthebard.net%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.qu.ax%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.skyts.net%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.srv00.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.theoks.net%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.tryhackx.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker1.myporn.club%3A9337%2Fannounce&tr=udp%3A%2F%2Ftracker2.dler.org%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker2.itzmx.com%3A6961%2Fannounce&tr=udp%3A%2F%2Ftracker3.itzmx.com%3A6961%2Fannounce&tr=udp%3A%2F%2Ftracker4.itzmx.com%3A2710%2Fannounce&tr=udp%3A%2F%2Fttk2.nbaonlineservice.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fu4.trakx.crim.ist%3A1337%2Fannounce&tr=udp%3A%2F%2Fwww.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fz.mercax.com%3A53%2Fannounce&tr=wss%3A%2F%2Ftracker.openwebtorrent.com%3A443%2Fannounce&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker-udp.gbitt.info%3A80%2Fannounce&tr=http%3A%2F%2Ftracker2.dler.org%2Fannounce&tr=http%3A%2F%2Fopen.acgtracker.com%3A1096%2Fannounce&tr=http%3A%2F%2Ftracker1.itzmx.com%3A8080%2Fannounce&tr=http%3A%2F%2Fch3oh.ru%3A6969%2Fannounce&tr=http%3A%2F%2Fwepzone.net%3A6969%2Fannounce&tr=https%3A%2F%2Ftracker.leechshield.link%2Fannounce&tr=udp%3A%2F%2Fopen.u-p.pw%3A6969%2Fannounce&tr=udp%3A%2F%2Ft.overflow.biz%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.skynetcloud.site%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker4.leechshield.link%3A6969%2Fannounce&tr=udp%3A%2F%2Fwepzone.net%3A6969%2Fannounce&tr=http%3A%2F%2F0123456789nonexistent.com%2Fannounce&tr=http%3A%2F%2F0d.kebhana.mx%3A443%2Fannounce&tr=http%3A%2F%2Ffinbytes.org%2Fannounce.php&tr=http%3A%2F%2Ffleira.no%3A6969%2Fannounce&tr=http%3A%2F%2Fftp.pet%3A6969%2Fannounce&tr=http%3A%2F%2Fhighteahop.top%3A6960%2Fannounce&tr=http%3A%2F%2Fhome.yxgz.club%3A6969%2Fannounce&tr=http%3A%2F%2Fopen.tracker.cl%3A1337%2Fannounce&tr=http%3A%2F%2Fopen.trackerlist.xyz%2Fannounce&tr=http%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=http%3A%2F%2Fretracker.spark-rostov.ru%2Fannounce&tr=http%3A%2F%2Frfc5746.mywaifu.best%3A6969%2Fannounce&tr=http%3A%2F%2Fseeders-paradise.org%2Fannounce&tr=http%3A%2F%2Fservandroidkino.ru%2Fannounce&tr=http%3A%2F%2Fshare.hkg-fansub.info%2Fannounce.php&tr=http%3A%2F%2Fshubt.net%3A2710%2Fannounce&tr=http%3A%2F%2Fsmurfsoft.com%3A6969%2Fannounce&tr=http%3A%2F%2Ftr.nyacat.pw%2Fannounce&tr=http%3A%2F%2Ftracker.bittor.pw%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.bt-hash.com%2Fannounce&tr=http%3A%2F%2Ftracker.bz%2Fannounce&tr=http%3A%2F%2Ftracker.corpscorp.online%2Fannounce&tr=http%3A%2F%2Ftracker.dmcomic.org%3A2710%2Fannounce&tr=http%3A%2F%2Ftracker.lintk.me%3A2710%2Fannounce&tr=http%3A%2F%2Ftracker.moxing.party%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.sbsub.com%3A2710%2Fannounce&tr=http%3A%2F%2Ftracker.srv00.com%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.vanitycore.co%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.xiaoduola.xyz%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker810.xyz%3A11450%2Fannounce&tr=http%3A%2F%2Fwww.genesis-sp.org%3A2710%2Fannounce&tr=https%3A%2F%2Fapi.ipv4online.uk%2Fannounce&tr=https%3A%2F%2Ftr.nyacat.pw%2Fannounce&tr=https%3A%2F%2Ftracker.bt4g.com%2Fannounce&tr=udp%3A%2F%2Fcanardscitrons.nohost.me%3A6969%2Fannounce&tr=udp%3A%2F%2Fdiscord.heihachi.pw%3A6969%2Fannounce&tr=udp%3A%2F%2Fns-1.x-fins.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.ololosh.space%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrust-demo.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker1.bt.moack.co.kr%3A80%2Fannounce&tr=http%3A%2F%2Fwww.torrentsnipe.info%3A2701%2Fannounce&tr=http%3A%2F%2Ft.jaekr.sh%3A6969%2Fannounce&tr=http%3A%2F%2Fbuny.uk%3A6969%2Fannounce&tr=http%3A%2F%2Fbt1.xxxxbt.cc%3A6969%2Fannounce&tr=http%3A%2F%2Fbt.poletracker.org%3A2710%2Fannounce&tr=udp%3A%2F%2Fd13bttrck.duckdns.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker-us.silksa.co.za%3A6969%2Fannounce&tr=http%3A%2F%2Fkiryuu-test.mywaifu.best%3A6969%2Fannounce&tr=udp%3A%2F%2Ffreedomalternative.com%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.beeimg.com%3A6969%2Fannounce&tr=https%3A%2F%2Ftracker.uraniumhexafluori.de%2Fannounce&tr=udp%3A%2F%2Ftk4.leechshield.link%3A6969%2Fannounce&tr=udp%3A%2F%2Fu6.trakx.crim.ist%3A1337%2Fannounce&xl=9530913393
出问题的磁力链接。

**Comment by Ghost-chu** [comment]
请勿在github上公开发布哈希值 链接 或种子文件。

**Comment by 1391189216** [comment]
> 请勿在github上公开发布哈希值 链接 或种子文件。

好的，我马上删除

**Comment by cjjdaq** [comment]
有没有可能在创建种子的时候没有块对齐，导致卡99%的情况

**Comment by 1391189216** [comment]
> 有没有可能在创建种子的时候没有块对齐，导致卡99%的情况

感觉不太可能，我不止一个种子出现这种情况

**Comment by cjjdaq** [comment]
如果你是初始种子，建议你使用别的工具创建试试。曾经我也遇到过自己创建的种子，个人种子别人只能下载到99%的情况。

**Comment by Ghost-chu** [comment]
请问一下您的 IP 是？

**Comment by 1391189216** [comment]
> 请问一下您的 IP 是？

BitComet使用的是临时ipv6吗？
这是我的临时ipv6：2409:8a6a:5032:7df0:8c80:5273:ee1e:95cb

**Comment by Ghost-chu** [comment]
> > 请问一下您的 IP 是？
> 
> BitComet使用的是临时ipv6吗？ 这是我的临时ipv6：2409:8a6a:5032:7df0:8c80:5273:ee1e:95cb

能看到我吗：

   临时 IPv6 地址. . . . . . . . . . : 2408:8214:2e10:a61:2983:7917:4ca1:2bf5
   临时 IPv6 地址. . . . . . . . . . : 2408:8214:2e10:a61:44a2:e1e6:f997:d0b0
   临时 IPv6 地址. . . . . . . . . . : 2408:8214:2e10:a61:703c:8d3b:4e08:608c
   临时 IPv6 地址. . . . . . . . . . : 2408:8214:2e10:a61:dd3c:f377:3b19:3945
   临时 IPv6 地址. . . . . . . . . . : 2408:8214:2e10:a61:f14b:59a3:1def:7e00

  IPV4 是 221.214.138.183

**Comment by Ghost-chu** [comment]
> > 我大概搞清楚了，现在我也是 99.5%
> > ![image](https://private-user-images.githubusercontent.com/30802565/383645922-3da8cfee-1e21-4893-887e-5c11f1fd13bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MTE1MzgsIm5iZiI6MTczMDkxMTIzOCwicGF0aCI6Ii8zMDgwMjU2NS8zODM2NDU5MjItM2RhOGNmZWUtMWUyMS00ODkzLTg4N2UtNWMxMWYxZmQxM2JiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDE2NDAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1OGEyZmFiYjg1YmQ5OWU5NDI3NTRhYzU2OTI2NjcyMWE1OWYwYzI5M2NkMzUwYzBiNmFmMGIwYmJiNjA4MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uxSVDOkz4frA_f7C-mT_uQqMuAqrVwW9Zhr7uq6LIUQ)
> > 事情是这样的，你的种子文件包含：
> > 
> > * *****.mp4 (8.84GB)
> > * *****.html (145B)
> > * *****.mp4 (14.3MB)
> > * *****.mp4 (22.7MB)
> > * *****.txt (126B)
> > 
> > 当我只选择下载 8.84GB 的文件之后，我从 BitComet 看我自己的进度就是 99.5%。 至于你为什么看到了进度回退，那大概是因为下载者把那几个垃圾文件取消勾选了。
> 
> 这个只是qb的问题吗？ ![image](https://private-user-images.githubusercontent.com/45230319/383648541-d0ec932f-88cf-4046-a2f1-0f929752bf51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MTE4OTAsIm5iZiI6MTczMDkxMTU5MCwicGF0aCI6Ii80NTIzMDMxOS8zODM2NDg1NDEtZDBlYzkzMmYtODhjZi00MDQ2LWEyZjEtMGY5Mjk3NTJiZjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDE2NDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMjVmZTZjZWJkNzZjYzk4YjBmNWJjZjMzZmVhMzIzZmFiYWM3NTI4NDJjM2NmYjA2M2Y1YWMyOTI4YWUyOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.44AIJgu-mIryJi0b3Sg0xctPZB85iaseAld3EAvxCn4) bitcomet无论我选择多少文件，当我选择的文件下载完之后就会显示100%，并且进入做种状态，如果是这样的话，那是不是意味着qb不选择所有文件的话永远不会进入做种状态呢？也就是说qb不选择所有文件的话，永远都会处于下载状态吗？

你要在没有开始下载时取消选择，或者下载完后取消选择、删除本地文件、然后重新校验。
