### ISSUE TITLE
[Other] 声明中对用户行为的要求违反GPL以及自由之零

### ISSUE THREAD

**Issue by ika-twb** [PBH-BTN/PeerBanHelper#758]
### 问题描述 - Issue Description

> 严禁使用 PBH-BTN 团队的任何服务、**产品** 从事任何违法违规、危害国家安全、实施或帮助他人实施电信犯罪等非法活动。
> 用户不得通过 PBH-BTN 团队的任何服务、**产品** 进行任何损害其它个人或组织的利益的活动。

我支持 PBH-BTN 对此类违法犯罪活动的反对立场, 但这种对用户使用软件用途的限制违反了 [开源定义](https://opensource.org/osd), [自由软件定义](https://www.gnu.org/philosophy/free-sw.html#fs-definition) 以及该仓库使用的 [GPL协议](https://www.gnu.org/licenses/gpl-3.0.html).

建议:

1. 在声明中将 "产品" 去除, 开发者有权不对某些用户/组织提供服务, 但对用户如何使用软件的限制违反了自由与开源软件精神以及GPL协议.
2. 或将该仓库使用的 GPL 协议改为其他形式的非自由许可证, 否则软件及其代码将无法受到任何保护.

参考: [Richard Stallman - 软件为什么不能限制运行的自由 (gnu.org)](https://www.gnu.org/philosophy/programs-must-not-limit-freedom-to-run.html)

### 检查清单 - Check list

- [X] 这不是一个错误 （BUG） (This is not an bug/error)
- [X] PeerBanHelper 已更新到最新版本，非最新版本不接受任何错误反馈，任何非最新版本的 Issue 将被 立 刻 关 闭，不会有人给您提供任何支持 (I'm running the latest version of PBH that can be found in Github Relases, non-latest release won't receive any support)
- [X] 我已检查过 [PBH 文档](https://docs.pbh-btn.com/)（特别是常见问题），且即使使用了搜索也没有找到与此有关的内容 (This not a question/or the question that not listed in README's FAQ or [PBH WIKI](https://docs.pbh-btn.com/))
- [x] 我同意遵守 PBH-BTN 包容性条约，不发布 “嘲讽、骂战、引战、开盒（有时也称为人肉搜索）、人身攻击、仇恨、暴力、侮辱性言辞、违法违规、黑灰产、危害国家安全、实施或帮助他人实施电信犯罪” 等内容。并已知晓如果仍旧发布了这些内容，我的账号将立刻从包括但不限于 PBH-BTN 组织、社交软件中封禁。所有主题、内容都将被立刻删除或折叠，撤销、删除和收回您所做出的一切贡献，并封禁 BTN 网络的中账号权限、排除您所提交的所有数据。在您违反相关规则时，PBH-BTN 将会将您的注册、登录、和最近访问的 IP 地址、电子邮件地址、以及其它可能追踪您或将您去匿名化的信息从定期删除转为永不删除，并在任何国家或地区的政府、公安机关或有关部门需要时无通知的提供这些数据。 (I agree to abide by the PBH-BTN Inclusivity Pact by not posting content such as “taunting, name-calling, war-mongering, open-boxing (sometimes referred to as mansplaining), personal attacks, hatred, violence, insulting language, illegal activities, black and grey business, endangering national security, and committing or assisting others in committing telecommunication crimes”. I am aware that if I continue to post such content, my account will be immediately banned from organizations including but not limited to PBH-BTN, social software. All topics and content will be immediately deleted or collapsed, all contributions will be revoked, deleted and retracted, and you will be banned from the BTN network and all data you have submitted will be excluded. In the event of a violation of these rules, PBH-BTN will delete your registration, login, and most recent IP address, email address, and any other information that may be used to track you or de-anonymize you from regular to permanent deletion, and will make this data available to the government, public security, or other relevant authorities without notice if they request it, no matter what country or region.)

**Comment by Ghost-chu** [comment]
对于任何用途下，我们首先采用 GPLv3 许可证进行授权，且遵循 GPLv3 中所述的包括但不限于修改、破解、安装、使用和重新分发的有关权利条款。  
但这一切的前提是您即将做出的行为不能危害开发者的人身安全或人身自由，否则您将直接违反许可条款，所带来的法律后果由您自行承担。

在中国大陆的法律管辖区内，我们首先遵循中国大陆的相关法律法规以及行政文件，其次是尽最大的自由和可能使用 GPLv3 许可证授权程序源代码。您不能阻止我们遵循相关法律法规或者行政文件，除非您认为 FSF&GNU （或者您自己）能够免去或者完全承担我们在违反中国大陆的相关法律法规以及行政文件的情况下需要承担的法律后果。

**Comment by zypA13510** [comment]
@Ghost-chu 
1. GPLv3许可协议的协议文本本身是受版权保护的，这点在您引用的许可协议的开头已做明确解释。注意最后一节加粗部分的内容：
    
    >  Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>
    >  Everyone is permitted to copy and distribute verbatim copies
    >  of this license document, **but changing it is not allowed.**
    
    在GPLv3协议文本之上额外附加条款限制这个行为已经构成了对协议的修改。那么您使用GNU GPLv3协议文本的行为已经违反了GPLv3协议本身，构成侵权。您可以自由决定是否使用GNU GPLv3协议授权您的劳动成果，但您不能借用GPLv3的文本（及名义）并在其上增加任何形式的额外条款，这正是上述第一段的存在意义。
2. 开源软件是面向世界的，您的软件如果“开源”，就不可能限制仅中国大陆地区用户使用。中国大陆地区法律对于其他地区的使用者并无管辖权，使用者并不一定有遵守中国大陆地区法律的义务，但您的项目之授权许可对所有使用者具有同样的强制性。如果使用任何一个开源软件，就需要阅读并遵守其所有共同开发者所在诸国的所有法律，那么开源将不复存在。
3. 本人不是律师，我无法就您开发的软件之使用是否违反中国大陆地区法律法规做出解释或解读。但至少以我的理解，确保您不是为从事违法活动而开发软件是开发者的责任；确保软件不以违法用途使用是使用者的责任。法律所默认的部分，不需要以额外条款约束，但什么是法律所默认的，这应该是对具体使用情况具有管辖权的司法机构决定的事情。如果您的理解中，中国大陆地区法律法规要求您有约束限制软件的所有使用者的义务，那GNU GPLv3授权许可协议可能不适合您。

以上，可能本人语气比较严肃，并不是对您有任何恶意，希望您理解。但法律本身是一个严肃的话题，既然决定给项目增加一个开源授权许可，那应该严肃地遵循许可的内容（和精神）。如果您不在乎是否遵循开源精神，您大可不必专门加个开源协议，默认保留所有权利或者专门编写自己的授权许可也是可以的。我相信ika-twb提出这个issue的初衷应该也是这样的，您不能挂羊头卖狗肉，不能挂着GNU GPLv3之名行违反开源精神之实。

**Comment by Ghost-chu** [comment]
> [@Ghost-chu](https://github.com/Ghost-chu)
> 
> 1. GPLv3许可协议的协议文本本身是受版权保护的，这点在您引用的许可协议的开头已做明确解释。注意最后一节加粗部分的内容：
>    > Copyright (C) 2007 Free Software Foundation, Inc. https://fsf.org/
>    > Everyone is permitted to copy and distribute verbatim copies
>    > of this license document, **but changing it is not allowed.**
>    
>    
>    在GPLv3协议文本之上额外附加条款限制这个行为已经构成了对协议的修改。那么您使用GNU GPLv3协议文本的行为已经违反了GPLv3协议本身，构成侵权。您可以自由决定是否使用GNU GPLv3协议授权您的劳动成果，但您不能借用GPLv3的文本（及名义）并在其上增加任何形式的额外条款，这正是上述第一段的存在意义。
> 2. 开源软件是面向世界的，您的软件如果“开源”，就不可能限制仅中国大陆地区用户使用。中国大陆地区法律对于其他地区的使用者并无管辖权，使用者并不一定有遵守中国大陆地区法律的义务，但您的项目之授权许可对所有使用者具有同样的强制性。如果使用任何一个开源软件，就需要阅读并遵守其所有共同开发者所在诸国的所有法律，那么开源将不复存在。
> 3. 本人不是律师，我无法就您开发的软件之使用是否违反中国大陆地区法律法规做出解释或解读。但至少以我的理解，确保您不是为从事违法活动而开发软件是开发者的责任；确保软件不以违法用途使用是使用者的责任。法律所默认的部分，不需要以额外条款约束，但什么是法律所默认的，这应该是对具体使用情况具有管辖权的司法机构决定的事情。如果您的理解中，中国大陆地区法律法规要求您有约束限制软件的所有使用者的义务，那GNU GPLv3授权许可协议可能不适合您。
> 
> 另外讨论一下您这段回复：
> 
> > 在中国大陆的法律管辖区内，我们首先遵循中国大陆的相关法律法规以及行政文件
> > 您不能阻止我们遵循相关法律法规或者行政文件
> 
> 是的，但请您注意您说这句话的主体，您讲到“我们”需要遵守，GPLv3也并不阻止您去遵守。GPLv3阻止您**强制所有用户去遵守**。而用户角度，一个受中国大陆法律管辖的用户他本来就具有遵守法律的义务，义务来源并不是来自您的许可约束；一个本不受中国大陆法律管辖的用户不需要受额外的限制管辖，这是开源之自由精神。
> 
> > 除非您认为 FSF&GNU （或者您自己）能够免去或者完全承担我们在违反中国大陆的相关法律法规以及行政文件的情况下需要承担的法律后果
> 
> 不论FSF/GNU是否能为您的具体情况提供法律支持，依据GPLv3协议去授权您的软件是您使用GPLv3协议文本的前提。如果您认为FSF/GNU的许可协议无法给您提供足够的保护，您可以不用。您不可以说“我偏要用GPLv3但是GPLv3又阻止我遵守国家法律法规了所以我要在其基础上做修改”，您没有修改它的权利。
> 
> 以上，可能本人语气比较严肃，并不是对您有任何恶意，希望您理解。但法律本身是一个严肃的话题，既然决定给项目增加一个开源授权许可，那应该严肃地遵循许可的内容（和精神）。如果您不在乎是否遵循开源精神，您大可不必专门加个开源协议，默认保留所有权利或者专门编写自己的授权许可也是可以的。我相信ika-twb提出这个issue的初衷应该也是这样的，您不能挂羊头卖狗肉，不能挂着GNU GPLv3之名行违反开源精神之实。

对于任何用途下，我们首先采用 GPLv3 许可证进行授权，且遵循 GPLv3 中所述的包括但不限于修改、破解、安装、使用和重新分发的有关权利条款。
**但这一切的前提是您即将做出的行为不能危害开发者的人身安全或人身自由，否则您将直接违反许可条款，所带来的法律后果由您自行承担。**

在中国大陆的法律管辖区内，**我们**首先遵循中国大陆的相关法律法规以及行政文件，其次是尽最大的自由和可能使用 GPLv3 许可证授权程序源代码。**您不能阻止*我们*遵循相关法律法规或者行政文件，除非您认为 FSF&GNU （或者您自己）能够免去或者完全承担我们在违反中国大陆的相关法律法规以及行政文件的情况下需要承担的法律后果。**

---

https://github.com/TC999/Aria-bak

请开源警察高抬贵手。

我不明白一个免责条款是怎么让你们如此热衷于发如此长文出警的。它存在的意义仅仅是有人使用我们的仓库和代码违法时，公安找上门我们有免责条款可以规避风险。至于你们爱用它干什么我完全管不到也根本无法阻止，我甚至根本不会知道你们私下拿去做了什么设计用途之外的事。

作为 Team Leader 我有义务和责任保护参与此项目的团队成员和其他贡献者最起码的人身安全，这不是空穴来风。你们总认为有个开源协议就完事大吉，图样图森破，在中国法律没有明文认可开源协议中的所有条款之前，所谓的开源条款仅仅是道德层面的约束，它在中国根本没有任何保护采用相关开源条款的人的现实能力，在执法中也不会因为GPL里某个条款就让你免于刑罚。

是FSF&GNU会代替我们坐牢，还是FSF&GNU能代替我们打官司？我看真进了监狱就算喊破喉咙FSF GNU也不见得会来帮忙吼！

**Comment by ika-twb** [comment]
作为issue发起者我感觉这个issue可以lock或者删了。 现在的声明已经很好了。

**Comment by zypA13510** [comment]
@Ghost-chu 

我想您是不是对于开源协议有什么误会，开源许可协议的初衷不全是对开发者的保护，您本身就受著作权法的保护。即使您不添加任何协议，没有人可以未经授权使用您的代码。开源许可协议是对使用者的保护，保障使用者不因开发者突然自行改变授权条款而受影响，不因第三方、第三国的法律问题而意外承担责任。开源许可协议也是对贡献者的保护，保障所有贡献者都能确保自己所贡献的代码被按照自己所认同的开源协议去共享，而不是日后被某个项目领导者私有化。而您的”声明“中，关于用户如何使用软件的禁止性条款，恰恰是在打破这样的承诺。

我反复强调了这点，没有人强迫您使用GPLv3授权您的劳动成果，您可以不声称您的软件是开源软件，这是您的自由。如果您不提供授权，或者提供一个GPLv3以外的其他形式的授权，甚至您愿意把代码删了不再共享，这都是您的自由。但是您坚持要使用“GPLv3”来授权您的项目的话，它不允许您添加额外的条款与限制，包括您的“这一切的前提xxx“，GPLv3并不允许您修改协议条款本身或设置任何”前提条件“。

我看到您回复
> 至于你们爱用它干什么我完全管不到也根本无法阻止，我甚至根本不会知道你们私下拿去做了什么设计用途之外的事。

我不知道我可不可以这样说，其实您也并不在乎法律细节，不在乎条文是否被遵守。那我前面已经说了，您并不需要专门加上一个GPLv3的协议。协议和条款的存在是给在乎协议与条款细节的人的，既然您不在乎，那为何又要添加条款呢？如果您认为由于您所处的环境开发开源软件会导致法律风险，不开源即可。或者，您可以说从x.x版本开始，不再以GPLv3协议进行授权。至于过往版本，您甚至可以删除代码，只要您同时不再提供过往版本的二进制文件（如果您继续提供过往版本的二进制文件，GPLv3的授权是不可逆的，您就有提供相应源代码的责任义务）。

至于您所处的环境是否存在您说的法律风险，与这个授权许可协议的讨论毫无关联。也许您所在地区的政府保护开源软件开发者，也许不保护，但我的理解您所在地区的政府并没有强迫您使用GPLv3进行授权。

**Comment by Ghost-chu** [comment]
> [@Ghost-chu](https://github.com/Ghost-chu)
> 
> 我想您是不是对于开源协议有什么误会，开源许可协议的初衷不全是对开发者的保护，您本身就受著作权法的保护。即使您不添加任何协议，没有人可以未经授权使用您的代码。开源许可协议是对使用者的保护，保障使用者不因开发者突然自行改变授权条款而受影响，不因第三方、第三国的法律问题而意外承担授权被撤回的风险。开源许可协议也是对贡献者的保护，保障所有贡献者都能确保自己所贡献的代码被按照自己所认同的开源协议去共享，而不是日后被某个项目领导者私有化、收购，又或是第三方私自贩卖。而您的”声明“中，关于用户如何使用软件的禁止性条款，恰恰是在打破这样的承诺。
> 
> 我反复强调了这点，没有人强迫您使用GPLv3授权您的劳动成果，您可以不声称您的软件是开源软件，这是您的自由。如果您不提供授权，或者提供一个GPLv3以外的其他形式的授权，甚至您愿意把代码删了不再共享，这都是您的自由。但是您坚持要使用“GPLv3”来授权您的项目的话，它不允许您添加额外的条款与限制，包括您的“这一切的前提xxx“，GPLv3并不允许您修改协议条款本身或设置任何”前提条件“。
> 
> 我看到您回复
> 
> > 至于你们爱用它干什么我完全管不到也根本无法阻止，我甚至根本不会知道你们私下拿去做了什么设计用途之外的事。
> 
> 我不知道我可不可以这样说，其实您也并不在乎法律细节，不在乎条文是否被遵守。那我前面已经说了，您并不需要专门加上一个GPLv3的协议。协议和条款的存在是给在乎协议与条款细节的人的，既然您不在乎，那为何又要添加条款呢？如果您认为由于您所处的环境开发开源软件会导致法律风险，不开源即可。或者，您可以说从x.x版本开始，不再以GPLv3协议进行授权。至于过往版本，您甚至可以删除代码，只要您同时不再提供过往版本的二进制文件（如果您继续提供过往版本的二进制文件，GPLv3的授权是不可逆的，您就有提供相应源代码的责任义务）。如果您认为有必要，您还可以编写自己的授权许可协议，这些都是可以的。
> 
> 至于您所处的环境是否存在您说的法律风险，与这个授权许可协议的讨论毫无关联。也许您所在地区的政府保护开源软件开发者，也许不保护，但我的理解您所在地区的政府并没有强迫您使用GPLv3进行授权。

PeerBanHelper 会继续保持现状，使用 GPLv3 协议对源代码授权，并叠加免责声明作为法律上的免责行为。这一点不会改变。

我不会继续在这个问题上浪费时间，你可以自由的 fork 本项目并移除免责声明以 “真正的” 符合 GPLv3 协议，但由此带来的潜在风险与我们无关。

**Comment by zypA13510** [comment]
> PeerBanHelper 会继续保持现状，使用 GPLv3 协议对源代码授权，并叠加免责声明作为法律上的免责行为

从头到尾本人都只是在阐述一个核心问题：就是您的“GPLv3”授权与您的免责声明并不兼容。请不要把这个问题跟您说的各种其他问题混为一谈。

条款的存在意义在于明确权责。现已明确指出了您的条款自相矛盾之处，您认为这种模糊或矛盾并无解决的必要。那添加条款还有什么意义呢？您目前的状态，无论把它叫做GPLv3也好，叫做您自己的China Public License v3也好，叫做未授权也好，并无实质区别，同样是处于提供源代码但并不开源的状态。那您为何一定要故意模糊边界？为何一定要蹭“开源”之名误导其他开源社区的参与者？

我也不愿意继续在这个问题上浪费时间，请您自便
