### ISSUE TITLE
[Other] 运营商疯狂封禁pcdn，为了宽带安全，如何只放行本省ip

### ISSUE THREAD

**Issue by linksluckytime** [PBH-BTN/PeerBanHelper#805]
### 问题描述 - Issue Description

由于近期运营商疯狂封禁pcdn，想请问怎么设置，单放行本省ip

### 检查清单 - Check list

- [X] 这不是一个错误 （BUG） (This is not an bug/error)
- [X] PeerBanHelper 已更新到最新版本，非最新版本不接受任何错误反馈，任何非最新版本的 Issue 将被 立 刻 关 闭，不会有人给您提供任何支持 (I'm running the latest version of PBH that can be found in Github Relases, non-latest release won't receive any support)
- [X] 我已检查过 [PBH 文档](https://docs.pbh-btn.com/)（特别是常见问题），且即使使用了搜索也没有找到与此有关的内容 (This not a question/or the question that not listed in README's FAQ or [PBH WIKI](https://docs.pbh-btn.com/))
- [X] 我同意遵守 PBH-BTN 包容性条约，不发布 “嘲讽、骂战、引战、开盒（有时也称为人肉搜索）、人身攻击、仇恨、暴力、侮辱性言辞、违法违规、黑灰产、危害国家安全、实施或帮助他人实施电信犯罪” 等内容。并已知晓如果仍旧发布了这些内容，我的账号将立刻从包括但不限于 PBH-BTN 组织、社交软件中封禁。所有主题、内容都将被立刻删除或折叠，撤销、删除和收回您所做出的一切贡献，并封禁 BTN 网络的中账号权限、排除您所提交的所有数据。在您违反相关规则时，PBH-BTN 将会将您的注册、登录、和最近访问的 IP 地址、电子邮件地址、以及其它可能追踪您或将您去匿名化的信息从定期删除转为永不删除，并在任何国家或地区的政府、公安机关或有关部门需要时无通知的提供这些数据。 (I agree to abide by the PBH-BTN Inclusivity Pact by not posting content such as “taunting, name-calling, war-mongering, open-boxing (sometimes referred to as mansplaining), personal attacks, hatred, violence, insulting language, illegal activities, black and grey business, endangering national security, and committing or assisting others in committing telecommunication crimes”. I am aware that if I continue to post such content, my account will be immediately banned from organizations including but not limited to PBH-BTN, social software. All topics and content will be immediately deleted or collapsed, all contributions will be revoked, deleted and retracted, and you will be banned from the BTN network and all data you have submitted will be excluded. In the event of a violation of these rules, PBH-BTN will delete your registration, login, and most recent IP address, email address, and any other information that may be used to track you or de-anonymize you from regular to permanent deletion, and will make this data available to the government, public security, or other relevant authorities without notice if they request it, no matter what country or region.)

**Comment by Ghost-chu** [comment]
每个省根据 BTN 数据统计，都有不同规模的刷流情况存在，即使只放行本省 IP，也不能解决上传流量的问题。封禁是双向的，这也意味着你在下载资源是无法连接到除本省以外的任何人。


要仅放行本省 IP 地址：

## 方式1

需要获取本省主要运营商的 IP CIDR 段，并将其添加到设置->首选项->全局配置->忽略地址列表中。随后在任意封禁模块中设置一个匹配全部 Peer 封禁的封禁规则即可。

如果需要获取 IP CIDR 段，请自行编写代码从 GeoIP 库中读取整理。

## 方式2

自行编写 AvaitorScript 脚本，通过规则管理->自定义脚本上传应用，对本省以外的 IP 地址采取 BAN 操作，而对本省 IP 地址 SKIP（强制放行并忽略其它所有模块）。

---

考虑到这种行为不被支持，且不利于 BT 环境，同时也不能明显改善被吸血这一根本问题，因此我不会做出任何更加详细的指导。
