### ISSUE TITLE
[WebUI] IP 查询界面输入“:”后接着输入数字、字母首个数字字母前的冒号会冒号会错位

### ISSUE THREAD

**Issue by CreeperAWA** [PBH-BTN/PeerBanHelper#850]
### WebUI 版本号 - Version

v2.4.3(24761399) 

### 问题描述 - Issue Description

IP 查询界面输入“:”后接着输入数字、字母首个数字字母前的冒号会冒号会错位，不太好描述，直接看截图吧

### 复现步骤 - Reproduce steps

1.找到 IP 查询页面
2.输入一个冒号（这个冒号是对比用的），再输入一个冒号，然后紧接着输入数字、字母
3.出现 BUG

### 截图 - Screenshot  

![image](https://github.com/user-attachments/assets/8438c39c-6553-4477-806c-58aa8aad8f47)
![image](https://github.com/user-attachments/assets/e8f4901d-6fba-49a6-9fc4-ee567d5c3fad)

### 检查清单 - Check list

- [X] PeerBanHelper 已更新到最新版本，非最新版本不接受任何错误反馈，任何非最新版本的 Issue 将被 立 刻 关 闭，不会有人给您提供任何支持 (I'm running the latest version of PBH that can be found in Github Relases, non-latest release won't receive any support)
- [X] 我已检查过 [PBH 文档](https://docs.pbh-btn.com/)（特别是常见问题），且即使使用了搜索也没有找到与此有关的内容 (This not a question/or the question that not listed in README's FAQ or [PBH WIKI](https://docs.pbh-btn.com/))
- [ ] 我没有检查这个检查清单，只是闭眼选中了所有的复选框，请关闭这个 Issue (I have not read these checkboxes and therefore I just ticked them all, Please close this issue)
- [X] 所添加的下载器已满足 README 中的前置要求（如版本号和插件）(The downloaders that I've added already satisfied the requirements (E.g install plugins/adapters))
- [X] 我同意遵守 PBH-BTN 包容性条约，不发布 “嘲讽、骂战、引战、开盒（有时也称为人肉搜索）、人身攻击、仇恨、暴力、侮辱性言辞、违法违规、黑灰产、危害国家安全、实施或帮助他人实施电信犯罪” 等内容。并已知晓如果仍旧发布了这些内容，我的账号将立刻从包括但不限于 PBH-BTN 组织、社交软件中封禁。所有主题、内容都将被立刻删除或折叠，撤销、删除和收回您所做出的一切贡献，并封禁 BTN 网络的中账号权限、排除您所提交的所有数据。在您违反相关规则时，PBH-BTN 将会将您的注册、登录、和最近访问的 IP 地址、电子邮件地址、以及其它可能追踪您或将您去匿名化的信息从定期删除转为永不删除，并在任何国家或地区的政府、公安机关或有关部门需要时无通知的提供这些数据。 (I agree to abide by the PBH-BTN Inclusivity Pact by not posting content such as “taunting, name-calling, war-mongering, open-boxing (sometimes referred to as mansplaining), personal attacks, hatred, violence, insulting language, illegal activities, black and grey business, endangering national security, and committing or assisting others in committing telecommunication crimes”. I am aware that if I continue to post such content, my account will be immediately banned from organizations including but not limited to PBH-BTN, social software. All topics and content will be immediately deleted or collapsed, all contributions will be revoked, deleted and retracted, and you will be banned from the BTN network and all data you have submitted will be excluded. In the event of a violation of these rules, PBH-BTN will delete your registration, login, and most recent IP address, email address, and any other information that may be used to track you or de-anonymize you from regular to permanent deletion, and will make this data available to the government, public security, or other relevant authorities without notice if they request it, no matter what country or region.)

**Comment by Gaojianli** [comment]
<img width="1448" alt="image" src="https://github.com/user-attachments/assets/47cfd005-3c9b-4cff-a39c-7fd0b0e0b9fc" />
<img width="1203" alt="image" src="https://github.com/user-attachments/assets/fca83740-34d1-4428-ac42-0b87bbee6d68" />

**Comment by CreeperAWA** [comment]
https://github.com/user-attachments/assets/7c4e26b1-943f-4ddf-985b-9862efc71e0e

Google Chrome
Chrome 已是最新版本
版本 131.0.6778.205（正式版本） （64 位）

版本	Windows 11 专业工作站版
版本号	23H2
安装日期	‎2024-‎07-‎29
操作系统版本	22635.4300
体验	Windows 功能体验包 1000.22700.1045.0

![image](https://github.com/user-attachments/assets/cbf9e876-16a4-40b1-b30f-abf0d3355b77)

该问题我同样也在 Microsoft Edge 中成功复现了
Microsoft Edge
版本 131.0.2903.112 (正式版本) (64 位)
请问还需要提供更详细的信息吗？

**Comment by CreeperAWA** [comment]
将浏览器的字体更换为 Segoe UI 同样成功复现
将网页字体更换为英文同样成功复现
请问您使用的是什么字体？我尝试一下

**Comment by CreeperAWA** [comment]
看样子您的猜测是对的，我更换 Windows10 虚拟机就正常了
![image](https://github.com/user-attachments/assets/941644c2-d7a9-4bba-8084-c239a4d516b6)

**Comment by Gaojianli** [comment]
可以尝试在其他软件的输入框测试一下

**Comment by CreeperAWA** [comment]
我第一次遇到这个问题就是在 PBH 的 WebUI 中，其它地方都是正常的（包括软件和网页）
