### ISSUE TITLE
伪造进度的没有被屏蔽

### ISSUE THREAD

**Issue by qwqcwcawa** [PBH-BTN/PeerBanHelper#98]
![Screenshot_2024-05-02-20-19-47-881_dev bartuzen qbitcontroller-edit](https://github.com/PBH-BTN/PeerBanHelper/assets/156668576/5333e47b-b81e-43bb-9901-91e3d2413172)
![Screenshot_2024-05-02-20-20-09-744_dev bartuzen qbitcontroller-edit](https://github.com/PBH-BTN/PeerBanHelper/assets/156668576/507132ac-768d-4a8d-926c-e08cd06f067d)
一个我没在网络上发布过的种子
[FLIP_FLOP RAMBLING OVERRUN.zip](https://github.com/PBH-BTN/PeerBanHelper/files/15188578/FLIP_FLOP.RAMBLING.OVERRUN.zip)
多了一个来自114.132.251.29的连接，刚开始对面进度和我上传的数据只差了0.03%就没管它，后面我又看了一下发现它的端口从60803变成了49635因为端口变了导致qbittorrent记录的已上传数据重置，它的进度显示27.7%而我实际上传了1.06G和他的进度差了大概12%并且没有触发封禁
配置:maximum-difference: 0.06

**Comment by Ghost-chu** [comment]
请提供PBH版本号信息，profile.yml文件，打包上传

**Comment by qwqcwcawa** [comment]
> 请提供PBH版本号信息，profile.yml文件，打包上传

PeerBanHelper.jar v3.3.7
[profile.zip](https://github.com/PBH-BTN/PeerBanHelper/files/15189194/profile.zip)
